### ISSUE TITLE
Mark console prompt as unselectable

### ISSUE THREAD

**Issue by tokideveloper** [rouge-ruby/rouge#1023]
Some people like copying shell commands from a web page in order to paste them into their terminals. Since copying the whole or parts of the prompt might lead to dumb mistakes, this should become impossible.

Hint: Simply setting the CSS property `*user-select` to `none` for a tag embracing the prompt should do it. See [w3schools.com](https://www.w3schools.com/cssref/css3_pr_user-select.asp).

This concerns the lexer `console` alias `terminal` alias `shell_session` alias `shell-session`.

**Comment by dblessing** [comment]
I'm not sure if Rouge is an appropriate place to handle such things. Rouge is intended for highlighting only. I'll consider if further and ask for some input from others.

**Comment by tokideveloper** [comment]
> I'm not sure if Rouge is an appropriate place to handle such things. Rouge is intended for highlighting only.

Assuming there exists another tool that handles this issue. Then this tool should recognize the beginnings and the endings of all prompts as determined by `rouge` in order to match the highlighting. And such a tool would probably operate on the result from `rouge`. Seems to be difficult to implement in my view.

A quick **compromise**: `rouge` could tag each prompt as a whole and assign it to a special class like `shell-prompt`, but does NOT set `*user-select` to `none` for that class. Instead, tell the users to add an appropriate style for `shell-prompt` on their own if they like to do so.

**Comment by jneen** [comment]
Unfortunately, the lexer layer is completely separated from HTML - it's only the formatter that can create HTML.

It *would* be possible to use an `Escape` lexer to accomplish this, but it would require effort on the part of the content editor.

**Comment by jneen** [comment]
You can also rely on the fact that the prompt receives the `Generic::Prompt` styling, so it's in a `<span>` tag with class `gp`. You can set this to be unselectable with CSS:

``` css
.highlight .gp {
  user-select: none
}

**Comment by pyrmont** [comment]
@jneen's solution is the correct one. CSS is the appropriate place to handle this.
