### ISSUE TITLE
Support JSON With Comments

### ISSUE THREAD

**Issue by connorshea** [rouge-ruby/rouge#1028]
VS Code supports it, as does GitHub linguist.

A bit of JSON with comments, using the identifier `json`:
```json
{ 
  // This is json
  "json": true
}
```

A bit of JSON with comments, using the identifier `jsonc`:
```jsonc
{ 
  // This is jsonc
  "json": true
}
```

Rouge doesn't recognize jsonc as a valid language.

**Comment by sormy** [comment]
Seems like done here: https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/json_doc.rb

**Comment by jneen** [comment]
We could add `jsonc` as an alias for `json_doc` I suppose!

**Comment by asbjornu** [comment]
When the fenced code block uses the `http` language specifier and the `Content-Type` equals `application/json`, how do we switch from the default `json` lexer to the `jsonc` lexer for the contents in the HTTP body of the code block? Example:

````
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  // It would be nice if this comment was supported
  "foo": "bar"
}
```
````

**Comment by jneen** [comment]
@asbjornu If you wouldn't mind creating a new issue next time, it'd make it easier for us to reference. I've pushed what I think addresses the above in #1592.
