### ISSUE TITLE
Parse error with shell heredoc

### ISSUE THREAD

**Issue by ghost** [rouge-ruby/rouge#1042]
With here documents (heredoc), the "string" begins after the first line. However
the parser thinks it starts right after the identifier. This is usually not a
problem because the identifier is at the end of line:

~~~sh
wc <<eof
aaaaa bbbbb
ccccc ddddd
eeeee fffff
eof
~~~

However this is not required: the identifier can be at the beginning of the line
with even a full pipeline after:

~~~sh
<<eof wc | sed 's/e/E/'
aaaaa bbbbb
ccccc ddddd
eeeee fffff
eof
~~~

**Comment by cup** [comment]
workaround is to use Perl highlighting:

~~~pl
<<eof wc | sed s/e/E/
one
two
three
eof
~~~
