### ISSUE TITLE
Java highlighting don't differentiate between field name and field type

### ISSUE THREAD

**Issue by ori-sh** [rouge-ruby/rouge#1043]
For example, a field `private String name;` will result with both `String` and `name` highlighted the same way.
See the following example:
http://rouge.jneen.net/pastes/Djqw
Both the field type and the field name get the `n` class so I can't highlight them differently.

I would expect that each will have its own class so I can get to a result looks like this:
![image](https://user-images.githubusercontent.com/14040749/49085869-b9537400-f25b-11e8-8410-bd3231df5bbe.png)

**Comment by pyrmont** [comment]
I've submitted a PR that adds two very simple rules for matching constant names and class names based on Java's naming conventions.
