### ISSUE TITLE
Coffeescript: Multiline comments

### ISSUE THREAD

**Issue by ian-flowhub** [rouge-ruby/rouge#1045]
**Bug**
Coffeescript multiline comments aren't working if there's any characters after the opening `###` i.e. `###*`

```coffeescript
###*
* This is a comment
###

sayName: (name) ->
  console.log(name)

###*
* Here's another comment
###
```

**Actual Behavior**

The following code is showing up as a comment.
```
###

sayName: (name) ->
  console.log(name)

###*
* Here's another comment
###
```

https://github.com/jneen/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/lib/rouge/lexers/coffeescript.rb#L46

**Comment by pyrmont** [comment]
[Here](http://rouge.jneen.net/pastes/882v) is an example of the formatting bug. @ian-flowhub has identified the problematic line. Will have a look at fixing it.
