### ISSUE TITLE
Kotlin Nested Comments Format Incorrectly

### ISSUE THREAD

**Issue by commonsguy** [rouge-ruby/rouge#1049]
Kotlin supports nested multiline comments:

```kotlin
/*
  It's
  /*
    comments
    /*
      all
      /*
        the
        /*
          way
          /*
            down!
          */
        */
      */
    */
  */
*/
```

Rouge's lexer handles the first `*/` OK, but it treats the rest as individual elements. So, if I run `rougify highlight -f html comment.kt` with the above code as `comment.kt`, I get:

```html
<span class="cm">/*
  It's
  /*
    comments
    /*
      all
      /*
        the
        /*
          way
          /*
            down!
          */</span>
        <span class="p">*/</span>
      <span class="p">*/</span>
    <span class="p">*/</span>
  <span class="p">*/</span>
<span class="p">*/</span>
```

I would expect something more like:

```html
<span class="cm">/*
  It's
  /*
    comments
    /*
      all
      /*
        the
        /*
          way
          /*
            down!
          */
        */
      */
    */
  */
*/</span>
```

Tested using Rouge and `rougify` 3.3.0.

Let me know if you need additional information &mdash; thanks!

**Comment by pyrmont** [comment]
I've submitted a PR that I think fixes this problem. To permit arbitrary nesting, I've changed things so that the lexer now puts a `:comment` state on the stack when it encounters a block comment that is not single line.
