### ISSUE TITLE
Swift: Reference property on variable / instance

### ISSUE THREAD

**Issue by lordcodes** [rouge-ruby/rouge#1050]
Currently, when a property is referenced on a variable, parameter or type instance, it is unhighlighted.

http://rouge.jneen.net/pastes/9XDe

```swift
let thing = MyClass()
thing.value = 3

func doSomething(on thing: MyClass) {
  thing.value = 4
}
```

In this markdown example, you can see 'value' being highlighted as a property. With Rouge, 'value' isn't highlighted.

**Comment by pyrmont** [comment]
The situation here is similar to #1051.

My understanding is that parentheses [are always required](https://docs.swift.org/swift-book/LanguageGuide/Functions.html) and so a simple rule might be to look for something like:

```ruby
rule r%'(#{instance_name})\.(#{fn_name})' do
  groups Name, Name::Function
end
```

assuming you had some `instance_name` and `fn_name` regular expressions set up.

I think the concern here is that the increased complexity of the lexer makes it more difficult to analyse for future bugs for, arguably, a minor gain in readability.
