### ISSUE TITLE
Kotlin: Function calls and property accesses not highlighted

### ISSUE THREAD

**Issue by lordcodes** [rouge-ruby/rouge#1051]
When calling a function or referencing a property on an instance in Kotlin, it isn't highlighted.

http://rouge.jneen.net/pastes/kjD5

```kotlin
thing.value = 3
thing.doSomething()
```

It can be seen that it isn't highlighted with GitHub markdown either. In the example, 'value' should be highlighted as a property and 'doSomething' should be highlighted as a function call.

**Comment by pyrmont** [comment]
Yeah, the Kotlin lexer doesn't have rules to identify these elements. Do functions in Kotlin always have parentheses? Or is it possible to call a function without them?

**Comment by lordcodes** [comment]
A regular function call will have parentheses, except when using trailing closure syntax. I.e. when the only argument is a closure, you can omit parentheses.

Also there is method reference syntax, but that could be treated as a separate thing.

**Comment by pyrmont** [comment]
In that case, you should be able to identify it with a positive lookahead like this: `/...(?=\s*[({])/`
