### ISSUE TITLE
Kotlin: Constructor calls not highlighted

### ISSUE THREAD

**Issue by lordcodes** [rouge-ruby/rouge#1052]
When instantiating an object, the class name (constructor call) isn't highlighted in Kotlin.

http://rouge.jneen.net/pastes/kjD5

```kotlin
val thing = MyClass()
```

'MyClass' in the example, which is successfully highlighted with GitHub markdown.

**Comment by pyrmont** [comment]
This seems like a bit of a tricky problem.

`MyClass` is being highlighted in your example but it's being highlighted as a plain 'name' identifier the same as a regular function would be. I gather the GitHub highlighter is doing what it's doing by assuming that any identifier that begins with a capital letter is a class name but, as best as I can tell, that's merely [a coding convention](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules) and not actually part of the language.

I assume this particular convention is so strong as to be almost a rule?

**Comment by pyrmont** [comment]
The Scala lexer uses the 'class begins with a capital letter' heuristic:

https://github.com/rouge-ruby/rouge/blob/6c7da8adaab1aa9deb4564ba7d40b47e93872524/lib/rouge/lexers/scala.rb#L67

Are you able to add something like this to the Kotlin lexer and submit a PR, @lordcodes?

**Comment by lordcodes** [comment]
Yes, I think this is a fair assumption and is very commonly used as a rule for matching class names in other highlighters and lexers I believe.

Sure thing, will add when I get a chance.
