### ISSUE TITLE
Cleaning up pull requests - Reviewed lexer PRs

### ISSUE THREAD

**Issue by vidarh** [rouge-ruby/rouge#1063]
@dblessing, as per discussion in order to make it easier to keep track, here is a list of pull requests I've reviewed that I believe are in a ok state to get merged.  I'm happy to create a single pull-request and clean-up minor issues (second list), and squash commits for these so there's one commit per lexer, if it'll help.

## Lexers ok to merge as is

 * #1057 Lexer for ARM assembly
 * #1044 Lexer for (SmallWorld) Magik
 * #1039 Lexer for CSV Schema language
 * #1037 Lexer for BrainF*ck
 * #1036 Lexer for GDScript
 * #1033 Lexer for OpenEdge ABL
 * #1020 Lexer for FreeFem++
 * #1019 Lexer for Lean
 * #1014 Lexer for Alda
 * #963 Lexer for CUDA
 * #905 Lexer for Lustre/Lutin
 * #872 Lexer for SPARQL
 * #867 Lexer for Slice interface language
 * #836 Lexer for HOCON
 * #749 Lexer for Supercollider

## Lexers w/frozen-string literal comment missing and/or minor textual cleanup only

(I'm happy to clean these up if the original authors don't)

 * #891 Lexer for ISBL
 * #884 Lexer for YARA
 * #871 Lexer for JSL
 * #864 Lexer for OpenTypeFeature
 * #814 Lexer for Squirrel
 * #789 Lexer for GCode
 * #724 Lexer for GAL

## Prerequisite

Note that we should get #1062 (the CI fix) agreed and merged first, as some of the above have CI failures - all of them should only be because of the CI issue, but obviously worth verifying.

## Other lexers

This leaves five new lexers I've requested changes for that I don't think are ready yet (#1021, #989, #880, #710, #876), but that can be with relatively small fixes. There's a further 17 I've reviewed where there was enough discussion or complexity that they'll need more detailed time spent on each lexer. Some of these may very well be ok but I can't tell without spending more time on them.

EDIT: Added #1037 
EDIT2: Added #836 #749 and #905 
EDIT3: Added #891, #884, #871, #864, #814, #789, #724

**Comment by miparnisari** [comment]
Is it possible to have this merged soon? @dblessing @vidarh

**Comment by geoffroymontel** [comment]
It would be super nice if supercollider lexer could be merged indeed, working on the new website ! best

**Comment by gferreira** [comment]
OpenTypeFeature lexer #864 should also be ready to merge… thanks!

**Comment by pyrmont** [comment]
@gferreira I've reviewed that PR (sorry, it fell victim to the fact I'm going through them in reverse chronological order) and have left some feedback for the author. Will wait to see how they respond.

**Comment by MedvedTMN** [comment]
ISBL lexer [#891](https://github.com/rouge-ruby/rouge/pull/891) should also be ready to merge… thanks!

**Comment by pyrmont** [comment]
@MedvedTMN I've addressed #891 more fully on the discussion page for the PR.
