### ISSUE TITLE
Add helper for identifier pattern in lexers

### ISSUE THREAD

**Issue by vidarh** [rouge-ruby/rouge#1064]
These blocks occur in some variation in 30-40 lexers (based on a couple of cursory grep's), and a further number of lexers *could* use it, but does some variation of bulding big "|" blocks across one or more regexes, see e.g. the nim and shell lexers:

```ruby
        rule id do |m|
          name = m[0]

          if self.class.keywords.include? name
            token Keyword
          elsif self.class.keywords_type.include? name
            token Keyword::Type
          elsif self.class.reserved.include? name
            token Keyword::Reserved
          elsif self.class.builtins.include? name
            token Name::Builtin
          else
            token Name
          end
```

Since this is a very common pattern, I propose we add the appropriate default methods for this, and a helper to define the rule.

**Comment by pyrmont** [comment]
@vidarh Since coming on as a maintainer I've seen this pattern a lot as well. However, I've found enough variations of it that I don't believe it would be that helpful. Thanks for the suggestion and maybe something to revisit in the future.
