### ISSUE TITLE
Consider semi-automatic support for other lexer description formats

### ISSUE THREAD

**Issue by vidarh** [rouge-ruby/rouge#1066]
#1054 contains links to Sublime and VIM syntax files for Dhall. Looking at that, Sublime appears to use a static YAML format with regexes, while VIM appears to use a script, but with most of it boiling down to a bunch of regexes. 

Additionally [gtk-source-view uses an XML format](https://developer.gnome.org/gtksourceview/unstable/lang-reference.html). While there's obviously a lot of overlap, a cursor look at the GtkSourceView language definition list shows that it'd give Rouge support for surprisingly many additional languages/file formats.

Any of these could potentially be supported by either writing a generic lexer class that can read them (possibly a subclass of the regex lexer as they're all regex based) and be used to lex files, or a tool to write out a starting point of a regex lexer subclass. The latter is probably easiest, as it doesn't require getting everything right. Upside of the former, on the other hand would be that we'd get "instant" support for any language supported by either of the three. 

Either way, it'd let us expand supported formats/languages a lot easier. Which is preferable I think comes down to how easy it is to get good/precise mapping of the token types for those three to Rouge.

I may take a stab at this when I get a chance, but if anyone beats me too it I'll be happy :)

**Comment by pyrmont** [comment]
I agree that this is an interesting idea. Even if all it was was a Rake task that could convert a syntax file to a Rouge class, that seems like something that could help people who want to contribute get started.

**Comment by vidarh** [comment]
@pyrmont I might potentially finally take a look at this soon, as I need a highlighter for asciidoc and there is one in the gtksourceview format. I'll update this ticket if I get a chance to make a start on it.

**Comment by pyrmont** [comment]
@vidarh Hey! Long time no see (in the repo :P). That'd be great as something to have :)
