### ISSUE TITLE
Make prefix of CSS classes for tokens configurable

### ISSUE THREAD

**Issue by mojavelinux** [rouge-ruby/rouge#1074]
Currently, the token shortname is used directly as the CSS class for a token. Due to the brevity of the shortnames (e.g., `err`), when the Rouge stylesheet is combined with other stylesheets in a site, this can lead to styling conflicts.

I'd like to propose that the CSS classes prefix for tokens be made configurable. I suggest using the name `token_class_prefix` (e.g., `token_class_prefix: 'tok-'`)

It's relevant to note that Pygments offers this option (as `classprefix`), so this could prove important for Pygments compatibility as well.

**Comment by mojavelinux** [comment]
I'm happy to send a PR for this issue, but I'm waiting on a decision about the name of the option. Is my proposal acceptable?

**Comment by pyrmont** [comment]
@jneen What do you think of the `tok-` prefix idea? Seems like a good idea to me.

**Comment by mojavelinux** [comment]
I'm still willing to send a PR if I can get confirmation this is an acceptable proposal.
