### ISSUE TITLE
Syntax highlighting in Rust failure: println!("a\"b");

### ISSUE THREAD

**Issue by d33tah** [rouge-ruby/rouge#1075]
In all views that use syntax highlihting, a Rust expression println!("a\"b"); breaks the hightlighting, considering \" as the end of a string. See the following code:

```
fn main() {
    println!("a\"b");
}
```

Related: http://rouge.jneen.net/pastes/5gRR

**Comment by pyrmont** [comment]
I've submitted a fix. The problem appears to have been caused by the double quote not  being in the list of escape characters for some reason.
