### ISSUE TITLE
Drop support of unmaintained Ruby versions

### ISSUE THREAD

**Issue by marius-balteanu** [rouge-ruby/rouge#1081]
Currently, according to Travis, the supported Ruby version are the following:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"

but the support was ended for:
- "2.0" in 2013-02-24
- "2.1" in 2013-12-25
- "2.2" in 2018-03-31

Please see: https://www.ruby-lang.org/en/downloads/branches/

**Comment by marius-balteanu** [comment]
Related to #1062

**Comment by pyrmont** [comment]
This has been addressed by #1110 and #1128. As discussed in #1115, older versions of Ruby will continue to be part of the CI builds for now.

Thanks for submitting the PR @marius-balteanu! I'm sorry it took so long to get back to you on it.

**Comment by marius-balteanu** [comment]
No problem! thanks for your response.
