### ISSUE TITLE
HTMLTable formatter cannot wrap HTMLLinewise formatter

### ISSUE THREAD

**Issue by mojavelinux** [rouge-ruby/rouge#1082]
The HTMLTable formatter cannot wrap the HTMLLinewise formatter (or similar). The reason is that the HTMLTable formatter delegates to the wrong method on the inner formatter. Instead of delegating to the stream method, it delegates to the span method. This makes the HTMLTable assume too much about the inner formatter. It also makes it impossible to insert a line-wise formatter in between the HTMLTable and HTML formatter.

The following code example demonstrates the issue:

```rb
require 'rouge'

source = File.read(File.expand_path('~/.gemrc'))
formatter = Rouge::Formatters::HTML.new
formatter = Rouge::Formatters::HTMLLinewise.new formatter
formatter = Rouge::Formatters::HTMLTable.new formatter
lexer = Rouge::Lexers::YAML.new
puts formatter.format(lexer.lex(source))
```

This results in:

```
lib/rouge/formatters/html_table.rb:31:in `block in stream': undefined method `span' for #<Rouge::Formatters::HTMLLinewise:0x00000000018426b8> (NoMethodError)
```

If the delegation were changes to the stream method, this example would work.

The HTMLTable formatter should only be decorating the contents of the code cell. It should not be involved in producing the cell contents.

**Comment by mojavelinux** [comment]
I'd be happy to submit a PR with a proposed change.

**Comment by tyteen4a03** [comment]
Just ran into this issue. Would be grateful for a fix.

**Comment by mojavelinux** [comment]
Fix is available here: https://github.com/jneen/rouge/pull/1083
