### ISSUE TITLE
HTMLLinewise formatter should preserve newlines

### ISSUE THREAD

**Issue by mojavelinux** [rouge-ruby/rouge#1084]
While it's tempting to wrap lines in `<div>` tags, this proves to be difficult to style inside a preformatted block. Better is to follow the approach that Pygments takes, which is to use `<span>` tags, preserve the newline, and place the closing tag just after the newline. This strategy requires no changes to existing CSS rules and allows the line span to be styled using `display: block` to add block-oriented styling.

**Comment by mojavelinux** [comment]
Using a `<div>` (without preserving the newline) also causes blank lines to be dropped.

**Comment by annfeera93** [comment]
GET URL/b2b-gateway/customers/wallet
