### ISSUE TITLE
csharp wrong highlighting using attributes with string params

### ISSUE THREAD

**Issue by dacanizares** [rouge-ruby/rouge#1093]
As you can see the string sent in the Router attribute is wrongly encoded: http://rouge.jneen.net/pastes/xlA9

Example of code to reproduce the issue:

```csharp
[Route("api/[controller]")]
[ApiController()]
public class UsersController : ControllerBase
{
    protected readonly IUsersRepository _repository;
    
}
```

You can see a similar code on the official docs: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#add-a-controller

**Comment by dacanizares** [comment]
As you can see here, string arguments are not being highlighted when used inside an attribute: http://rouge.jneen.net/pastes/pD9W

**Comment by pyrmont** [comment]
This was being caused by [this rule](https://github.com/rouge-ruby/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/lib/rouge/lexers/csharp.rb#L74). I've submitted a fix that removes it.
