### ISSUE TITLE
Haskell lexer parses ticked promoted constructors incorrectly

### ISSUE THREAD

**Issue by goolord** [rouge-ruby/rouge#1112]
https://dev.to/goolord/trasa-tutorial-pt-1-type-safe-web-routing-with-trasa-5b1p#our-route-type
Adding a `'` to data constructors which have been promoted to the kind level is convention in haskell, but ticked promoted data constructors seem to be being parsed as `Char` literals

**Comment by pyrmont** [comment]
@goolord Would PR #1027 fix this problem? There's a current effort to try to clear some of the backlog of outstanding PRs and would like to confirm whether this requires a different fix.

**Comment by goolord** [comment]
Yes, that would fix the problem. I couldn't find anything about this at a glance, apologies.

**Comment by pyrmont** [comment]
No no, no need to apologise! Just wanted to check :) Hopefully can get a fix out soon.

**Comment by goolord** [comment]
Alternatively: https://github.com/jneen/rouge/pull/1113 will also fix this issue

**Comment by pyrmont** [comment]
Oops, forgot to close this. Thanks @goolord!
