### ISSUE TITLE
Add debug documentation

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1144]
@miparnisari wrote in [a comment](https://github.com/rouge-ruby/rouge/pull/1111#issuecomment-497915820) in #1111:

> Can we add information on how to debug while developing? What I do is run `rackup >> debug.txt` and then load `localhost:9292/json?debug` which prints something like
   
   ```
   lexer: json
   stack: [:root]
   stream: "\"firstName\": \"John\","
     trying #<Rule /\s+/m>
     trying #<Rule /"/>
       got "\""
       yielding Literal.String.Double, "\""
       pushing :string
   lexer: json
   stack: [:root, :string]
   stream: "firstName\": \"John\",\n"
     trying #<Rule /[^\\"]+/>
       got "firstName"
       yielding Literal.String.Double, "firstName"
   ```

**Comment by pyrmont** [comment]
This is still outstanding.

**Comment by ComFreek** [comment]
I just found this issue and found it helpful for debugging. It's not stale!
