### ISSUE TITLE
Allocations in Guessers::Source

### ISSUE THREAD

**Issue by ashmaroli** [rouge-ruby/rouge#1148]
Tracing allocations from Rouge (current `master`) with `memory_profiler` on Jekyll's documentation source-code shows the following:

```
allocated memory by file
-----------------------------------
  27.43 MB  rouge/lib/rouge/guessers/source.rb

allocated memory by location
-----------------------------------
  22.98 MB  rouge/lib/rouge/guessers/source.rb:25
   4.38 MB  rouge/lib/rouge/guessers/source.rb:26

allocated objects by file
-----------------------------------
    192432  rouge/lib/rouge/guessers/source.rb

allocated objects by location
-----------------------------------
    127680  rouge/lib/rouge/guessers/source.rb:25
     63840  rouge/lib/rouge/guessers/source.rb:26
```
The code reported being:
https://github.com/rouge-ruby/rouge/blob/dabd56e19d0429a04d5dcf642d949bc20173a915/lib/rouge/guessers/source.rb#L24-L27

Debugging shows that the lines `#25` have been called a total of **63840 times** during the
`jekyll build` session.

**Comment by jneen** [comment]
I wrote this code long enough ago that I don't remember the specifics, but `methods(false).include?(sym)` is *definitely different* from `respond_to?`, and I would appreciate maybe looking into why that was used - there may be hints in the git history.

**Comment by jneen** [comment]
In particular `methods(false)` does not include superclass or module methods.

**Comment by pyrmont** [comment]
@ashmaroli updated the OP after creating the original issue. The PR memoised `methods(false).include?(:detect?)` not `respond_to?`.

**Comment by jneen** [comment]
If the current tests are insufficient (i believe they fail if it's replaced with `respond_to?`) maybe we could add a test that a subclass of a `detectable?` method is not marked as detectable?

**Comment by ashmaroli** [comment]
@jneen Before I proposed to add `Lexer.detectable?` I realized that the semantics of `respond_to?` was opposite of what `.methods(false)` was returning. Hence dropped the idea of replacing with `respond_to?`
`Lexer.detectable?` does the same thing as `Lexer.methods(false).include?(:detect?)` but it is a memoized method to avoid re-evalutaion from multiple instances of same lexer class.

I've updated the tests in `#1153`
