### ISSUE TITLE
Bring back CGI.escape_html in Formatters::HTML

### ISSUE THREAD

**Issue by ashmaroli** [rouge-ruby/rouge#1154]
Back when #114 shipped, `CGI.escape_html` was slow. But it has been [made faster since Ruby 2.3.0](https://github.com/ruby/ruby/commit/ce7f7f5e3d6c288b140870fa87c4b11e9a744f62)
```ruby
# frozen_string_literal: true

require 'benchmark/ips'
require 'cgi'

TEXT = 'Message: "Research & Development"'
TABLE_FOR_ESCAPE_HTML = {
  '&' => '&amp;',
  '<' => '&lt;',
  '>' => '&gt;',
}

def cgi_escape
  CGI.escape_html(TEXT)
end

def str_escape
  TEXT.gsub(/[<&>]/, TABLE_FOR_ESCAPE_HTML)
end

Benchmark.ips do |x|
  x.report('cgi_escape') { 1000.times { cgi_escape } }
  x.report('str_escape') { 1000.times { str_escape } }
  x.compare!
end
```
In spite of the `cgi_escape` method escaping quotes, it is `~ 4x faster` than `str_escape`.
Memory profiling above methods shows that `cgi_escape` allocates `4x lesser objects` as well.

**Comment by jneen** [comment]
That's new! When we first introduced the table it was orders of magnitude faster than CGI

**Comment by ashmaroli** [comment]
I was not aware of the optimization myself until the author himself pointed me to it:
https://bugs.ruby-lang.org/issues/15895

**Comment by jneen** [comment]
Yep. And our use of the table comes from #114, which was pre-optimization. +1 from me.

**Comment by mojavelinux** [comment]
The downside of this change is that it will cause a change in the output. In addition to escaping <, >, and &, CGI.escape_html also (unnecessarily) escapes " and ', which is only relevant for attribute values. (I really wish Ruby provided an accelerated method that only escaped the first three).

The alternative is `string.encode xml: :text` (which only does <, >, and &). (You  can make it match CGI.escape_html using `xml: :attr`).

**Comment by ashmaroli** [comment]
> The downside of this change is that it will cause a change in the output.

@mojavelinux  That's the reason I haven't submitted a PR for this yet.. :wink:

**Comment by mojavelinux** [comment]
I really wish CGI.escape_html wasn't so naive. I'm very glad to see that at least the `String#encode` method has an awareness of XML rules. It's just too bad that method wasn't accelerated too :/

**Comment by ashmaroli** [comment]
Closing this for now since quotes shouldn't be escaped in Rouge 3.x and because the issue has been partially optimized via https://github.com/rouge-ruby/rouge/commit/43615a64746f35ebffee82f8fd57b515feae689f

**Comment by jneen** [comment]
This is still the approach I would like to take for Rouge 4.x. We did once escape quotes as well - and while there's not strictly a need for it, it can be useful in some cases.

**Comment by mojavelinux** [comment]
Which cases?

**Comment by jneen** [comment]
In case you're passing formatted content in a `data-...="..."` attribute, for example.

**Comment by ashmaroli** [comment]
@jneen Can you add this to a `Rouge 4.0` Milestone so that it can be easily accessed in the future.
Thanks

**Comment by mojavelinux** [comment]
@jneen Thanks for that information. I agree it would be useful for that case.
