### ISSUE TITLE
When "sub" is used as key of a Perl hash, error tokens are rendered

### ISSUE THREAD

**Issue by miparnisari** [rouge-ruby/rouge#1164]
![image](https://user-images.githubusercontent.com/5374887/59175690-4c267280-8b0b-11e9-9092-0017316a4a7e.png)

When the lexer sees "sub" it thinks a function will follow:

```ruby
rule /sub\s+/, Keyword, :funcname
```

Maybe a simple negative lookahead is enough?

```ruby
rule /sub\s+(?!=>)/, Keyword, :funcname
```

**Comment by pyrmont** [comment]
Hmmm, it won't necessarily result in an error but I assume any bare word used in a hash will be highlighted incorrectly if it's a keyword, right?
For instance, `package` will have the same issue, won't it?

**Comment by jneen** [comment]
I'd be interested in how Perl parses this - does the hash context have specific parsing rules, or does the `=>` retroactively change the meaning of `sub`?

**Comment by alexkalderimis** [comment]
> does the `=>` retroactively change the meaning of `sub`?

`=>` causes bare-words to the left to be interpreted as strings, but is otherwise the same as `,`

**Comment by jneen** [comment]
Okay! Then something like `rule /(?=[^\n]*=>)/, :pre_arrow` to put us in the special state where barewords cannot be keywords?

**Comment by jneen** [comment]
It means we have to do a kind of big regex on every line though, and also we have to make sure we break regex scans on lines...

**Comment by pyrmont** [comment]
Can `=>` only occur inside parentheses? Maybe we need a state for function arguments (or whatever the correct terminology is in Perl for this kind of thing).

**Comment by miparnisari** [comment]
@pyrmont no, this is valid as well:

```perl
use constant EMPTY_SPACE => '&nbsp;';
```

**Comment by pyrmont** [comment]
Good to know. From what I can see, though, the use of the 'fat arrow' here is another special case. 

Based on a cursory search, it looks to me like the two cases are in a hash and in a constant pragma (see [here](https://perldoc.perl.org/perldata.html) and [here](https://perldoc.perl.org/constant.html)).

**Comment by jneen** [comment]
@miparnisari in your example, are `use` and `constant` interpreted as keywords or barewords?

**Comment by jneen** [comment]
Would this also be valid:

``` perl
use constant EMPTY_SPACE # comment
   => '&nbsp;'
```

**Comment by jneen** [comment]
or more to the point,

``` perl
foo(
  sub # comment
    => 1
)
```

**Comment by pyrmont** [comment]
@jneen It wants me to create an account to save a link to the code but the online editor [JDoodle](https://www.jdoodle.com/execute-perl-online) is compiling this and printing a reference to `$x`:

```perl
$x = { bareword # comment
       => "string" };
print "$x";
```

**Comment by miparnisari** [comment]
This is still an issue: http://rouge.jneen.net/v3.20.0/perl/IyEvdXNyL2Jpbi9lbnYgcGVybApyZXR1cm4gJG0tPmNvbXAoIm15Rm4iLCBzdWIgPT4gJ3NvbWV0aGluZycp

**Comment by pyrmont** [comment]
@miparnisari Thanks for confirming!
