### ISSUE TITLE
Line spans

### ISSUE THREAD

**Issue by ronalchn** [rouge-ruby/rouge#117]
Wow, just saw this library after putting pygments.rb into my app.

Support for wrapping each line with a span would be great. Because I let code wrap, the tableized line numbering doesn't actually work well. So I put use the css ::before pseudo-element to insert line numbers.

Apart from this, it could be a drop-in replacement, and it would allow me to fix the annoying `<pre><code></code></pre>` that pygments doesn't do, and which I can't fix because it's in python.

**Comment by jrfnl** [comment]
Another user just switched from pygments and looking for the same. The Rouge HTML output with the tables instead of the spans makes that the switch from Pygments to Rouge is not as straightforward as advertised.
