### ISSUE TITLE
Rouge may crash when formatting tokens if options are used with lexer instance

### ISSUE THREAD

**Issue by mojavelinux** [rouge-ruby/rouge#1175]
Rouge will sometimes crash when formatting tokens that were created using a lexer instance that was used with options.

The problem stems from a typo in the Lexer#lex method. Here's the problematic line: https://github.com/rouge-ruby/rouge/blob/6d62ba17dd50cc7dbc94c59c753c82c13a48db6d/lib/rouge/lexer.rb#L421-L424

The code is not actually checking for the `:continue` option, which can send the application down the wrong code path. As a result, very bizarre things start to happen.

**Comment by bbatsov** [comment]
I was just about report this! 😃  Thanks, @mojavelinux!

**Comment by mojavelinux** [comment]
Already have a fix too...because I was super curious ;)
