### ISSUE TITLE
Lexer#lex warns even when no options are passed in

### ISSUE THREAD

**Issue by mojavelinux** [rouge-ruby/rouge#1186]
Starting in 3.4.1, the following Rouge code generates a warning in verbose mode about the use of opts with Lexer.lex:

```rb
old_verbose, $VERBOSE = $VERBOSE, nil
require 'rouge'
$VERBOSE = old_verbose

source = 'puts "Hello, World!"'
formatter = Rouge::Formatters::HTML.new
lexer = Rouge::Lexer.find 'ruby'
formatter.format(lexer.lex(source))
```

The following message is printed when invoked using `ruby -w`:

```
The use of opts with Lexer.lex is deprecated
The use of opts with Lexer.lex is deprecated
```

The problem is that Rouge itself is passing the options, not the user. See https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/lexer.rb#L426-L429.

This warning did not occur in 3.4.0, so it has to do with this change: https://github.com/rouge-ruby/rouge/commit/6835352bfc70759d16acfbaf3bb33d9a16f06f24

**Comment by jneen** [comment]
@pyrmont the current state of this method makes no sense to me - I'll open a PR that deals with all the cases shortly.

**Comment by jneen** [comment]
In the future let's be a little more cautious about merging things like #1175 - I think there was a lot of confusion generated from an unnecessary sense of urgency.

**Comment by mojavelinux** [comment]
To be fair, this was a really difficult situation to reason about, so it's likely a very rare occurrence. For me, the source of the confusion is that Lexer.lex and Lexer#lex use the options *very* differently. Lexer.lex passes the options to the Lexer constructor, while Lexer#lex uses options for an internal concern. This is an easy thing to confuse, IMO.

**Comment by jneen** [comment]
Exactly - this is why we are deprecating the use of the options hash for something internal. In the future we may support passing options to `#lex`, but this deprecation step is necessary first.
