### ISSUE TITLE
The keyword endfor is not properly matched in the Liquid lexer

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1194]
**Name of the lexer**
Liquid

**Online example**
[rouge.jneen.net](http://rouge.jneen.net) is currently not accepting new pastes at the moment.

**Code sample**
A sample of the code that produces the bug.

```liquid
{% if x %}
Do something.
{% endif %}

{% for x in xs %}
Do something.
{% endfor %}
```

**Additional context**
This was discussed in PR #1192 (see [here](https://github.com/rouge-ruby/rouge/pull/1192#discussion_r294530920)).

**Comment by ashmaroli** [comment]
I think you should attach a "visual proof" to corroborate the complaint.

**Comment by pyrmont** [comment]
@ashmaroli Yeah. I need to work out what's wrong with [jneen.rouge.net](http://jneen.rouge.net/).

**Comment by ashmaroli** [comment]
> Yeah. I need to work out what's wrong with

What do the Heroku logs say?
