### ISSUE TITLE
HTMLTable formatter doesn't handle folded lines (soft line-breaks) properly

### ISSUE THREAD

**Issue by ashmaroli** [rouge-ruby/rouge#1201]
## Describe the bug

If I have a `div.container` with a fixed-width and nest the markup returned by Rouge's `HTMLTable` formatter within it, then `line_numbers` does not follow long lines that are folded onto the consecutive line.

## To Reproduce
1. Checkout the `v3.4.1` tag on the repository
    ```
    git checkout v3.4.1
    ```
2. Start `visual test app`:
    ```
    rackup
    ```
3. Inspect `ruby` lexer:
    ```
    (goto) http://localhost:9292/ruby?line_numbers=true
    ```

## Expected behavior

Expected "line-number cell" to increase in height corresponding to height of the "code-text cell".

### Faulty Line numbers

![Ruby Visual Test](https://user-images.githubusercontent.com/12479464/59763602-9223c900-92b7-11e9-81f5-a58f9fb78a8e.png)

### Raw sample with really long lines on disk

![Ruby Visual Test - raw sample](https://user-images.githubusercontent.com/12479464/59764010-7240d500-92b8-11e9-93d0-91182911a0e7.png)

### Rendered Text with soft line-breaks

![Ruby Visual Test - rendered](https://user-images.githubusercontent.com/12479464/59763884-39a0fb80-92b8-11e9-8216-b2806dafc7e5.png)

## System:

Field | Value
--- | ---
**OS** | Windows
**Ruby version** | Ruby 2.4.5
**Rouge version** | Rouge 3.4.1

## Additional context

This is reproducible on both latest `master` and with Rouge 3.3.0 as well.

**Comment by ashmaroli** [comment]
Looks like this would need a new `Formatter` subclass to avoid changing existing output from `HTMLTable` formatter in Rouge 3.x..

**Comment by ashmaroli** [comment]
@jneen Can I get your thoughts on this..?

**Comment by jneen** [comment]
We would need a new formatter subclass with a completely different approach

**Comment by ashmaroli** [comment]
> We would need a new formatter subclass

I went ahead to wrote a subclass that's hybrid between current `HTMLTable` and `HTMLLinewise`. It works as I expect but falls short *visually* because of the following code in the library:
https://github.com/rouge-ruby/rouge/blob/ab369162fe1c2b515bf3879ec15d6531c28ef43b/lib/rouge/theme.rb#L164-L174
