### ISSUE TITLE
PowerShell lexer highlights built-in names used as hashtable keys

### ISSUE THREAD

**Issue by gmckeown** [rouge-ruby/rouge#1208]
**Name of the lexer**
PowerShell

**Online example**
Not currently able to do this due to an error on the rouge.jneen.net site.

**Code sample**

```PowerShell
type somefile.txt

$mydata = @{
    key = "value"
    key2 = "value2"
    type = "bad highlighting"
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/22765233/59853696-4e899780-9369-11e9-9a37-2071d37957e2.png)

**Additional context**
I believe the lexer is not recognising the hashtable definition construct ```@{ }```, inside which it should not be highlighting built-ins.

**Comment by pyrmont** [comment]
I agree. The lexer needs a new rule in here somewhere, I think:

https://github.com/rouge-ruby/rouge/blob/ab369162fe1c2b515bf3879ec15d6531c28ef43b/lib/rouge/lexers/powershell.rb#L650-L665
