### ISSUE TITLE
PowerShell Lexer -- built-ins definition can be simplified

### ISSUE THREAD

**Issue by gmckeown** [rouge-ruby/rouge#1209]
PowerShell doesn't have a fixed set of built-in functions; rather, it uses cmdlets that follow a ```Verb-Noun``` naming format. The PowerShell lexer currently identifies each of the standard cmdlets by name, which amounts to some 1900 built-ins. This won't correctly highlight any other cmdlet that correctly follows the ```Verb-Noun``` format.

One option would be to highlight anything that matches the regex ```\w+-\w+```, but I wonder if that might be a little bit *too* generic.

So instead, I'd propose using [Microsoft's list of approved verbs](https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands) as a starting point; i.e. anything that matches ```Verb-\w+``` for the approved verbs (plus a few other common ones) should match as a built-in. This appears to be the approach followed by, for example, the Visual Studio Code syntax highlighting for PowerShell; it highlights ```Write-MyCustomCmdlet``` but not ```Nonsense-MyCustomCmdlet```.

I've tested a modified version of the powershell.rb lexer file with this change (pull request to follow), but I'm after some feedback as to whether this change is considered desirable by a wider audience.

Tagging a few potentially interested parties for this reason: @aaroneg @JacodeWeerd @michaeltlombardi @ypid-geberit @markroloff @miparnisari

**Comment by aaroneg** [comment]
You're certainly welcome to give it a shot, just keep in mind that not even
Microsoft sticks to their approved verb list. The version I put forward was
only ever meant to be quick and dirty since creating lexers isn't really a
skill of mine. I wonder if anything can be gained by seeing how the vscode
ps extension lexer works.

**Comment by gmckeown** [comment]
@aaroneg Indeed, there are some non-standard prefixes in my pull-request, and they're for standard "special-case" cmdlets (e.g. ```Sort-Object``` and ```Tee-Object```)!! Also, a few to cover cmdlets that are in the current list, despite not using standard verbs (e.g. ```Apply-WindowsUnattend```).

Your quick'n'dirty lexer has been doing a pretty decent job for a few years now, with only a few tweaks needed. It was the addition of the PowerShell 5 cmdlets that really highlighted the need for a bit of streamlining! 😁

I'd definitely like to take apart the VSCode lexer to see if it can offer improvements to the Rouge lexer, but that's for another day when I've more time on my hands...

**Comment by aaroneg** [comment]
Looks like this is the newest release : https://github.com/PowerShell/vscode-powershell/releases/tag/v2019.5.0

**Comment by aaroneg** [comment]
So it looks like it's a seperate project: https://github.com/powershell/editorsyntax

**Comment by aaroneg** [comment]
And here is the file that makes the rules, it looks like:
https://github.com/PowerShell/EditorSyntax/blob/master/PowerShellSyntax.tmLanguage

**Comment by gmckeown** [comment]
That would make sense -- VSCode grammar files are [in TextMate format](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#textmate-grammars).

**Comment by aaroneg** [comment]
Interesting. I'm not sure how to make a good development environment for this - I only use rouge through gitlab. I think the first time i'd just take the gem and smash it into a gitlab omnibus install. Might do that again.

**Comment by gmckeown** [comment]
There is a way to test Rouge directly I think -- granted it has been a few years since I last did any work on it, but I'm pretty sure there was a way to generate a HTML page directly from Rouge on the command-line, thus avoiding the need to mess with GitLab...

Yeah, looks like it's [explained in the Rouge Wiki](https://github.com/rouge-ruby/rouge/wiki/Adding-a-new-lexer).

**Comment by aaroneg** [comment]
I've started here : https://github.com/aaroneg/rouge/tree/feature/upgrade-powershell
Have some basics done but not much. Could probably use help understanding the states.

**Comment by gmckeown** [comment]
Does this help? https://www.rubydoc.info/github/rouge-ruby/rouge/file/docs/LexerDevelopment.md

**Comment by aaroneg** [comment]
sortof. working through it by understanding the shell lexer a little better.

**Comment by pyrmont** [comment]
Hi guys :) Looks like you're basically past this point already but I wrote up a new document explaining how to set up your development environment. It's not yet merged into master but you can read the first draft [here](https://github.com/pyrmont/rouge/blob/87ffad9e8974bc83d653f653041a42a29b9a8ab7/docs/DevEnvironment.md). It's PR #1212 so if you have any comments on it, please put them there :)

**Comment by pyrmont** [comment]
In terms of the lexer design itself, the basic idea of the Shell lexer (of which the PowerShell lexer is a subclass) is that you have the 'basic' commands (covered by the rules in the `:basic` state) and 'data' (covered by the rules in the `:data` state).

The PowerShell lexer builds on top of the Shell lexer by adding rules to `:basic` (it puts these rules at the front by `prepend`ing then) and by replacing the rules in `:data`.

For this issue. I imagine you'll want to be updating the rules in `:basic` to introduce a rule that matches verb-noun commands.

**Comment by aaroneg** [comment]
Thanks Michael!
That does provide some clarity. I wrote the powershell lexer long enough
ago that I forgot most of it.

Mostly the stuff I needed today was related to how to create a new state,
mix other states in, and exit cleanly. I used the shell lexer pretty
heavily for examples. I think I came up with some acceptable solutions.
Have a look at the PR referenced in the thread and see if you agree.
