### ISSUE TITLE
Remove hard-coded CSS for tables

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1217]
**Is your enhancement request related to a problem? Please describe.**
Rouge 3.0 hard codes CSS for certain table elements into the theming output. Specifically:

https://github.com/rouge-ruby/rouge/blob/ab369162fe1c2b515bf3879ec15d6531c28ef43b/lib/rouge/theme.rb#L164-L174

**Describe the solution you'd like**
Rouge should not output these CSS rules. It should be left for the stylesheet.
 
**Additional context**
This was discussed briefly [here](https://github.com/rouge-ruby/rouge/pull/1211#issuecomment-505274853).

**Comment by jneen** [comment]
This will need to be on a major version release, as it will definitely break styling on people's websites.
