### ISSUE TITLE
Inconsistent constructor API for formatters

### ISSUE THREAD

**Issue by ashmaroli** [rouge-ruby/rouge#1218]
## Summary

The various formatters are initialized inconsistently and therefore a downstream factory method needs to be unnecessarily complicated.

Formatter class | constructor
--- | ---
**`Formatter`**    | **`initialize(opts = {})`**
**`HTML`**         | **`initialize(opts = {})`**
**`HTMLInline`**   | **`initialize(theme)`**
**`HTMLLegacy`**   | **`initialize(opts = {})`**
**`HTMLLinewise`** | **`initialize(formatter, opts = {})`**
**`HTMLPygments`** | **`initialize(formatter, css_class = 'codehilite')`**
**`HTMLTable`**    | **`initialize(formatter, opts = {})`**
**`Null`**         | **`initialize(*)`**
**`Terminal256`**  | **`initialize(theme = Themes::ThankfulEyes.new)`**
**`Tex`**          | **`initialize(opts = {})`**

In spite of inheriting from the same parent class, the arity of the various constructors differ, the expected type of the first argument differs (`Hash` / `Formatter` / `Theme` / `Array`)

## Possible solution

Since the constructors can't be normalized in Rouge 3.0, it'd be best to provide an **_adapter_** that accepts a `options` Hash to handle the various formatters internally so that a *`Converter`* at the receiving end doesn't have to know about the variations in the constructor design.

**Comment by ashmaroli** [comment]
/cc @pyrmont [Ping]
Any comment on what would be the best route to resolve this..?

**Comment by pyrmont** [comment]
@ashmaroli I realise this wasn't what you had in mind by tagging me but I've changed the label for this issue. I don't see any bug here; this looks like a suggestion on how to improve the Rouge codebase.

More substantively, I see some appeal in having a consistent approach to the API but I'm not sure I rank it particularly highly in terms of concerns. I've still got a stack of PRs to work through and a large number of outstanding bugs reported in existing lexers. I feel like fixing these is sort of always going to be top of mind.

The other concern I have is whether this is a case of the perfect being the enemy of the good. Would it be preferable if the initialisers were consistent? Yes, but they're not and unless we want to break a lot of existing code for what is mostly aesthetic benefit (as far as I can tell), we're going to have to do some clever hackery to allow methods to accept multiple potential arguments styles.

**Comment by ashmaroli** [comment]
> what is mostly aesthetic benefit

Actually, its more than that. For further context, you may refer to the discussion at https://github.com/gettalong/kramdown/issues/617

I agree that addressing issues with lexers take a higher priority over this. Just wanted your take on this and see if I could submit a pull request.
Thank you.

**Comment by pyrmont** [comment]
@ashmaroli At the risk of provoking a link to the XKCD comic about standards, is your adapter idea that there'd be a generic—almost abstract—formatter that consumers could call with an options hash that contained the type of formatter they wanted and some additional arguments and then that generic formatter would switch on the formatter type requested and make the appropriate call?

**Comment by ashmaroli** [comment]
Yes. My adapter idea is in theory similar to how `Rouge::Formatters::HTMLLegacy` works but consistently updated to suit new formatters added to Rouge core.

**Comment by pyrmont** [comment]
What do you think would be a good name for the adapter? `HTML` is already used; `HTMLGeneric`? `HTMLAdapter`?

**Comment by ashmaroli** [comment]
`HTMLAdapter` seems great. :+1: 
The intended purpose is instantly conveyed: `Rouge::Formatters::HTMLAdapter`

**Comment by jchester** [comment]
Just lending my voice: I have also bumped into gettalong/kramdown#617. It's unfortunate, I would prefer to use `HTMLLineTable` as well.
