### ISSUE TITLE
Powershell Error in 3.5.0

### ISSUE THREAD

**Issue by jpmarceau** [rouge-ruby/rouge#1221]
I used to be able to highlight powershell scripts but with the 3.5.0 update this afternoon, even very simple code samples now seem to fail. Example:

```powershell
# Convert any text file to ASCII
 
param( [string] $infile = $(throw "Please specify a filename.") )
 
$outfile = "$infile.ascii"
 
get-content -path $infile | out-file $outfile -encoding ascii
```

00:02:39.671  [31m  Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'collections/mydocument.md':[0m
00:02:39.671  [31m                    unknown state: :paren[0m
00:02:39.671  jekyll 3.7.0 | Error:  unknown state: :paren

Thank you :)

**Comment by pyrmont** [comment]
@jpmarceau Sorry about that. I'm pretty sure this is from a change to the Shell superclass. I think I know how to fix the PowerShell lexer to use the new states. I'll test and update.

**Comment by pyrmont** [comment]
@jpmarceau The problem was in #1216. The PowerShell lexer needed to be updated to use the new `:paren_interp` state. I've got a fix coming.

**Comment by jpmarceau** [comment]
@pyrmont thanks for the quick follow-up!

**Comment by pyrmont** [comment]
@jpmarceau v3.5.1 has now been pushed to RubyGems and should fix this. Sorry about the trouble!
