### ISSUE TITLE
Use Similarity tester to fail builds

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1230]
**Is your enhancement request related to a problem? Please describe.**
Sometimes lexers that are submitted are created by copying and pasting existing lexers. While this is not a bad way to begin development, a lexer should not be sufficiently differentiated from existing lexers. In #1206, @jneen added a mechanism to test the similarity of lexers.

**Describe the solution you'd like**
As part of Travis' build process, it would test the similarity of the lexer that was being added/modified to existing lexers.

**Comment by pyrmont** [comment]
@jneen Do you think this is a good idea? I've gone lukewarm on it now. I like that we can test Similarity but failing a build seems too extreme. I'm of a mind to close this issue. What do you think?

**Comment by jneen** [comment]
I think it should at least put a warning on the pull request - if there's a way to do this without failing the whole build then that'd be lovely.
