### ISSUE TITLE
Fix inconsistent use of template tag highlighting

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1237]
**Name of the lexer**
Handlebars, JSP, Smarty (possibly others).

**Online example**
N/A

**Code sample**
N/A

**Additional context**
The above-mentioned lexers are template lexers that do not use `Comment::Preproc` as the token for their template tags. This was identified by @miparnisari in [this comment](https://github.com/rouge-ruby/rouge/pull/838#discussion_r298787821).

**Comment by miparnisari** [comment]
Note that `Comment::Preproc` prints text in italics which might be undesirable. E.g. if you try to highlight `<&|` it will look like `<&/`

**Comment by pyrmont** [comment]
As noted in the discussion in the PR, the token doesn't impact the way the text appears, that's the stylesheet. Any token will have the problem you're describing if the CSS rule for that token causes it to display with italics.
