### ISSUE TITLE
Request for Cypher query language lexer

### ISSUE THREAD

**Issue by miromarchi** [rouge-ruby/rouge#1266]
**The name of the language**
*Cypher*

**Resources**
Cypher resources at the [openCypher initiative](http://www.opencypher.org/resources), including style guide, grammar specification, and others.
Cypher chapter in the [Neo4j developer manual](https://neo4j.com/docs/developer-manual/3.3/cypher/)

**Implementation in other libraries**
[Cypher for Pigment](http://pygments.org/docs/lexers/?highlight=cypher#pygments.lexers.graph.CypherLexer) class: `pygments.lexers.graph.CypherLexer`
I didn't find any implementation in Chroma nor in Highlight.js
[Cypher for Sublime Text 2](https://github.com/kollhof/sublime-cypher)
[Cypher for Atom](https://github.com/tobiashm/language-cypher) derived from Sublime
[Cypher for VSCode](https://github.com/jakeboone02/cypher-query-language) derived from Sublime and Atom
[Cypher for Codemirror](https://codemirror.net/mode/cypher/index.html)
[Cypher for Intellij](https://github.com/neueda/jetbrains-plugin-graph-database-support)

**Additional context**
There was already an issue #832 with 4 thumbs up as of today, but it was not recognized as a lexer-request
Given that [graph databases are now mainstream and given the openCypher initiative](https://www.information-age.com/growing-graph-database-space-2018-123470315/) (e.g. [cypher for spark](https://github.com/opencypher/morpheus)), it is likely cypher will increase its importance in the near future.

**Comment by pyrmont** [comment]
@miromarchi Thanks for taking the time to add an issue!

First, I want to set realistic expectations. Rouge is a library maintained by a group of volunteers. The vast majority of time spent by the maintainers is on fixing bugs and reviewing pull requests. It's unfortunately unlikely that the maintainers will create lexers based on requests :( Why have the issue template? We want to let members of the community see what lexers are in demand in case they want to contribute.

Speaking of which, the best way to get a lexer added to Rouge is to submit a PR with an implementation. I realise that can sound like a lot of work but most lexers consist of a collection of regular expressions that match the constructs in the particular language. We have [a guide](https://rouge-ruby.github.io/docs/file.LexerDevelopment.html) on how to develop a lexer that can give you more of an idea of how to start.
