### ISSUE TITLE
Julia lexer generates bad text output on `mutable struct`

### ISSUE THREAD

**Issue by iamed2** [rouge-ruby/rouge#1291]
**Name of the lexer**
julia

**Online example**
The site couldn't save the example so I took a screenshot (posted below).

**Code sample**
A sample of the code that produces the bug.

```
mutable struct Foo
end
```
produces
```
mutable structmutable Foo
end
```

**Screenshots**
https://www.dropbox.com/s/56uywbyaojq3vv3/Screenshot%202019-07-31%2015.16.15.png?dl=0

**Additional context**
This is basic Julia syntax that's been around since Julia 0.6 (support for that was explicitly added in PRs from earlier) but I don't think it's tested anywhere. Unfortunately I don't know Ruby or this package well enough to add tests on my own :(

**Comment by pyrmont** [comment]
@iamed2 Thanks for the report and sorry for the trouble >_< I'm pretty sure I see how this happened. It's a mistake in the regex pattern here:

https://github.com/rouge-ruby/rouge/blob/7836be9cd8757e8c300b058a3eb84bcd5b6000a0/lib/rouge/lexers/julia.rb#L201-L206

I'll look at putting a fix together we can roll out in the next version.

**Comment by pyrmont** [comment]
I've got a fix submitted. This will be merged into master and will come out in v3.8.0. That's due for release next Tuesday.

Sorry again for the trouble—I missed the bug when I did my original review! Will try to make sure that doesn't happen again!

**Comment by iamed2** [comment]
Wow, great, thanks! Amazing response time!
