### ISSUE TITLE
Rust unsafe keyword should be highlighted differently

### ISSUE THREAD

**Issue by gautammohan** [rouge-ruby/rouge#1299]
**Is your enhancement request related to a problem? Please describe.**

Unsafe blocks are uncommon and should be very loudly highlighted in Rust. Most Rust syntax highlighters make the `unsafe` keyword bright red, however it seems that Rouge groups it with other keywords.

**Describe the solution you'd like**

Is there a way to capture the "unsafe" keyword and highlight it differently?

**Additional context**

**Comment by pyrmont** [comment]
@gautammohan Can you provide some examples of the other syntax highlighters you're talking about? I'm curious how they're tokenising `unsafe`.

**Comment by gautammohan** [comment]
I use emacs normally, and `rust-mode` puts `unsafe` in a warning/error font face. I may have been overzealous in my statement of "most" syntax highlighters, as I just tried Vim and by default it did not differentiate between `unsafe`and other keywords as far as highlighting. Let me dial it back to say that Emacs does it, and I think it's a good idea (provided it doesn't take too much effort to implement)

**Comment by pyrmont** [comment]
Hmmm... the problem is that there's not really a token that would be appropriate for `unsafe` other than the `Keyword` token we're currently using. Rouge uses [the same tokens](http://pygments.org/docs/tokens/) as Pygments and that system isn't really designed to provide the kind of support for which you're looking.

What's the use case? Are you wanting to have the same kind of highlighting in a blog post?

**Comment by gautammohan** [comment]
Yep, highlighting in a blog post is precisely the use case. A potential workaround (for my case) would probably be to create a special tag and amend my css files.

I wasn't sure if it was an easy fix or not, but it looks like it might not be trivial. I'm not even sure if the Rust community agrees on a canonical syntax highlighting style. If it turns out that many of the tools treat `unsafe` differently, it might be worth considering. However I do not know for sure if this is the case.

**Comment by pyrmont** [comment]
I don't know how much control you have over the server but you might be interested in looking into the Escape lexer that was added in v3.4.0 of Rouge. If you have a formatter that has escaping enabled, you should be able to insert HTML into your source code that will be 'ignored' by Rouge and passed straight through to your blogging engine.

We need to document its use better and so you might prefer a different way of achieving your goal but if you're curious about this, PR #1152 (where it was added) is a good place to start. I hope that's helpful!
