### ISSUE TITLE
plaintext with linewrap

### ISSUE THREAD

**Issue by a-recknagel** [rouge-ruby/rouge#1302]
**Not an actual language**

**Additional context**
Issues like [this one](https://gitlab.com/gitlab-org/gitlab-ce/issues/25850) occasionally pop up for markdown rendering. My current usecase is pasting a token into an .md file. I can't add newlines by hand, since it will lead to errors when users copy-paste it. Adding the a `wrap` "lexer" (as is suggested in the linked issue) or a `wrap` modifier for any existing lexer would be nice.

**Comment by ashmaroli** [comment]
Technically speaking, this has nothing to do with lexing.

Rouge-3.6.0 has introduced a new table-formatter that allows soft linebreaks. But this render will have line-numbers next to it. You will have to use CSS to hide the line-numbers if you don't want them to be visible.

**Comment by pyrmont** [comment]
@a-recknagel I'm trying to approach this with an open mind but this really looks to me to be an issue for the consuming library to implement.

In the GitLab issues to which you link, the general proposal is for (1) the Markdown parser to recognise the word 'wrap' in a codeblock's language identifier; and (2) a CSS rule to apply `white-space: pre-wrap` to codeblocks that include the word 'wrap' in the relevant language identifier.

With respect to (1), the suggestion that this is something Rouge would handle seems to reflect a misunderstanding of where Rouge fits into the processing pipeline. While we lex text _within_ a Markdown codeblock, we don't look at (or even have access to) the language identifier in the Markdown. That is done by the library doing the Markdown parsing (or for the consuming library to override).

With respect to (2), this is really two things: a custom formatter that includes the CSS rule and some sort of logic to determine whether the CSS rule should be 'activated' (i.e. whether the word 'wrap' is present). While Rouge ships with a number of formatters, our position is that users who need custom behaviour should implement that in their own formatter. That, combined with the fact that the activation of the CSS rule depends on the language identifier which, as established above, is not information to which has access, points to the consuming library (e.g. GitLab) being the appropriate place for this support to be added.

Does that make sense?

**Comment by a-recknagel** [comment]
@pyrmont It does, and it's also not surprising that it's something that would be awkward to handle in rouge. I mainly wanted to make sure that it isn't, against expectations, a simple issue on your part. If you want you can close this, and in the future I can link this in all "maybe this can be fixed in rouge" discussions that I see. 

Also thanks for giving a thorough explanation instead of just saying "no" =)

**Comment by pyrmont** [comment]
@a-recknagel Not a problem! And that'd be most helpful if you could do that—thanks! :)
