### ISSUE TITLE
Regexp error in Terraform

### ISSUE THREAD

**Issue by sashee** [rouge-ruby/rouge#1304]
**Name of the lexer**
Terraform

**Online example**
Got an error when saving the paste

**Code sample**

```
resource "aws_cloudfront_distribution" "s3_distribution" {
  aliases = ["www.${replace(var.domain_name, "/\\.$/", "")}"]
}

```

**Screenshots**

![image](https://user-images.githubusercontent.com/82075/63080949-a5af8100-bf42-11e9-8742-61a3d9d8f2e7.png)

**Additional context**

The ```$``` in the regexp is reported as error, but it is valid.

**Comment by pyrmont** [comment]
@sashee Sorry about the fact it's not possible to save pastes. That's on my list of things to fix (should probably move it higher up).

**Comment by sashee** [comment]
No worries:) A screenshot is trivial to make

**Comment by pyrmont** [comment]
Oh, and it doesn't help with checking the way PRs lex things but we did eventually get [the dingus](https://rouge.jneen.net/) working again :)
