### ISSUE TITLE
NASM addressing lexing fails on most types of addresses

### ISSUE THREAD

**Issue by travisdowns** [rouge-ruby/rouge#1310]
**Name of the lexer**
nasm

**Online example**
I tried, but the "Save this" button seems broken, giving this error:

![image](https://user-images.githubusercontent.com/2403521/63397235-8c1d9780-c38f-11e9-85fc-d448df8b5952.png)

Here's a screenshot of the code:

![image](https://user-images.githubusercontent.com/2403521/63397309-bff8bd00-c38f-11e9-83de-b888ff82e674.png)

Note that all but the first addressing expressions produce lexer errors (the red brackets), but are valid (and very common) x86 addresses.

**Code sample**

```
mov eax, [eax]
mov eax, [eax + ebx]
mov eax, [eax + ebx*2]
mov eax, [eax + 10]
mov eax, [eax + ebx*2 + 10]
```

All but the first line produce an error.

**Additional context**

I would be happy to help, but I know zero Ruby and after opening the nasm lexer it didn't seem like something that I could fake my way though.

FWIW I don't think you need to very carefully parse the inside of the addressing expression: I think identifying registers, as they are identified outside `[]` would be fine, rather than trying to come up with exactly the allowed grammar in the addressing expression.

If you do want to capture exactly what is allowed it is something like:

`[ reg1 + reg2 * mult + offset ]`

Where all of `reg1`, `reg2`, `mult`, `offset` are optional (`mult` can only appear if `reg2` does). Order doesn't matter, and evidently you drop the `+` and `*` if the associated components are missing.

**Comment by pyrmont** [comment]
The 'problem' is that the rule to match expressions inside brackets only works for contiguous letters and numbers:

https://github.com/rouge-ruby/rouge/blob/8533fea3caff19a1506467fed6526e32cdf377fb/lib/rouge/lexers/nasm.rb#L167

The simplest thing to do might be just to match `[` and `]` independently rather than trying to match `[...]`.

**Comment by travisdowns** [comment]
@pyrmont - so that rule will match a whole `[...]` group and put it in the Punctuation category? We could also just match `[.*]`.

**Comment by pyrmont** [comment]
@travisdowns Yeah. But that seems obviously wrong to me. It shouldn't all be lexed as `Punctuation`. Forgive me for leaning on you a bit, but you could explain what exactly the following represents?

```nasm
mov eax, [eax]
mov eax, [eax + ebx]
mov eax, [eax + ebx*2]
mov eax, [eax + 10]
mov eax, [eax + ebx*2 + 10]
```

It looks to me from GitHub's highlighting that `mov` is a function but I'm a bit lost on the rest.

**Comment by travisdowns** [comment]
All of those are assembly instructions, in this case `mov` meaning "move the RHS to the LHS".

`eax` is the name of a CPU register. The `[ ... ]` expressions are addressing expresions, which means "read this from memory".

So `mov eax, [eax]` means "move 4 bytes from the memory pointed by `eax` (that's the `[eax]` part) into the CPU register `eax`. Basically it's a pointer-chasing step, like `ptr = *ptr` in C.

The other ones are all similar, except with more complex addressing. `[eax + ebx*2 + 10]` means calculate that expression and use it as the address.

The main thing to get right would be for register names to be parsed correctly, but based on my tests `mov eax, eax` is displayed the same as `mov foo, bar` (`eax` is a real register name, `foo` and `bar` are not).

**Comment by pyrmont** [comment]
@travisdowns Thanks, that's very helpful. Are the names of the registers fixed? Or do they follow a pattern? Or is it all ad hoc?

**Comment by travisdowns** [comment]
They are fixed. They "kind of" follow a pattern. Here's a list:

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/x64-architecture

You can kind of see there are several patterns there, for example a regex like `(r|e)?[abcd]x` would capture the top left quadrant, but it might be simplest to just list them all?

**Comment by travisdowns** [comment]
A regex for the bottom part of the list would be like `r(8|9|(1[012345]))[dwb]?`.

**Comment by pyrmont** [comment]
@travisdowns We try to avoid defining too many reserved words as each one requires memory to be allocated but it doesn't look like there are all that many so listing them all might be the best idea.

**Comment by travisdowns** [comment]
@pyrmont - makes sense. Are you asking about register names because you want to highlight them specially?

I am happy to answer any questions about x86 nasm syntax, please don't hesitate to ask.

**Comment by travisdowns** [comment]
@pyrmont - I've run into enough other limitations (e.g., many instructions are missing) that I'm willing to learn a bit of ruby to work on this.

Is there a standard way to test the syntax highters, e.g., so I can try my changes on a bunch of representative asm quickly?

**Comment by pyrmont** [comment]
Argh! Sorry, @travisdowns! I somehow forgot we halfway through discussing this. I'm out at the moment but will get back to you on this ASAP (the short answer is 'not really'; you can copy and paste the code into the visual sample in `spec/visual/sample` and inspect it that way but it's not great).

**Comment by travisdowns** [comment]
@pyrmont - I mean I guess a simple way would just be to run Jekyll against a markdown file with various samples and inspect the output. It doesn't have to be _super_ fast iteration, I just don't want to spend hours setting up the basics :).

**Comment by pyrmont** [comment]
@travisdowns That's definitely one way. I think the simplest, though, is to add what you want to test to the visual sample. You can see how I did that in #1428.

I should note that Rouge is architected such that you don't need to stop the Rack server to see changes to your Ruby code when looking at visual samples. If you save an update you've made to the relevant lexer's code, refreshing the page showing the sample will show the result of the updates.
