### ISSUE TITLE
"Save this" button fails on http://rouge.jneen.net 

### ISSUE THREAD

**Issue by travisdowns** [rouge-ruby/rouge#1311]
_Please note: This is for non-lexer bugs._

**Describe the bug**

"Save this" button fails on [rouge.jneen.net](rouge.jneen.net), at least for nasm language.

**To Reproduce**

1. Go to [rouge.jneen.net](rouge.jneen.net)
2. Enter some nasm like `add eax, eax` or just leave the box empty, in the "Try some code" field. Like this:

![image](https://user-images.githubusercontent.com/2403521/63397593-a9069a80-c390-11e9-8402-1c0564e261d6.png)

3. Click "Save this"

4. See this error:

![image](https://user-images.githubusercontent.com/2403521/63397692-0d295e80-c391-11e9-94bc-85fc6f197d7a.png)

URL shown is http://rouge.jneen.net/pastes

Same behavior on Chrome and Firefox.

**Expected behavior**
No error.

**Screenshots**
As above.

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - Ruby version: N/A problem with web app
 - Rouge version: unknown

**Additional context**
Not sure if this is the right category to report bugs with the online service but I didn't see an obviously better one.

**Comment by pyrmont** [comment]
@travisdowns Thanks for the bug report. We've exceeded our current capacity on Heroku which is why you see the error. I have it on my list of things to fix >_<

**Comment by travisdowns** [comment]
Thanks @pyrmont - oddly I didn't see the error when I tried it with another language (XML which was just randomly selected for me), but I guess it may be an on-or-off problem.

**Comment by pyrmont** [comment]
@travisdowns Hmmm... not sure why that would have happened. It should occur for any language.

**Comment by travisdowns** [comment]
@pyrmont - I tried it again and it failed this time. Maybe the XML examples was already saved so was cached somewhere, dunno.

**Comment by pyrmont** [comment]
@travisdowns Yeah, that could be it!

**Comment by pyrmont** [comment]
@travisdowns [The new dingus](https://github.com/rouge-ruby/dingus) no longer has this problem. Thanks for the report!

**Comment by travisdowns** [comment]
Thanks @pyrmont - the "new dingus" (is that a technical term?) looks great!

**Comment by pyrmont** [comment]
I took it from the Markdown world but don't think it's a technical term—just a makeshift solution for something that doesn't have a great name :)
