### ISSUE TITLE
Unicode highlight in Coq (or other lang)

### ISSUE THREAD

**Issue by Huxpro** [rouge-ruby/rouge#1312]
<img width="1228" alt="Screen Shot 2019-08-22 at 3 37 38 PM" src="https://user-images.githubusercontent.com/5563315/63554635-00248080-c4f3-11e9-84d0-609c5969e2cb.png">

This issue is similar to #621 or #831 where the Unicodes are highlighted with a bold concrete background (I guess it's an error?). 
It looks like #621 is fixed by manually accepting more alphabet symbols.
Could there be a unified fix for deemphasizing the lex errors on Unicode?

Noted that using Unicode here in Coq is actually syntactically invalid but yet a common way in writing (say the Software Foundation books). Trying to highlight Agda code (where Unicode is universally used) with Haskell will encounter a similar issue.

**Comment by pyrmont** [comment]
@Huxpro Yeah, a way to deemphasise errors is an interesting idea. The difficulty is how to do that? The simplest way I can think of would be to insert an additional class into the generated HTML that users could then use to affect the styling. 

Oh, and could you copy and paste the example text you tried to lex? Sorry the dingus isn't accepting new saves at the moment :(

**Comment by Huxpro** [comment]
Thx @pyrmont. I guess brutely highlight ".highlight .err" as whatever in user-land could workaround but I agreed how to do it elegantly is tricky.

here is the code:

```Coq
Theorem ev_plus4 : ∀n, even n → even (4 + n).
Proof.
  intros n H. simpl.
  apply ev_SS.
  apply ev_SS.
  apply H.
Qed.
```

**Comment by pyrmont** [comment]
@Huxpro I would also like to have a fix for the Coq lexer that allows the types of characters commonly used in the community.

The difficulty I'm having is finding a regular expression that doesn't match symbols that are used as punctuation or as operators (there are alternatives to this approach but this is my preferred solution). [The ∀ character](https://www.compart.com/en/unicode/U+2200), for example, is part of the 'Math Symbol' general category but so is [the + character](https://www.compart.com/en/unicode/U+002B).

Are there a common set of additional characters used that we want to (effectively) whitelist? Or do people use any old Unicode character they feel like?

**Comment by jneen** [comment]
you can actually put those characters literally in a regex, if they're common enough we may want to add them to haskell/coq.

**Comment by pyrmont** [comment]
@jneen Yeah, that's kind of where my mind was going too :)

**Comment by Huxpro** [comment]
@pyrmont Coq has some meta-programming power so it might be tricky to cover all cases... essentially, math symbols commonly used in logic and set theory are most used and might be sufficient:

A tentative list could be
- def/implications `⇒` `→` `↔` `⇔` `≔` `≡`
- quantification `∀``∃`
- logical connectives `/\` `\/` `∧` `∨` `¬`
- top/bottom `⊤` `⊥`
- proof/entail `⊢` `⊨`
- set `∈`...

A code example could be:

```coq
Theorem progress : ∀t T,
  empty ⊢ t ∈ T →
  value t ∨ ∃t', t --> t'.
```

**Comment by tomtomjhj** [comment]
Some coq projects make heavy use of unicode indentifiers and notations and their highlighting is severely broken on gitlab. Example: https://gitlab.mpi-sws.org/iris/iris/-/blob/master/iris_heap_lang/adequacy.v
![image](https://user-images.githubusercontent.com/19489738/103544531-96d4c000-4ee3-11eb-868b-a0b3daee9906.png)

Github's highlighter seems to ignore everything it doesn't recognize, and I think that is much more readable in general.
![image](https://user-images.githubusercontent.com/19489738/103544916-22e6e780-4ee4-11eb-8e56-8a3f374a940b.png)

**Comment by pyrmont** [comment]
@tomtomjhj I'm no longer maintaining Rouge but have reopened the issue.
