### ISSUE TITLE
Rationalise regular expressions in Kotlin lexer

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1324]
**Name of the lexer**
Kotlin

**Code sample**
https://github.com/rouge-ruby/rouge/blob/7b876784f61444da6d3a9a8ada0a2ace8b13621a/lib/rouge/lexers/kotlin.rb#L27-L30

**Additional context**
Does `id` have any purpose? It's used throughout the lexer rather than `name` but as best as I can tell is just `name` inside a capture group. The capture group is never used, which seems wasteful.

Directing this at you, @lordcodes, because I'm not familiar with Kotlin and so am not sure if there would be a reason to have done things this particular way.

**Comment by lordcodes** [comment]
No, I had exactly the same thought when making changes to the Kotlin lexer. `name_backtick` can be used instead.

**Comment by pyrmont** [comment]
Perhaps this is going overboard but is it worth simply putting the backticks into the `name` regex as optional matches? It's a non-goal of Rouge to check syntax and so the fact this would allow: (1) backticks in places they shouldn't be; and (2) 'unbalanced' backticks, doesn't seem problematic to me. But what do you think? Perhaps overrationalising things?

**Comment by lordcodes** [comment]
Can be done, I am assume name and name_backtick were kept separate to make the regexes easier to read.
I will have a look in more detail soon.

**Comment by pyrmont** [comment]
Yeah, if they were combined it's probably a good idea to include a code comment explaining that backticks are being included but will result in some technically false positives.
