### ISSUE TITLE
Swift: Passing Lambdas to Functions

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1328]
**Name of the lexer**
Swift

**Code sample**
A sample of the code that produces the bug.

```
funcWithLambdaArg { x in x + 5 }
funcWithLambdaArg { $0 + 5 }
funcWithLambdaArg({ x in x + 5 })
```

**Screenshots**
![3ABBA849-5CAA-404C-8332-CC691977D754](https://user-images.githubusercontent.com/41152/64605033-396b5480-d3fe-11e9-9717-8e59474de096.jpeg)

**Additional context**
It may not be possible to tokenise the identifier `funcWithLambdaArg` when a lambda is the only argument because of other possibilities (I'm not familiar enough with Swift to know whether this is the case or not).

What do you think @johnfairh / @lordcodes?

**Comment by lordcodes** [comment]
I have thought about this one for the Kotlin lexer too. However, I do think funcWithLambdaArg should be able to be highlighted in first 2 cases. I believe this issue applies to the Kotlin lexer as well.
