### ISSUE TITLE
Add TTCN-3 testing language lexer

### ISSUE THREAD

**Issue by YannGarcia** [rouge-ruby/rouge#1336]
**The name of the language**
TTCN-3 testing language is standardized by ETSI. Latest TTCN-3 core language standard can be found [here](https://www.etsi.org/deliver/etsi_es/201800_201899/20187301/04.11.01_60/es_20187301v041101p.pdf). 
This language is used to develop conformance and interoperability test suites for variety of protocols such as Intelligent Transport System protocols, Telco's protocols... All these test suite are available on the [ESTI forge](https://forge.etsi.org/).

**Implementation**
The TTCN-3 testing language lexer includes 3 files (to be merged)
![CaptureRackupTtcn3](https://user-images.githubusercontent.com/5013253/65937332-e0507880-e41f-11e9-8c76-a0cdc6c4b148.JPG)
:
1) [rouge/spec/lexers/ttcn3_spec.rb](https://github.com/YannGarcia/rouge/blob/master/spec/lexers/ttcn3_spec.rb)
2) [rouge/lib/rouge/lexers/ttcn3.rb](https://github.com/YannGarcia/rouge/blob/master/lib/rouge/lexers/ttcn3.rb)
3) [rouge/lib/rouge/demos/ttcn3](https://github.com/YannGarcia/rouge/blob/master/lib/rouge/demos/ttcn3)

**TTCN-3 lexer validation**
This lexer was validated using rackup/ruby2.5 (see attached screenshopt).

Thanks to add this contribution to Rouge syntax highlighter.

Best regards,

Yann Garcia
Senior Software EngineerMicrosoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6,  Avenue des Alpes 
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08
Mobile: +33 (0)6 68 94 57 76
Email: yann.garcia@fscom.frSkype: yann.garcia

**Comment by pyrmont** [comment]
@YannGarcia Can you submit this as a pull request? Instructions on how to do that are [here](https://help.github.com/en/articles/creating-a-pull-request).

**Comment by YannGarcia** [comment]
Unfortunately not, permission issues :(
Yann
Best regards,

Yann Garcia
Senior Software Engineer
Microsoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6,
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
  Avenue des Alpes
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08
Mobile: +33 (0)6 68 94 57 76
Email: *yann.garcia@fscom.fr <yann.garcia@fscom.fr>*
Skype: yann.garcia

**Comment by pyrmont** [comment]
I'm not sure what you mean. We don't have any settings enabled that would prevent a PR.

**Comment by YannGarcia** [comment]
I follow the procedure, but when I tried to push my branch, my Github
authentication was rejected.
Yann
Best regards,

Yann Garcia
Senior Software Engineer
Microsoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6,
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
  Avenue des Alpes
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08
Mobile: +33 (0)6 68 94 57 76
Email: *yann.garcia@fscom.fr <yann.garcia@fscom.fr>*
Skype: yann.garcia

**Comment by pyrmont** [comment]
A pull request is different to a push to the main repository. If you want to do that from the command line, you need to download GitHub's [hub tool](https://hub.github.com/). However, you can submit the PR using the GitHub website if you prefer. The instructions are in the previous link.

**Comment by YannGarcia** [comment]
Oups, my apologies for my misunderstanding,
it's done
Thanks a lot,
Best regards,
Yann

**Comment by pyrmont** [comment]
No worries :)
