### ISSUE TITLE
Interpolate pieces of highlighted code with specific html tags

### ISSUE THREAD

**Issue by brodock** [rouge-ruby/rouge#135]
I would like to ask if it's possible in any feasible way to preserve specific "html" tags inside the original code.

What I want to do is to "annotate" source-code with specific tags, to be used on slides. As an example, I would like to use "< mark >def x< /mark >" to be able to style background around the generated "def x" highlighted part:

``` ruby
class A
  def x
  end
end
```

I know that something similar to that is possible with highlightjs (you have to use span), so I'm asking if it's on the scope of rouge to support it (probably as a advanced hack or a optional flag).

This can also be useful to the folks highlighting pieces of code on blog posts.

**Comment by pyrmont** [comment]
@brodock It took five years but @jneen did add [something that lets you do this](https://github.com/rouge-ruby/rouge/pull/1152) :D

**Comment by brodock** [comment]
awesome ❤️
