### ISSUE TITLE
Rouge Support for Assembly

### ISSUE THREAD

**Issue by Merikanto** [rouge-ruby/rouge#1352]
Hello,

Does Rouge support syntax highlight for assembly in markdown texts?

I tried the keywords "asm", "x86asm", "armasm", and none of them works.

Thanks!

**Comment by pyrmont** [comment]
@Merikanto You can see all of the lexers available in [the `lexers` directory](https://github.com/rouge-ruby/rouge/tree/master/lib/rouge/lexers). Rouge has an ArmAsm lexer and a Nasm lexer that might be what you're looking for. You can also see these in [the online dingus](http://rouge.jneen.net/).

Do you know what version of Rouge you're running? If you're running an older version, you might not have these lexers.

**Comment by Merikanto** [comment]
I'll give it try, thanks!
