### ISSUE TITLE
PHP multiple use statements combined not highlighted properly

### ISSUE THREAD

**Issue by HypeMC** [rouge-ruby/rouge#1353]
**Name of the lexer**
PHP

**Code sample**

```php
use Class1, Class2, Class3;
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2445045/68084511-dd89de80-fe36-11e9-92fa-5894b05fa2b7.png)

**Comment by pyrmont** [comment]
@HypeMC Thanks for the report! This sounds pretty straightforward to fix. I'll have a look at the PHP lexer and see what's breaking :)
