### ISSUE TITLE
Support for BibTeX

### ISSUE THREAD

**Issue by ph03** [rouge-ruby/rouge#1357]
**BibTeX**
Syntax format description: http://www.bibtex.org/Format

**Implementation in other libraries**
Pygments implementation: https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/bibtex.py

**Comment by pyrmont** [comment]
Thanks for filing the issue, @ph03!

Rouge relies on the support of our community for new language lexers. We always encourage new language lexer submissions to be submitted via PR. If you'd like to contribute, please feel free. [This guide](https://rouge-ruby.github.io/docs/file.LexerDevelopment.html) is a good place to start :)
