### ISSUE TITLE
PHP traits not always highlighted properly

### ISSUE THREAD

**Issue by HypeMC** [rouge-ruby/rouge#1361]
**Name of the lexer**
PHP

**Code sample**

```php
class ClassA
{
    use TraitA {
        foo as private bar;
    }
}

class ClassB
{
    use TraitA, TraitB {
        TraitB::foo insteadof TraitA;
    }
}


class ClassC
{
    use TraitA, TraitB {
        TraitB::foo as bar;
    }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2445045/68905146-7cb8ab00-0740-11ea-9f41-680f7d2ce2cd.png)

**Comment by pyrmont** [comment]
@HypeMC That definitely doesn't look right, does it? I'll have a look at the lexer and see where it's going wrong.
