### ISSUE TITLE
PHP alternative syntax not always highlighted properly

### ISSUE THREAD

**Issue by HypeMC** [rouge-ruby/rouge#1362]
**Name of the lexer**
PHP

**Code sample**
```php
<?php if (true): ?><!-- Notice the space between the colon & question mark -->
    <p>This is OK.</p>
<?php endif ?>

<?php if (true) :?><!-- No space -->
    <p>This is wrong</p>
<?php endif ?>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2445045/68905630-26e50280-0742-11ea-9d64-de66290b3ce8.png)

**Additional context**
The bug occurs when there's no space between the colon & the closing php tag, eg `:?>`.

**Comment by pyrmont** [comment]
@HypeMC It's a non-goal of Rouge to check syntax. Lexers do sometimes report errors but  but it's not a require

**Comment by HypeMC** [comment]
@pyrmont Hi, tnx for your response, but I'm not sure I understood you. Just to be clear, this is valid PHP syntax that works, it's only highlighted incorrectly.

**Comment by pyrmont** [comment]
Argh, sorry—I misunderstood the bug!

**Comment by HypeMC** [comment]
@pyrmont Np, I probably could've explained it better tbh, tnx.

**Comment by julp** [comment]
I think I understand why: `:?>`, by `rule %r/[~!%^&*+=\|:.<>\/?@-]+/, Operator` is probably seen as a single Operator token when it should be seen as two tokens `:` then `?>` with `?>` exiting (pop!) current PHP lexer as expected.
