### ISSUE TITLE
Please document usage of console options (e.g. ?prompt, ?root, etc.)

### ISSUE THREAD

**Issue by dleidert** [rouge-ruby/rouge#1370]
I'm trying to make use of the console lexxer option as described at <https://github.com/rouge-ruby/rouge/blob/master/CHANGELOG.md> and <https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers>. But whatever I do, I don't see any difference and I even don't have any clue, when and what they would alter. I presume, that the usage is

> \`\`\`console?option=value
> 
> \`\`\` 

But it doesn't change anything, e.g. both the following examples lead to the same result.

> \`\`\`console?root=1
> \# foobar
> \`\`\` 

> \`\`\`console?comments=1
> \# foobar
> \`\`\` 

altough they have different meanings. Please document the options and the correct usage.

**Comment by pyrmont** [comment]
@dleidert Sorry for the confusion. There's a couple of things happening here and the documentation isn't clear.

The short answer is that the parsing of options associated with Markdown code blocks is something that's handled by your Markdown parser and, as far as I'm aware, there are no Markdown parsers that support what you're looking for. I'm afraid that means there's not much you can do. 

The longer answer is that Rouge is a syntax highlighting library that provides an API for other tools (typically, parsers). The basic process is:

1. the tool will send text to Rouge together with some configuration options;
2. Rouge will highlight the text using the lexer that's either specified or detected (as adjusted by any of the options that were passed to it); and
3. Rouge will return the highlighted text to the tool.

As is perhaps evident from the above, it's not really a library for end users to use. Rather our consumers are tool makers (like Markdown parsers) who want a library that will highlight code for _their_ users. It is possible for a tool to collect configuration options from end users (perhaps using the syntax you were trying) and then pass those options to Rouge. Unfortunately, I'm not aware of any Markdown parsers that do that.

If you're using something like Jekyll or GitLab, you can look at adding that kind of functionality to those projects (but it may not be something that the project maintainers would accept as it would be an extension to the Markdown syntax).

Does that explanation help at all? Let me know if I can provide more details.

**Comment by johnfairh** [comment]
Rouge is designed to accept language requests with options, coming in to the `Lexer.find_fancy()` method - see doc comments there.  The Redcarpet plugin, which I suppose is the reference implementation for markdown engines to invoke Rouge, uses this to pass through options from the user without the markdown layer knowing about them.

The brief docs for the console lexer are available in the source code or `rougify list`.

That said, I couldn't make the console lexer do anything with the 'comments' option except confirm it was set correctly in the lexer -- it's pretty different to the lexers I'm used to reading!

**Comment by jneen** [comment]
@pyrmont i think @johnfairh is correct here, and while we do have documentation for those options (...right?) this appears to be a bug.

**Comment by jneen** [comment]
these are the options for the console lexer (available in `rougify list`):

``` ruby
      option :lang, 'the shell language to lex (default: shell)'
      option :output, 'the output language (default: plaintext?token=Generic.Output)'
      option :prompt, 'comma-separated list of strings that indicate the end of a prompt. (default: $,#,>,;)'
      option :comments, 'enable hash-comments at the start of a line - otherwise interpreted as a prompt. (default: false, implied by ?prompt not containing `#`)'
```

**Comment by jneen** [comment]
I think the issue is that there is no `root=...` option. But you should be able to pass `prompt=#`.

**Comment by dleidert** [comment]
> The short answer is that the parsing of options associated with Markdown code blocks is something that's handled by your Markdown parser and, as far as I'm aware, there are no Markdown parsers that support what you're looking for. I'm afraid that means there's not much you can do.

When I read #636 I got the impression, that these options can be passed somehow (and are expected to be used in Markdown). How or where would you pass `?comments=1` for example?

> 1. the tool will send text to Rouge together with some configuration options;
> 2. Rouge will highlight the text using the lexer that's either specified or detected (as adjusted by any of the options that were passed to it); and
> 3. Rouge will return the highlighted text to the tool.
> [..]
> Unfortunately, I'm not aware of any Markdown parsers that do that.

I did wonder why `\`\`\`shell?comments=1` and `\`\`\`shell` both produce the same results, whereas `\`\`\`shells` is unrecorgnized. In case of ruby-kramdown (which is used by Jekyll) I cannot even find any string comparison or a reference to e.g. the word `shell` in its code. So it seems to me the markdown parser does not evaluate the codeblock type here.

The magic in the kramdown parser happens in [rouge.rb](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter/rouge.rb), I suppose. There is a call to `Lexer.find_fancy()`. Judging from rouge's source code, a string like e.g. `shell?root=1` is fine and it seems to be parsed in `find_fance()` too. And if I read the source right (I'm not a Ruby programmer), the additional options passed with the CGI like string are examined and passed to the returned object.

But in reality this does not seem to work. As I'm not a Ruby programmer, can you please take a look at it?

**Comment by jneen** [comment]
Yes, you should be able to pass options like that. You can use `rougify list` to see which ones are available, and some documentation about them. In this case, `?root=true` is not a valid option, so it is being ignored.

**Comment by jneen** [comment]
@pyrmont for future reference, our markdown does do recursive lexing, here: https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/lexers/markdown.rb#L39

**Comment by jneen** [comment]
Oh! I should also say, the `shell` lexer is for shell scripts. If you want a console session, you should use the `console` lexer. `console?prompt=#` is a lot more likely to give you what you want.

**Comment by dleidert** [comment]
Ok. I've tested via command line and also created a Jekyll test post. Seems `?prompt=...` is working. But `?comments=...` seems dysfunctional. Independent of its value a `#` always seems to be interpreted as prompt. The value I assign to `?lang=` also doesn't seem to make any difference. Is it possible to create some test cases for the console lexer to check if the options are working?

**Comment by pyrmont** [comment]
@dleidert Good thing @johnfairh and @jneen were paying attention otherwise I would have led you astray! I've learnt something too! I'll try to have a play around over the weekend with the tests for the appropriate lexer and see how it goes.

@jneen Yeah, I should have checked the behaviour of the Markdown plugins more closely. I knew the options were something that could be passed to Rouge; I just had no idea that Markdown plugins were doing that. It makes sense now that they'd just get the tag at the end of the ` ``` ` and leave Rouge to work out how to pull any options out of it. Good to know!

@johnfairh Thanks for responding! Always good to have more eyes :)

**Comment by pyrmont** [comment]
@dleidert Just wanted to give an update (somewhat unsatisfyingly) that I am exploring things but haven't got a fix yet. I've replicated the behaviour you described and am looking at adding a spec that will fail when the options aren't producing the right results.
