### ISSUE TITLE
LLVM lexer does not handle addrspace or addrspacecast

### ISSUE THREAD

**Issue by jholewinski** [rouge-ruby/rouge#1372]
**Name of the lexer**
LLVM

**Code sample**

```
%1 = addrspacecast i32* %a to i32 addrspace(1)*
```

**Screenshots**
<img width="427" alt="Screen Shot 2019-12-09 at 11 30 24 PM" src="https://user-images.githubusercontent.com/246931/70495626-21c66980-1adc-11ea-975e-c52149b54105.png">

**Additional context**

**Comment by pyrmont** [comment]
Thanks for the report, @jholewinski. I haven't had a chance to look yet at the LLVM lexer but merely from the error, it looks like it should be a simple fix. I should be able to make that soon :)
