### ISSUE TITLE
CGI-style parameter set to false isn't recognised as false

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1380]
**Describe the bug**
When passing an option to a lexer as a CGI-style parameter, `parameter=false` does not result in parameter being set to `false`.

**To Reproduce**
1. Specify the language string to a GFM code block as `console?comments=false`
2. The resulting `ConsoleLexer` will have the option for comments enabled.

**Expected behavior**
The parameter value will be `false`.

**System**
 - Ruby 2.6.5
 - Rouge 3.14.0

**Additional context**
As discussed by @dleidert in #1379.

**Comment by jneen** [comment]
lexer.rb, line 321 should do it :]

**Comment by pyrmont** [comment]
Aww yiss :)

Thanks @jneen!
