### ISSUE TITLE
First segment of Java package namespace is not highlighted

### ISSUE THREAD

**Issue by mojavelinux** [rouge-ruby/rouge#1388]
**Lexer**: Java

**Sample code:**

```java
package com.example;

public class HelloWorldApp {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```

**Screenshot:**

![java-lexer-bug](https://user-images.githubusercontent.com/79351/72320624-525f6d00-365f-11ea-87a8-5b1fad57c59d.png)

**Additional details:**

It doesn't matter what the first segment of the package namespace is named (e.g., com, org, io, etc), or how many segments are in the namespace, the first segment isn't highlighted using the same color as the remaining segments.

I would expect all the segments in the namespace to be highlighted in the same color (as is the case for import statements).

**Comment by pyrmont** [comment]
@mojavelinux Definitely looks broken. Will take a look.
