### ISSUE TITLE
Defining local custom lexers

### ISSUE THREAD

**Issue by evanw555** [rouge-ruby/rouge#1392]
**Is your enhancement request related to a problem? Please describe.**
No particular problem.

**Describe the solution you'd like**
I'd like to be able to define my own custom lexer locally to be used by my specific use case.

**Additional context**
My online documentation contains code snippets in a custom homemade language. I'm not sure if it's appropriate or worth the effort to get it reviewed by your team and to make it natively supported in Rouge. Do you think if I can define a lexer, I should just get it reviewed and merged? Or would it make more sense to support custom local lexers?

**Comment by jneen** [comment]
Rouge is specifically engineered to allow this! I do it all the time when giving presentations about language design - talking about languages that don't and probably won't ever exist. All you've got to do is:

``` ruby
class MyLanguage < Rouge::RegexLexer
  tag 'my-language'
  aliases '...'
  state :thing do
    ...
  end
end
```

**Comment by jneen** [comment]
The `tag` and `aliases` invocations will register your lexer with the rouge language resolver. However - this isn't even necessary. If you want it to be *entirely* isolated from Rouge's global state, just leave those out, and do `MyLexer.new(opts).lex(string)`. This will return a token stream that you can pass to any instance of `Rouge::Formatter` through the `.format(stream)` method.

**Comment by evanw555** [comment]
Thanks so much, this is exactly what I was looking for. So after you responded, I went ahead and developed my lexer and wired it into my Jekyll build process. You can see the lexer here: https://github.com/linkedin/rest.li/blob/gh-pages/_plugins/pdl_highlighter.rb

The lexer is meant to be used with the open-source schema definition format used at LinkedIn called PDL. You can see our documentation on the language here: https://linkedin.github.io/rest.li/pdl_syntax

Everything was running smoothly when I was testing it locally, however I only realized today that GitHub pages doesn't support custom plugins. As you can see in the link, none of the snippets are highlighted. This is a major bummer for me, as I spent a decent amount of time developing this last night. My only two options right now are to (1) submit this as an officially supported language in Rouge since the Rouge highlighter is whitelisted by GitHub pages, or (2) do some hacky solution where I build my site locally and commit the rendered HTML (yuck).

So my question for you is: what's your standard for an acceptable language to be supported natively in Rouge? Our schema definition language is open-source so it seems like it would be appropriate, however it's not widely used. What do you think?

**Comment by jneen** [comment]
I'm glad it worked locally at least!

While I think there are broader discussions to be had about when a language is "mainstream" enough to be included in Rouge core, I think I would highly recommend pushing HTML directly to github pages. Even if we were to merge that lexer today, we have found it very difficult to get github to run an up-to-date version of rouge, so I suspect it would take quite a while. I have had success using a `github-pages` branch and a small script to switch to that branch and copy stuff from `build/` - it should support HTML files in a reasonable way. I use middleman in place of jekyll anyways, so it's not as far out of the way to do that kind of thing.

**Comment by pyrmont** [comment]
I should add GitHub has greatly improved things of late. They were stuck forever with a version 2 release but did eventually upgrade it to 3.11.0 and then in December bumped it again and are [now on 3.13.0](https://pages.github.com/versions/).

**Comment by jneen** [comment]
That's really good news! (though I still think it's less of a headache to just push HTML, then you get to control your own versions of things)

**Comment by pyrmont** [comment]
@evanw555 Can this be closed?

**Comment by evanw555** [comment]
@pyrmont Sorry for the delay here. Yes, this can be closed. Thanks for helping me to figure out how to set this up and pointing me in the right direction.

**Comment by Simran-B** [comment]
FWIW, LinkedIn's lexer now appears to live here: https://github.com/linkedin/rest.li/blob/gh-pages-source/src/_plugins/pdl_highlighter.rb
