### ISSUE TITLE
PowerShell lexer treats lines after variable expansion wrong

### ISSUE THREAD

**Issue by flipcc** [rouge-ruby/rouge#1407]
**PowerShell lexer**
The following shows a bug that was discovered after commiting a PowerShell script and reviewing it within GitLab's web interface.

**Code sample**
```powershell
# Highlighting ok
$gitUserName = "$($userAdObject.Properties['sn']), $($userAdObject.Properties['givenName'])"

# Highlighting false
$gitExeString = "$gitExeFolder\git.exe"
&("$gitExeString") config --add --global user.name `"$gitUserName`"
```

**Screenshots**
![powershell_lexer_bug](https://user-images.githubusercontent.com/16879827/73073007-ad426100-3eb6-11ea-868e-690c03b486d8.png)

As you can see, that bug behavior is similar to forgetting to close a String.

**Additional context**
We are employing GitLab (GitLab Community Edition 12.7.0) at our enterprise, which makes use of your wonderful project.

**Comment by pyrmont** [comment]
@flipcc I think the problem is here (specifically line 104):

https://github.com/rouge-ruby/rouge/blob/09c2b8b467d7355126006668b12aaec4f8f31629/lib/rouge/lexers/powershell.rb#L101-L110

Have to have a think about how to fix this.
