### ISSUE TITLE
rougify prints \e instead of corresponding character

### ISSUE THREAD

**Issue by shoorick** [rouge-ruby/rouge#1410]
`rougify` prints wrong ANSI sequences: literally `\e` intead of special character `^[` (`0x1b`): all lines except first one begin with `\e[38;5;230m` and end with `\e[39m`

May be these sequences are unnecessary because colors are shown as expected.

**To Reproduce**

1. Open terminal
2. Execute `path/to/rougify some-file.ext`

**Expected behavior**

Expected output must not contain unnecessary characters.

**Screenshot**
![wrong-ansi-sequences](https://user-images.githubusercontent.com/190892/73105879-e5c85600-3f1b-11ea-84ca-a66a31438773.png)

**System:**

 - OS: Debian 10 Buster, GNOME Terminal 3.30.2
 - Ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
 - Rouge 3.15.0

**Comment by pyrmont** [comment]
@shoorick I think this was fixed by #1402 and #1404. Could you test against the current master?

**Comment by shoorick** [comment]
I've tested again — it works, thank you.

![rouge-no-error](https://user-images.githubusercontent.com/190892/73112006-760f9680-3f2e-11ea-9e49-e3aa656013cc.png)

**Comment by pyrmont** [comment]
@shoorick Great! All credit to @jneen; she came across this just before you did it would appear :D 

We push out new versions of Rouge on a monthly cadence at the moment. The version with this fix (v3.16.0) is scheduled to go out on Tuesday 11 February.

**Comment by shoorick** [comment]
@pyrmont Fine! I’m glad that Rouge is live and goes on.
I've made [pull request for Gettext lexer](https://github.com/rouge-ruby/rouge/pull/1405) and right now I'm working on [LilyPond lexer](https://github.com/shoorick/rouge/tree/lilypond) (its syntax is more complicated than Gettext). I hope I’ll finish this work shortly.
![rouge-lilypond-with-errors](https://user-images.githubusercontent.com/190892/73112607-018a2700-3f31-11ea-93a6-7923cbb9a152.png)

**Comment by pyrmont** [comment]
@shoorick Yep, I've got that PR on my radar. Will try to get to it soon!
