### ISSUE TITLE
TypeScript: Issue with optional chaining inside templated string

### ISSUE THREAD

**Issue by codebutler** [rouge-ruby/rouge#1420]
**Name of the lexer**
TypeScript

**Code sample**

```ts

// This is fine:
const x = `Hello world ${a.b}`;

// This breaks:
const y = `Hello world ${a?.b}`;

// Now Rouge thinks we're still inside a string...
console.log('hello world');
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3827/73403353-414c6800-42bd-11ea-9298-2f36670fae3e.png)

**Comment by pyrmont** [comment]
@codebutler I think what's happening here is that the lexer is treating the `?` after the `a` as a ternary operator. What does `a?` represent? Is it just a name?

**Comment by jneen** [comment]
As far as I can tell this is a stage 4 draft, not yet part of the spec: https://tc39.es/proposal-optional-chaining/

**Comment by codebutler** [comment]
yes, this is the optional chaining operator. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

@jneen optional chaining is in wide use. it was added to typescript last year: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

**Comment by pyrmont** [comment]
@codebutler Is your use case using it with the TypeScript lexer? This could be added specifically to that lexer (and then moved into the JavaScript one once it receives broader adoption and/or becomes part of the spec).

**Comment by codebutler** [comment]
Yes, we are specifically seeing this with Typescript. I didn't realize it was a separate lexer.

**Comment by pyrmont** [comment]
@codebutler No worries. Thanks for filing the bug! Will have a look into it!
