### ISSUE TITLE
Support for Rego

### ISSUE THREAD

**Issue by RyPeck** [rouge-ruby/rouge#1435]
[Rego](https://www.openpolicyagent.org/docs/latest/#rego) is a high level declarative language built for expressing policy over hierarchical data structures. Used in [Open Policy Agent](https://www.openpolicyagent.org/).

`cson` for Atom in the OPA project -
https://github.com/open-policy-agent/opa/blob/master/misc/syntax/atom/language-rego/grammars/rego.cson

**Comment by pyrmont** [comment]
@RyPeck Thanks for filing the request about Rego :) At this stage in its development, Rouge predominantly relies on submissions from its community for new lexers. If you'd like to give it a shot, we have [documentation](https://rouge-ruby.github.io/docs/file.LexerDevelopment.html) about how to do that.
