### ISSUE TITLE
BrightScript lexer

### ISSUE THREAD

**Issue by lkinasiewicz** [rouge-ruby/rouge#1446]
BrightScript is a language used to develop TV apps for Roku - one of the leading TV streaming platforms in the U.S.

https://developer.roku.com/en-gb/docs/references/brightscript/language/brightscript-language-reference.md

**Implementation in other libraries**
This is an implementation for code editors in a textmate bundle format:
https://github.com/cmink/BrightScript.tmbundle/blob/master/Syntaxes/BrightScript.tmLanguage

**Comment by pyrmont** [comment]
Thanks for filing the issue. At this stage in its development, Rouge predominantly relies on submissions from its community for new lexers. I realise you're got experience with the LiveScript one as well so you're familiar with the process but if you do have any questions, feel free to file a PR with where you get up to and I'd be happy to help with a review or any answers I can provide.

**Comment by domRowan** [comment]
FYI, BrightScript support was added in this commit: https://github.com/rouge-ruby/rouge/commit/16ce5cec4948fac5cf7f5c7cef4c014b9b0a682e

And has since been included in release v.3.21.0: https://github.com/rouge-ruby/rouge/commit/76497f8582f753c37cd78167ace7f5df7e41657f

**Comment by pyrmont** [comment]
@domRowan Thanks for noting this. I'd forgotten when PR #1544 was submitted that it would close this issue. Cheers!
