### ISSUE TITLE
Harbour

### ISSUE THREAD

**Issue by rjopek** [rouge-ruby/rouge#1447]
Hi.

What should I do?
I would appreciate Harbour support in rouge. 

* [Harbour on GitHub](https://github.com/harbour/core)
* [Harbour Wikipedia](https://en.wikipedia.org/wiki/Harbour_(programming_language))

**Comment by pyrmont** [comment]
@rjopek Submit a pull request with a lexer! In addition to the information in the [README](https://rouge-ruby.github.io/docs/index.html), we have documentation on setting up a development environment ([here](https://rouge-ruby.github.io/docs/file.DevEnvironment.html)) and on developing a lexer ([here](https://rouge-ruby.github.io/docs/file.LexerDevelopment.html)).

**Comment by marwin1991** [comment]
@rjopek Have you manage to solve your problem because i Have the same :)

**Comment by rjopek** [comment]
I've completely abandoned Harbour – I'm moving all my old open-source projects to C.

See here [GT](https://github.com/dev-harbour/gt)
