### ISSUE TITLE
CMake syntax highlight gets confused by the naked escaped quote

### ISSUE THREAD

**Issue by danilaml** [rouge-ruby/rouge#1452]
**Name of the lexer**
CMake

**Code sample**

Here's how GitHub lexes it:

```cmake
list(APPEND CFLAGS -foo=\"${CMAKE_CURRENT_SOURCE_DIR}/bar\")
message("everything else is counted as part of the string")
```

And [here](http://rouge.jneen.net/v3.16.0/cmake/Y21ha2VfbWluaW11bV9yZXF1aXJlZChWRVJTSU9OIDIuOC4zKQoKcHJvamVjdChmb28gQykKCmFkZF9leGVjdXRhYmxlKGZvbyB1dGlscy5jICJmb28uYyIpCgpsaXN0KEFQUEVORCBDRkxBR1MgLWZvbz1cIiR7Q01BS0VfQ1VSUkVOVF9TT1VSQ0VfRElSfS9iYXJcIikKCnRhcmdldF9saW5rX2xpYnJhcmllcyhmb28gJHtMSUJSQVJJRVN9KQ) is how Rouge does it.

When Rouge encounters a "naked" `\"` it doesn't treat it as an escaped `"`, but rather as a `\` followed by the start of the string literal, hence the issue.

**Comment by pyrmont** [comment]
@danilaml I'm not especially familiar with CMake so allow me to check my understanding. What should happen is that both `\"` in the first line should not be treated as double quotes that would otherwise begin or end a string (as they do in the second line)?

**Comment by danilaml** [comment]
@pyrmont yes, see how GitHub parses it.
Basically, CMake can support differntly quoted arguments as well as [unquoted](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#unquoted-argument), in which case `\"` is still treated as escaped double quote, instead of the `\` followed by the start of the new string as it appears to be interpreted by rouge.
