### ISSUE TITLE
Add lexer for YANG

### ISSUE THREAD

**Issue by gribok** [rouge-ruby/rouge#1457]
_Please note: New lexers are contributed to Rouge from the community. Your request will help the community in developing a lexer but it does not mean that anyone **will** develop the lexer._

**The name of the language**
A lexer for modeling language **YANG**.
Documentation and BNF definiton under [RFC7950](https://tools.ietf.org/html/rfc7950#page-184)

**Implementation in other libraries**
I have already written the YANG lexer for pygments in python.
See PR pygments/pygments#1408

**Additional context**
I will migrate the lexer from python-pygments into rouge-ruby-code and create the PR.

**Comment by pyrmont** [comment]
Thanks @gribok!

**Comment by gribok** [comment]
@pyrmont : Sorry for confusing. Is it still possible to change a line in visual example via a new PR? 
Only a little important thing for me.
If not, it is also ok. :-)

**Comment by pyrmont** [comment]
@gribok Sorry, it's merged now :( You can branch off `master` and make a new PR if you want and I can merge that in.

**Comment by gribok** [comment]
> @gribok Sorry, it's merged now :( You can branch off `master` and make a new PR if you want and I can merge that in.

Thanks for fast response, @pyrmont. I created new PR #1474
