### ISSUE TITLE
Add dracula theme

### ISSUE THREAD

**Issue by iovw** [rouge-ruby/rouge#1459]
**Is your enhancement request related to a problem? Please describe.**
A clear and concise description of the problem. Eg. I'm always frustrated when [...]

**Describe the solution you'd like**
I want to add a [dracula theme!](https://draculatheme.com) 
**Additional context**
Add any other context or screenshots about the enhancement request here.
Look like this:
![image](https://user-images.githubusercontent.com/24983369/76294448-d8113900-62ed-11ea-901a-df185381951d.png)

**Comment by iovw** [comment]
My version look like:
![image](https://user-images.githubusercontent.com/24983369/76378886-9a61ee00-6389-11ea-9c35-30ea55606402.png)

**Comment by pyrmont** [comment]
I'm sorry not to have written sooner—particularly before you put this theme together—but at this stage of Rouge's evolution, we're not really looking to add more themes. We think this is an area better left to users to add as they see fit rather than be something that should be bundled together with the library.

Again, my apologies for not communicating that more quickly :(

**Comment by iovw** [comment]
But how?
How can users add theme but don't add code to this library? Write css? It's really ugly.
May need separate the theme generator from rouge if you think so.

**Comment by pyrmont** [comment]
What's the context in which you want to use the theme?

**Comment by iovw** [comment]
In my jekyll static blog.

**Comment by pyrmont** [comment]
In that case, CSS really seems like the appropriate place to define the theme.

If you really don't want to do that, you can throw your plugin into the `_plugins` directory of your Jekyll site and it will be like it was defined in Rouge itself.

**Comment by iovw** [comment]
Where introduced the `_plugins` directory?
I haven't found it at https://jekyllrb.com/docs/structure/

**Comment by pyrmont** [comment]
It's a directory you make. See [here](https://jekyllrb.com/docs/plugins/installation/).

**Comment by iovw** [comment]
Thank you.

**Comment by pyrmont** [comment]
It looks like your site is done through GitHub Pages. You won't be able to use the `_plugins` directory in that case. I'm sorry but in that case, the appropriate place to add the theme is via CSS.

**Comment by msangel** [comment]
It is possible to load custom theme class in generator:
```bash
# see it loaded
rougify -r /path/to/your/theme/class/for/example/_plugins/my_theme.rb help style
# generate with it:
rougify -r /path/to/your/theme/class/for/example/_plugins/my_theme.rb style MyTheme > assets/rouge.css
```
Sample theme file:
```
# -*- coding: utf-8 -*- #
# frozen_string_literal: true

module Rouge
  module Themes
    class MyTheme < CSSTheme
      name 'MyTheme'

      style Text,                             :fg => '#444444'
      style Comment::Preproc,                 :fg => '#CC00A3'
      style Comment::Special,                 :fg => '#CC00A3'
      style Comment,                          :fg => '#FF0000'
      style Keyword::Constant,                :fg => '#C34E00'
      style Keyword::Declaration,             :fg => '#0000FF'
      style Keyword::Reserved,                :fg => '#007575'
      style Keyword,                          :fg => '#0000FF'
      style Literal::String,                  :fg => '#009C00'
      style Literal::String::Affix,           :fg => '#0000FF'
      style Name::Builtin,                    :fg => '#C34E00'

      # rogue keep track of all its themes, but since we load out the theme
      # from the outer world, need to register it manually: 
      Theme.registry[name.to_s] = self
    end
  end
end
```
