### ISSUE TITLE
Incorrect tokenization of compact Ruby class names

### ISSUE THREAD

**Issue by ashmaroli** [rouge-ruby/rouge#1469]
## Name of the lexer
`Rouge::Lexers::Ruby`

## Code sample
A sample of the code that produces the bug.

```ruby
# Compact class name
class Rouge::Lexers::Ruby < RegexLexer
  def self.detect?(text)
    return true if text.shebang? 'ruby'
  end
end

# Nested class name
module Rouge
  module Lexers
    class Ruby < RegexLexer
      def self.detect?(text)
        return true if text.shebang? 'ruby'
      end
    end
  end
end
```
## Sample screenshot

![Screenshot_2020-03-27 ruby Visual Test](https://user-images.githubusercontent.com/12479464/77782779-d1b8e600-707d-11ea-9260-92d2baf15de5.png)

The class name **`Ruby`** has a different color in the two scenarios

**Comment by jneen** [comment]
Would you be willing to make a branch with this added to the sample file?
