### ISSUE TITLE
Structs, classes and typenames should be lexed similarly in C++ lexer

### ISSUE THREAD

**Issue by pyrmont** [rouge-ruby/rouge#1484]
**Name of the lexer**
C++

**Code sample**
```
class example1 {};
struct example2 {};
template <typename Type, class Class>
struct example {};
```

Live example on [rouge.jneen.net](http://rouge.jneen.net/v3.17.0/cpp/Y2xhc3MgZXhhbXBsZTEge307CnN0cnVjdCBleGFtcGxlMiB7fTsKdGVtcGxhdGUgPHR5cGVuYW1lIFR5cGUsIGNsYXNzIENsYXNzPgpzdHJ1Y3QgZXhhbXBsZSB7fTs)

**Additional context**
These issues were originally raised by @tcbrindle in #394.

**Comment by pyrmont** [comment]
@integricho I'm not sure if you're still interested in this problem, but I was wondering if you'd be able to help with my understanding.

Rouge's C++ lexer currently tokenises identifiers that come after the `class` keyword with the `Name::Class` token and identifiers that come after the `struct` keyword with the generic `Name` token. That matches my naïve interpretation of how the syntax should be tokenised given a struct is not a class but I gather that for C++ programmers, it's a little strange to treat them differently? Is there precedent for treating them the same (e.g. in language specification, IDEs, other syntax highlighters)?

Similarly, that's the case with identifiers that follow `class` and `typename`?

**Comment by integricho** [comment]
The only difference between a `struct` and a `class` in C++ is the default access specifier (for a `struct` it's `public` and for a `class` it's `private`), while in every other way they're the same, so I'd say they should be treated equally, from the syntax highlighting perspective at least.
Regarding IDEs and other syntax highlighters, of course, `struct`s and `class`es are always colored the same (at least in the tools that I've used so far, it was done that way).

Regarding the `class` vs `typename` issue, it depends in which context are the keywords encountered. In the above shown example, when they're in a `template` declaration, e.g.:
`template <typename Type, class Class>`, they have the same meaning, it doesn't make a difference which is used from the standard's perspective, so again, in that context, the color should be the same (and it is the same in IDEs, etc.)
Later on of course, `typename` is used to access dependent names on instantiated templates, and `class` is used to explicitly instantiate templates, so in those cases they really do different things. But again, if we focus only on the above shown examples, `typename` == `class`.

Thanks for you work! Much appreciated! :)

**Comment by pyrmont** [comment]
@integricho Thank you for responding so quickly! That all makes sense. I'll have a look at making the necessary adjustments.
