### ISSUE TITLE
[Turtle/TriG] The empty prefix is fine

### ISSUE THREAD

**Issue by kaefer3000** [rouge-ruby/rouge#1485]
**Name of the lexer**
Turtle/TriG

**Code sample**
```turtle
@prefix : <http://example.org/#> .

:this a :Test .
```
This data with a colon, preceded by the empty string, is valid.
Renders OK on GitHub, but not with Rogue, see:
[Link to a Code Sample](http://rouge.jneen.net/v3.17.0/turtle/QHByZWZpeCA6IDxodHRwOi8vZXhhbXBsZS5vcmcvIz4gLgoKOnRoaXMgYSA6VGVzdCAuCg).

**Additional context**
[The official Turtle grammar](https://www.w3.org/TR/turtle/#grammar-production-PNAME_NS)
[The line where I would try a fix if I knew Ruby](https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/lexers/turtle.rb#L56)

[dingus]: http://rouge.jneen.net/

**Comment by pyrmont** [comment]
@kaefer3000 That's indeed the right line. I gather there's no other use for `:`?

**Comment by kaefer3000** [comment]
From the top of my head, no. It may appear in a Literal, though. The following is weird, but valid.

```turtle
@prefix : <http://example.org/#> .

: a :AdditionalTest ;
  rdfs:comment ":-)"^^: .
```
