### ISSUE TITLE
[SPARQL] "a" is a keyword

### ISSUE THREAD

**Issue by kaefer3000** [rouge-ruby/rouge#1486]
**Name of the lexer**
SPARQL

**Code sample**
A sample of the code that produces the bug:

```sparql
PREFIX : <http://example.org/#> 
SELECT ?item ?itemLabel
WHERE
{
  ?item a :Test .
}
```

[Link to a code sample](http://rouge.jneen.net/v3.17.0/sparql/UFJFRklYIDogPGh0dHA6Ly9leGFtcGxlLm9yZy8jPiAKU0VMRUNUID9pdGVtCldIRVJFCnsKICA_aXRlbSBhIDpUZXN0IC4KfQo).

**Comment by pyrmont** [comment]
@kaefer3000 Thanks for the report. When you say that `a` is a keyword do you mean like the keywords listed here:

https://github.com/rouge-ruby/rouge/blob/f054b733b8e599c38812d32e98633fb25fb52bbd/lib/rouge/lexers/sparql.rb#L26-L32

**Comment by kaefer3000** [comment]
Thanks for the quick response!

I mean keyword as in here (note that SPARQL builds on Turtle).:
 https://github.com/rouge-ruby/rouge/blob/bbdf8c8d2e241f37212bbc865a3c4e9c5dcbf522/lib/rouge/lexers/turtle.rb#L52
Also see note 1 about the [SPARQL grammar](https://www.w3.org/TR/sparql11-query/#sparqlGrammar). I conclude from there that a is a keyword in the same sense as the lines you are quoting.
