### ISSUE TITLE
JavaScript comment in hash bug

### ISSUE THREAD

**Issue by maxlinc** [rouge-ruby/rouge#150]
Came across this bug... rouge doesn't like comments on the first line of a hash, but it is okay with comments on other lines:

![screen shot 2014-06-05 at 6 41 57 pm](https://cloud.githubusercontent.com/assets/896878/3194702/b1bcd05a-ed02-11e3-8d56-ac3480576953.png)

**Comment by realityking** [comment]
We've just run into the same issue. Is there a workaround?

**Comment by jneen** [comment]
Hm, this should have been fixed - which version of rouge are you running?

**Comment by realityking** [comment]
We were originally using 1.7.2, but upgrading to 1.8 didn't change anything.

**Comment by jneen** [comment]
Could you provide a sample of the js you're trying to highlight?

**Comment by realityking** [comment]
Sure:

```
{
  // ...    
  "metadata": {
       "clientTransactionId": "CLIENT STRING ID",
       "serverTransactionId": "UNIQUE SERVER TRANSACTION ID"
   }
}
```

We tried both the `json` (which we'd, but it's obviously invalid) and the `javascript` mode. The problem in `javascript` mode is probably, that it gets interpreted as a JS block. We're looking for a way to add comments to JSON objects as part of an API documentation.

**Comment by jneen** [comment]
Ah, well that's a feature request, since that's neither syntactically valid javascript or json.  Does the problem go away if you wrap it in parentheses? (not to say that's the solution, just want to check)

**Comment by textshell** [comment]
Related by doesn't fix the original issue.
Comments for json implemented in [pull request 243](https://github.com/jneen/rouge/pull/243) or [pull request 244](https://github.com/jneen/rouge/pull/244)

**Comment by miparnisari** [comment]
I think this can be closed @pyrmont 

![image](https://user-images.githubusercontent.com/5374887/58744556-72585e00-83f9-11e9-94aa-db4be40466de.png)

**Comment by pyrmont** [comment]
Thanks for the heads up!
