### ISSUE TITLE
c++ lexer can't handle scope resolution operator in case expression

### ISSUE THREAD

**Issue by tim-becker** [rouge-ruby/rouge#1506]
**Code sample**

```c++
switch (foo) {
  case Foo::kBar:
    break;
}
```

http://rouge.jneen.net/v3.18.0/cpp/c3dpdGNoIChmb28pIHsKICBjYXNlIEZvbzo6a0JhcjoKICAgIGJyZWFrOwp9

**Comment by pyrmont** [comment]
Thanks for the report, @tim-becker. I'll have a look at a fix.

**Comment by pyrmont** [comment]
@tim-becker Actually, I'm not sure I follow the problem. What do you mean by 'handle scope resolution operator'? This seems consistent with how Rouge's C++ lexer generally handles namespaces ([example](http://rouge.jneen.net/v3.18.0/cpp/ZW51bSBjbGFzcyBEYXkgewogIE1vbiwgVHVlLCBXZWQsIFRodXIsIEZyaSwgU2F0LCBTdW4KfTsKRGF5IHRvZGF5ID0gRGF5OjpNb247)).

**Comment by tim-becker** [comment]
There's a difference between how the two examples highlight the `::`. In the example I linked, the first `:` is highlighted as punctuation and the second as an operator. Also, the `:` at the end of the line is highlighted as an operator, when this is actually the punctuation.
