### ISSUE TITLE
Python lexer broken for raw strings in v3.18.0

### ISSUE THREAD

**Issue by tuxu** [rouge-ruby/rouge#1507]
**Name of the lexer**
Python

**Code sample**

The two below examples show that escaped characters in raw strings confuse the lexer.

```python
import re
s = "Hello World"
m = re.findall(r"^[\w]+", s)
print(m)
```
([rouge.jneen.net](http://rouge.jneen.net/v3.18.0/python/aW1wb3J0IHJlCnMgPSAiSGVsbG8gV29ybGQiCm0gPSByZS5maW5kYWxsKHIiXltcd10rIiwgcykKcHJpbnQobSk))

```python
devid_line = status_line.split('STATUS:')[0]
result_line = status_line.split('STATUS:')[1]
print(f'Parsing "{result_line}"...')

# parse devid string
pattern = re.compile(r'.*\[p00t_(d\d{4})\].*')
data = pattern.match(devid_line)
devid = data.group(1)
```
([rouge.jneen.net](http://rouge.jneen.net/v3.18.0/python/ZGV2aWRfbGluZSA9IHN0YXR1c19saW5lLnNwbGl0KCdTVEFUVVM6JylbMF0KcmVzdWx0X2xpbmUgPSBzdGF0dXNfbGluZS5zcGxpdCgnU1RBVFVTOicpWzFdCnByaW50KGYnUGFyc2luZyAie3Jlc3VsdF9saW5lfSIuLi4nKQoKIyBwYXJzZSBkZXZpZCBzdHJpbmcKcGF0dGVybiA9IHJlLmNvbXBpbGUocicuKlxbcDAwdF8oZFxkezR9KVxdLionKQpkYXRhID0gcGF0dGVybi5tYXRjaChkZXZpZF9saW5lKQpkZXZpZCA9IGRhdGEuZ3JvdXAoMSk))

**Additional context**

There is an issue in the GitLab issue tracker which describes the same problem:
https://gitlab.com/gitlab-org/gitlab/-/issues/215643

I traced the problem back to commit 652a6227: Use generic string states in Python lexer (#1477)

**Comment by pyrmont** [comment]
@tuxu Thanks for the detailed report and sorry for the trouble :( Will have a look at that now.

**Comment by Spindel** [comment]
It's not only raw strings, this also seems to set it off:

```python
var = "\w+"
foo = "bar"
```

**Comment by pyrmont** [comment]
@Spindel Thanks for the report! The code in the PR will fix this too :)
