### ISSUE TITLE
Allow "rougify style" with custom themes

### ISSUE THREAD

**Issue by theXYZT** [rouge-ruby/rouge#1512]
It seems `rougify style` can only accept themes that come with the library. There doesn't seem to be a way to define a `custom_theme.rb` in the same way as other themes are defined and have them "rougified" (converted to CSS).

If I am mistaken that this feature doesn't exist, I'd love to be told how to achieve this.

**Comment by pyrmont** [comment]
@theXYZT I think there might be three ways to address this.

First, to explain the problem. If you have a look at this excerpt:

https://github.com/rouge-ruby/rouge/blob/dca76dd0ca9ee8634a6775b39af63ba446a239b4/lib/rouge/cli.rb#L352-L370

you can see that the list available is whatever has been added to the theme registry by the time the `bin/rougify` script is run. The problem for you is that I don't think there's any capability to register themes beyond those listed in `lib/rouge.rb`:

https://github.com/rouge-ruby/rouge/blob/dca76dd0ca9ee8634a6775b39af63ba446a239b4/lib/rouge.rb#L93-L107

The three potential solutions I can see are:

1. **Create a fork**: If you hard code your custom theme into the list in `lib/rouge.rb`, it should be registered in the registry and become available as an option to `bin/rougify`. Themes are automatically registered through the use of the `Theme.name` method that you are most likely using at the top of your theme so, as long as you have given your custom theme a number, there's nothing additional you should need to do.

2. **Modify the script**: The `bin/rougify` script is [quite simple](https://github.com/rouge-ruby/rouge/blob/dca76dd0ca9ee8634a6775b39af63ba446a239b4/bin/rougify). You can write your own script that does everything `bin/rougify` does but also loads your custom theme.

3. **Allow custom themes**: Rouge is written to be extremely dynamic in terms of how it loads code. It should be relatively straightforward to update `Rouge::CLI` to allow a user to include a path to a custom theme. `Rouge::CLI` could then load that theme and make it available as the other themes are.

Am I missing something @jneen? Is there an existing way to do what @theXYZT is asking?

**Comment by jneen** [comment]
The canonical way to do it is this:

``` ruby
# my_cool_file.rb
class MyCoolTheme < Rouge::Theme
  name 'my-cool-theme'

  style Text,                        :fg => '#000000', :bg => '#ffffff'
  # ... etc ...
end

# in your cli
$ rougify -r my_cool_file.rb style my-cool-theme
```

**Comment by keryell** [comment]
> The canonical way to do it is this:

This is super useful information that deserves a place in the top `README.md`.

Now I need to figure out how to inject this in asciidoctor...
