### ISSUE TITLE
Haskell prime breaks highlighting

### ISSUE THREAD

**Issue by Fresheyeball** [rouge-ruby/rouge#1514]
**Describe the bug**
In the Haskell language the `'` character may be used in a variable name, and frequently is (pronounced "prime"). 

```haskell
foo :: Int -> Int
foo x' = x' + 1
```

This case causes the highlighting to treat the entire rest of the file as a giant string, since there is no closing `'`.

Other use cases for `'` appear to work, including describing a Char

```haskell
letterC :: Char
letterC = 'C'
```

and promoted types

```haskell
data Foo = Bar
toUnit :: Proxy 'Bar -> ()
toUnit _ = ()
```

but not in variable names.

**To Reproduce**
This effect can be seen in this file here:
https://gitlab.com/fresheyeball/Shpadoinkle/-/blob/master/examples/servant-crud/View.hs#L77

**Expected behavior**
The single tick is not treated as the start of a string. Note the syntax highlighting is correct on GitHub, which does not use Rouge. Here is the same file in a gist for comparison:
https://gist.github.com/Fresheyeball/495f2f68718cc1a539a00b7d36a4e4fd

**Comment by pyrmont** [comment]
@Fresheyeball When `'` is used to describe a Char, are the number of characters used in the source code always 1? Can you, for example, have this:

```
newline :: Char
newline = '\n'
```

**Comment by Fresheyeball** [comment]
@pyrmont the newline char example you posted is legal Haskell
