### ISSUE TITLE
Null coalesce breaks highlighting in template string (Javascript/Typescript)

### ISSUE THREAD

**Issue by Kcazer** [rouge-ruby/rouge#1516]
**Name of the lexer**
Typescript and Javascript lexers

The lexer fails when using the [null coalesce operator `??`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing) inside a template string.
All of the code after the end of the string is colored as if it was part of a giant string.

**Code sample**

```typescript
// Get value or undefined
const value = getValue();
const content = `Value is ${value ?? 'not set'}`;
const description = "Highlighting is broken now";

// Comments
console.log('And appears a a giant string');
```

Same code on [rouge.jneen.net][demo] :

| ![image](https://user-images.githubusercontent.com/609420/81914389-87f67180-95d1-11ea-9d54-e5e2fe91dabb.png) |
| --- |

[demo]: http://rouge.jneen.net/v3.19.0/javascript/Ly8gR2V0IHZhbHVlIG9yIHVuZGVmaW5lZApjb25zdCB2YWx1ZSA9IGdldFZhbHVlKCk7CmNvbnN0IGNvbnRlbnQgPSBgVmFsdWUgaXMgJHt2YWx1ZSA_PyAnbm90IHNldCd9YDsKY29uc3QgZGVzY3JpcHRpb24gPSAiSGlnaGxpZ2h0aW5nIGlzIGJyb2tlbiBub3ciOwoKLy8gQ29tbWVudHMKY29uc29sZS5sb2coJ0FuZCBhcHBlYXJzIGEgYSBnaWFudCBzdHJpbmcnKTs

**Comment by pyrmont** [comment]
@Kcazer Thanks for the report. Will take a look!

**Comment by donocode** [comment]
The same problem occurs for the optional chaining operator

```
const test = { }
console.log(`something ${test?.value}`);
const description = "Highlighting is broken now";
```

**Comment by pyrmont** [comment]
@Kcazer I've submitted a PR to the TypeScript lexer that fixes the use of `??` in template strings.

In terms of the JavaScript lexer, our approach with proposals to the JavaScript spec is to wait until they are accepted before incorporating them into the lexer. This is the reason optional chaining is only supported in the TypeScript lexer at this stage (see #1420).

**Comment by donocode** [comment]
Hi @pyrmont I was referring to Typescript for the optional chaining operator but I was mistaken, it is only broken in tsx (which is also called "Typescript") in the rouge preview site. See [a broken example of optional chaining in tsx](http://rouge.jneen.net/v3.19.0/tsx/ZnVuY3Rpb24gY3JlYXRlQ2Fub25pY2FsUmVxdWVzdChtZXRob2Q6ICdHRVQnLCB1cmw6IFVSTCwgaGVhZGVyc1RvU2lnbjogSGVhZGVycyk6IHN0cmluZyB7CiAgIGNvbnN0IGNhbm9uaWNhbFVyaSA9IGNyZWF0ZUNhbm9uaWNhbFVyaSh1cmwucGF0aG5hbWUpOwogICBjb25zdCBjYW5vbmljYWxRdWVyeVN0cmluZyA9IGNyZWF0ZUNhbm9uaWNhbFF1ZXJ5KHVybC5zZWFyY2gpOwogICBjb25zdCBjYW5vbmljYWxIZWFkZXJzID0gT2JqZWN0LmVudHJpZXMoaGVhZGVyc1RvU2lnbikKICAgICAubWFwKChba2V5LCB2YWx1ZV0pID0-IGAke2tleX06JHt2YWx1ZT8udHJpbSgpIHx8ICcnfWApCiAgICAgLmpvaW4oJ1xuJyk7CiAgIGNvbnN0IHNpZ25lZEhlYWRlcnMgPSBPYmplY3Qua2V5cyhoZWFkZXJzVG9TaWduKS5qb2luKCc7Jyk7CiAgIGNvbnN0IGhhc2hlZFBheWxvYWQgPSBlbXB0eUhhc2g7CiAgIGNvbnN0IHJlc3VsdCA9IFsKICAgICBtZXRob2QsCiAgICAgY2Fub25pY2FsVXJpLAogICAgIGNhbm9uaWNhbFF1ZXJ5U3RyaW5nLAogICAgIGNhbm9uaWNhbEhlYWRlcnMsCiAgICAgJycsCiAgICAgc2lnbmVkSGVhZGVycywKICAgICBoYXNoZWRQYXlsb2FkLAogICBdLmpvaW4oJ1xuJyk7CiAKICAgcmV0dXJuIGhhc2gocmVzdWx0KTsKIH0)

**Comment by pyrmont** [comment]
@donocode Ah, fair point about the TSX lexer  (coincidentally, [the next release](https://github.com/rouge-ruby/rouge/commit/3b9c42288ce8aa4ab06fab92e42e16978e939054) of Rouge will fix the name :D). Will get the optional chaining working there, too!

**Comment by pyrmont** [comment]
@Kcazer This has been added to the TypeScript lexer. Furthermore, it's been done in a way so that the TSX lexer will also recognise the operator.

@donocode I've moved the code prepending the optional chaining operator to the TypeScript common module and so now works in both the TypeScript and TSX lexers. This is also the case for the nullish coalescing operator.

A version of Rouge with these changes, v3.20.0, is scheduled for release on Tuesday 9 June. Thanks for the bug reports! This helps make Rouge better 👍

**Comment by Hxuhao233** [comment]
Hi, @pyrmont 
Could you add this feature in the javascript parser too? It seems to be a common usage.

**sample:**
``` javascript
const optional = `code${window?.console ?? true}`;
const java = 12;
const classes = `header ${ isLargeScreen() ? '' :
  `icon-${item.isCollapsed ? 'expander' : 'collapser'}` }`;
```

Same code on [rouge.jneen.net](http://rouge.jneen.net/v3.26.0/javascript/Y29uc3Qgb3B0aW9uYWwgPSBgY29kZSR7d2luZG93Py5jb25zb2xlID8_IHRydWV9YDsKY29uc3QgamF2YSA9IDEyOwpjb25zdCBjbGFzc2VzID0gYGhlYWRlciAkeyBpc0xhcmdlU2NyZWVuKCkgPyAnJyA6CiAgYGljb24tJHtpdGVtLmlzQ29sbGFwc2VkID8gJ2V4cGFuZGVyJyA6ICdjb2xsYXBzZXInfWAgfWA7)

![image](https://user-images.githubusercontent.com/15798755/106852672-673bf200-66f3-11eb-8fcf-96f2cc4d3ee0.png)


**Related Links**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#nesting_templates

**Comment by pyrmont** [comment]
@Hxuhao233 I'm no longer a maintainer on this project so I'm afraid I'm not the right person to ask any more. I'm sorry :(

Oh, and given the age of the earlier issue, I'd suggest opening a new one for this.

**Comment by Hxuhao233** [comment]
> @Hxuhao233 I'm no longer a maintainer on this project so I'm afraid I'm not the right person to ask any more. I'm sorry :(
> 
> Oh, and given the age of the earlier issue, I'd suggest opening a new one for this.

Thanks for the reply, I will open a new issue
