### ISSUE TITLE
JSX: Opening tag not rendered correctly 

### ISSUE THREAD

**Issue by netzwerg** [rouge-ruby/rouge#1517]
**Name of the lexer**
JSX

**Code sample**

```TSX
<header className="App-header">
  Hello React!
</header>
```
**Result (v3.19.0)**
<img width="458" alt="Screenshot 2020-05-22 at 10 26 48" src="https://user-images.githubusercontent.com/439387/82647629-c7970c00-9c16-11ea-99ea-d052ace08976.png">

http://rouge.jneen.net/v3.19.0/jsx/PGhlYWRlciBjbGFzc05hbWU9IkFwcC1oZWFkZXIiPgogIEhlbGxvIFJlYWN0IQo8L2hlYWRlcj4

**Comment by pyrmont** [comment]
@netzwerg Thanks for reporting this. I have a fix working as part of a broader update to the JSX and TSX lexers (#1492). The plan is for that to come out as part of the next release of Rouge, v3.20.0. That's scheduled for 9 June.

**Comment by netzwerg** [comment]
@pyrmont Excellent, thank you for letting me know!
