### ISSUE TITLE
Allow Unicode identifiers in several languages (Julia, XML, HTML, YML, CSS, JS, etc.)

### ISSUE THREAD

**Issue by BenjaminGalliot** [rouge-ruby/rouge#1534]
Hello,

This topic was first created there: https://gitlab.com/gitlab-org/gitlab/-/issues/220566

But it seems it is based on Rouge, so I link the problem here. At least, the same problem occurs on the Rouge online tester.

Non-ASCII characters in identifier names break syntax highlighting in several languages, like Julia, XML, HTML, YML, CSS, Javascript…

I made a specific repository to show: https://gitlab.com/BenjaminGalliot/non-ascii-character-problem-test

I know there were some related issues opened and merged about Java and Python, so maybe it is a really more general issue.

Sincerely.

**Comment by pyrmont** [comment]
@BenjaminGalliot We tend to wait for users of a particular language to submit PRs if a lexer isn't lexing valid input correctly as they are in a better position to inform us (with links to the appropriate documentation) what is and isn't a valid identifier in the given language.

Please feel free to submit any corrections; it would be much appreciated!
