### ISSUE TITLE
Rouge can't parse well using the `??` operator in js template literals

### ISSUE THREAD

**Issue by getty104** [rouge-ruby/rouge#1538]
**Name of the lexer**
JavaScript, TypeScript, JSX

**Code sample**

```js
console.log(`${a ?? b}`) // hoge hoge
```

**Screenshots**
<img width="519" alt="スクリーンショット 2020-06-09 16 39 46" src="https://user-images.githubusercontent.com/20335778/84119843-f236f080-aa6f-11ea-8f2d-da2e3c25c1ac.png">
<img width="340" alt="スクリーンショット 2020-06-09 16 39 54" src="https://user-images.githubusercontent.com/20335778/84119847-f3681d80-aa6f-11ea-8c4f-5a2aa067035c.png">

**Comment by pyrmont** [comment]
@getty104 This is the same as #1516, right? That's been fixed in `master` and will roll out as part of v3.20.0 of Rouge (that's scheduled for release later tonight/early tomorrow depending on your time zone).

**Comment by getty104** [comment]
@pyrmont Absolutely. Thank you!
