### ISSUE TITLE
Guesser: `dockerfile_spec.rb` is considered Ambiguoss instead of `ruby`

### ISSUE THREAD

**Issue by brodock** [rouge-ruby/rouge#1539]
_Please note: This is for non-lexer bugs._

**Describe the bug**
When using the guesser against a ruby rspec file that contains `dockerfile_` (lowercase) as part of the filename, it is being classified as ambiguous.

**To Reproduce**

```ruby
require 'rouge'

content = <<~EOF
# frozen_string_literal: true

require 'spec_helper'

RSpec.describe 'something' do
end
EOF

Rouge::Lexer.guess(filename: 'dockerfile_dropdown_spec.rb', source: content)

Traceback (most recent call last):
        5: from /Users/brodock/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `<main>'
        4: from /Users/brodock/.rvm/rubies/ruby-2.6.6/bin/irb:23:in `load'
        3: from /Users/brodock/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):26
        1: from /Users/brodock/.rvm/gems/ruby-2.6.6/gems/rouge-3.19.0/lib/rouge/lexer.rb:181:in `guess'
Rouge::Guesser::Ambiguous (Rouge::Guesser::Ambiguous)
```

**Expected behavior**
```
=> Rouge::Lexers::Ruby
```

**System (please complete the following information):**
 - OS: MacOS: 10.15.5
 - Ruby version: 2.6.6
 - Rouge version: 3.19.0

**Additional context**
There are additional information here: https://gitlab.com/gitlab-org/gitlab/-/issues/220877

Our current approach to deal with ambiguous is in https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/highlight.rb#L31-37, but it looks like the solution here would be to trust the extension in this case. Another possible solution would be to make sure https://github.com/rouge-ruby/rouge/blob/c46846803736ae1c43ba2873dba06d64c22082e1/lib/rouge/lexers/docker.rb#L11 matches the case correctly

**Comment by pyrmont** [comment]
@brodock Thanks for the report. It was my mistake to add the `Dockerfile_*` file glob. I've made a PR to revert that change.
