### ISSUE TITLE
C++ lexer is broken (typename)

### ISSUE THREAD

**Issue by szilardszaloki** [rouge-ruby/rouge#1546]
**Name of the lexer**
The name of the lexer with the bug:
C++, `typename` wrong color.

**Code sample**
A sample of the code that produces the bug:
```
template <typename, typename...>
struct whatever;
```
http://rouge.jneen.net/v3.20.0/cpp/dGVtcGxhdGUgPHR5cGVuYW1lLCB0eXBlbmFtZS4uLj4Kc3RydWN0IHdoYXRldmVyOwo

**Comment by pyrmont** [comment]
@szilardszaloki I'm not a C++ programmer. Is the above syntactically correct? That is, can you have `…` at the end?

**Comment by szilardszaloki** [comment]
@pyrmont Sure, this is a type template parameter pack.
