### ISSUE TITLE
Rego lexer needs some help

### ISSUE THREAD

**Issue by jcmcken** [rouge-ruby/rouge#1547]
**Name of the lexer**
rego

**Code sample**

If you look at the way GitHub renders this, it looks correct:

```rego
some_rule[msg] {
  msg := "hey"
}
```
However the same rendered with Rouge looks funky (underscore isn't parsed right, hard to distinguish variable names vs values, etc.). There may be other issues, but this is the one I noticed.

The full EBNF grammar can be found on OPA site: https://www.openpolicyagent.org/docs/latest/policy-reference/#grammar

For this example, the relevant grammar rule is ``rule-head``.

**Additional context**

http://rouge.jneen.net/v3.20.0/rego/c29tZV9ydWxlW21zZ10gewogIG1zZyA6PSAiaGV5Igp9

**Comment by jcmcken** [comment]
Issue where Rego was originally added: #1435

**Comment by jneen** [comment]
This is caused by a keyword list not being anchored to word boundaries - the `some` in that expression is being detected as a keyword.

**Comment by pyrmont** [comment]
@jneen Yeah, I need to go into that lexer and just do a generic match against word characters and then have a case statement in a block. Am working through the pile at the moment and can hopefully get to it tonight/this morning :)

**Comment by jcmcken** [comment]
``some`` as a keyword is one issue. Another issue is the flat color scheme (although admittedly there's probably some presentation configuration to change that -- but the defaults don't seem great. The specific application I'm using is GitLab, so I don't have much leeway to configure it). 

Rouge:

![image](https://user-images.githubusercontent.com/1117819/85301562-f999c900-b475-11ea-98fa-d73b28574c7c.png)

GitHub:

![image](https://user-images.githubusercontent.com/1117819/85301658-159d6a80-b476-11ea-96ad-786060e58462.png)

Not saying GitHub's highlighting is the ideal, but it's much less "flat" and easier to distinguish different parts of the grammar.

**Comment by jneen** [comment]
@pyrmont let's maybe take some time at some point to re-think the colour scheme in use on rouge.jneen.net - it's a little low-contrast for my tastes.

For reference, here's how it looks in Rouge's *actual* default colour scheme, "thankful_eyes":

<img width="148" alt="image" src="https://user-images.githubusercontent.com/225017/85347133-b1a29280-b4c5-11ea-8277-12722986b273.png">

**Comment by pyrmont** [comment]
@jneen Sure, that would be helpful, I think.

In @jcmcken's case, though, I think he might have been referring to the colour scheme being used by GitLab. I was a little unclear on that.

**Comment by jneen** [comment]
Oh! Yeah that colour scheme could use a good deal of work. cc @stanhu

**Comment by jcmcken** [comment]
OK, so it might be that GitLab itself isn't using a suitable color scheme and needs reconfiguration on their end (although other languages seem to look OK). Maybe I can submit a ticket in GitLab's issue tracker

**Comment by jneen** [comment]
I also agree with @pyrmont that this sample is a little over-highlighted. We often run into the problem where, if *everything* has a big bright token then nothing stands out. `msg` and `foo` in this example should probably be `Name::Variable` for starters.
