### ISSUE TITLE
COBOL

### ISSUE THREAD

**Issue by GitMensch** [rouge-ruby/rouge#1569]
**COBOL**
[Complete 2.0 draft for COBOL202x](https://isotc.iso.org/livelink/livelink?func=ll&objId=19468956)

**Implementation in other libraries**
[Pygments](http://pygments.org/) has `cobol` and `cobolfree` in [business lexers](https://github.com/pygments/pygments/blob/master/pygments/lexers/business.py), [Chroma](https://github.com/alecthomas/chroma) has [cobol](https://github.com/alecthomas/chroma/blob/master/lexers/c/cobol.go), there are more.

**Additional context**
Testing code can be find in multiple places, including [worldcities tutorial](https://sourceforge.net/p/gnucobol/contrib/HEAD/tree/trunk/samples/worldcities) and [cobjapi](https://sourceforge.net/p/gnucobol/contrib/HEAD/tree/trunk/tools/cobjapi/SWING/src_cobol/cobjapi.cob) (note: Allura uses pygments and has a hard-wired extension based selection of the language, in this case "cbl = cobolfree and cob = cobol", and therefore highlight these samples wrong).
If rouge takes the same approach as pygments (two different lexers), then it would be good to support the change via directive (if that's possible), a sample where the source ensures free-form reference-format is used is found [here](https://sourceforge.net/p/gnucobol/contrib/HEAD/tree/trunk/tools/TUI-TOOLS/GC99SCREENGEN.COB).

**Comment by pyrmont** [comment]
@GitMensch Thanks for filing the issue! At this stage in its development, Rouge predominantly relies on submissions from its community for new lexers. If you'd like to give it a shot, we have [documentation](https://rouge-ruby.github.io/docs/file.LexerDevelopment.html) about how to do that (the Pygments and Chroma lexers should provide good examples of the regular expressions to use).
