### ISSUE TITLE
JS: non string-literal highlighted as string literal

### ISSUE THREAD

**Issue by eukolab** [rouge-ruby/rouge#1591]
**Name of the lexer**
Javascript

**Code sample**

```
const text = `${obj.prop?.text}`;
console.log("Hello world!");
console.log("Foobar");
```

Code sample on [rouge.jneen.net][dingus].

http://rouge.jneen.net/v3.23.0/javascript/Y29uc3QgdGV4dCA9IChgJHtvYmo_LnByb3B9YCk7CmNvbnNvbGUubG9nKCJIZWxsbyB3b3JsZCEiKTsKY29uc29sZS5sb2coIkZvb2JhciIpOwo

Additional Context:
The issue seems to arise when '?' is found in a template literal expression.

[dingus]: http://rouge.jneen.net/

**Comment by pyrmont** [comment]
@eukolab Thanks for reporting this! I've merged @jneen's fix into master and it will be part of v3.24.0 going out a little bit later today.
