### ISSUE TITLE
Ruby lexer bug for regular expressions (since 3.24.0)

### ISSUE THREAD

**Issue by stomar** [rouge-ruby/rouge#1618]
**Name of the lexer**

Ruby lexer, since rouge 3.24.0 (problem doesn't occur in 3.23.0)

**Code sample**

``` ruby
/o/ =~ "foo"
str.gsub(/foo/, "bar")
```

This produces `<span class="err">` directly following the regular expression. Same for `%r{}` notation.

See:

- http://rouge.jneen.net/v3.24.0/ruby/L28vID1-ICJmb28i
- http://rouge.jneen.net/v3.24.0/ruby/IkhpIi5nc3ViKC9IaS8sICJCeWUiKQ

**Comment by jneen** [comment]
Confirmed. Looks like it's getting stuck in the `regex_flags` state - that state needs a default pop.

**Comment by To1ne** [comment]
For cross-referencing, this also affects GitLab https://gitlab.com/gitlab-org/gitlab/-/issues/276911
