### ISSUE TITLE
Q about Rouge / Pygments relationship

### ISSUE THREAD

**Issue by bradcray** [rouge-ruby/rouge#1627]
Hi Rouge Community —

[I apologize for opening this as an issue, but I couldn't find the answer in the documentation and wasn't finding another forum in which to ask it].

For context, I'm new to Rouge and coming at it from a "wanting to use it with Jekyll perspective" for a language not currently supported by Rouge.  I've read the documentation on creating a new lexer in Rouge and understand the general approach and work required, but am new enough to Ruby that I still have a lot of work ahead of me to get a working version.

My question is this:  If I already have a Pygments highlighter for our language, does the mention on http://rouge.jneen.net/ of Rouge being 100% compatible mean that I can somehow use that rather than creating a new Ruby lexer from scratch?  And if so, how?  I wasn't finding anything promising in the documentation, but may just be new enough to Rouge to be missing something obvious.

Thanks very much.

**Comment by jneen** [comment]
The model of Pygments and the model of Rouge are very similar, so it's easy to port. The main relationship we have to Pygments is that we use the same tokens and HTML signifiers in our output, so it's possible to use a stylesheet/colour scheme designed for Pygments with the output of rouge, and achieve approximately the same look.

Unfortunately we don't have a way of calling into Python to make that bridge work. There has been some talk about a tool that can convert Pygments lexers to Rouge ones, but I have not used it and I imagine it would take some manual tweaking to make it work properly.

**Comment by bradcray** [comment]
OK, thanks.  That's about what I suspected the stylesheet compatibility statement to mean, but I didn't want to miss an easy opportunity to avoid writing another highlighter if possible.  And thanks for the super-quick response!
