### ISSUE TITLE
TOML: keys starting with digits are not recognized properly

### ISSUE THREAD

**Issue by jaskij** [rouge-ruby/rouge#1636]
**Name of the lexer**
TOML

**Code sample**

```
aaa = "a:100"
100 = "a:100"
1a = "a:100"
```

Code sample on [rouge.jneen.net][dingus].

**Additional context**

In the above snippet all three lines have valid keys, but only the first one is recognized properly.

From [TOML specification](https://toml.io/en/v1.0.0-rc.3#keys) (emphasis mine):

> Bare keys may only contain ASCII letters, ASCII digits, underscores, and dashes (A-Za-z0-9_-). **Note that bare keys are allowed to be composed of only ASCII digits**, e.g. 1234, but are always interpreted as strings.

Note that this is handled properly by the INI lexer.

[dingus]: http://rouge.jneen.net/v3.25.0/toml/YWFhID0gImE6MTAwIgoxMDAgPSAiYToxMDAiCjFhID0gImE6MTAwIgo

**Comment by tancnle** [comment]
Looking into it.
