### ISSUE TITLE
Rust: Variable-initial underscore being lexed incorrectly

### ISSUE THREAD

**Issue by lunabunn** [rouge-ruby/rouge#1664]
**Name of the lexer**
Rust

**Code sample**
```rust
let _unused_variable = "foo";
```
http://rouge.jneen.net/v3.26.0/rust/bGV0IF91bnVzZWRfdmFyaWFibGUgPSAiZm9vIjs
![image](https://user-images.githubusercontent.com/29861658/103448241-a2ff1a00-4c64-11eb-810e-cfaaa4045d34.png)

**Additional Context**
From [Rust By Example 4. Variable Bindings](https://doc.rust-lang.org/rust-by-example/variable_bindings.html):
> The compiler warns about unused variable bindings; these warnings can be silenced by prefixing the variable name with an underscore

**Comment by tancnle** [comment]
@lunabunn This issue has been addressed by https://github.com/rouge-ruby/rouge/pull/1711.

See http://rouge.jneen.net/v3.27.0/rust/bGV0IF91bnVzZWRfdmFyaWFibGUgPSAiZm9vIjs
