### ISSUE TITLE
template string bug in javascript lexer

### ISSUE THREAD

**Issue by Hxuhao233** [rouge-ruby/rouge#1672]
**Name of the lexer**
javascript

**Code sample**
``` javascript
const optional = `code${window?.console ?? true}`;
const java = 12;
const classes = `header ${ isLargeScreen() ? '' :
  `icon-${item.isCollapsed ? 'expander' : 'collapser'}` }`;
```

Same code on [rouge.jneen.net](http://rouge.jneen.net/v3.26.0/javascript/Y29uc3Qgb3B0aW9uYWwgPSBgY29kZSR7d2luZG93Py5jb25zb2xlID8_IHRydWV9YDsKY29uc3QgamF2YSA9IDEyOwpjb25zdCBjbGFzc2VzID0gYGhlYWRlciAkeyBpc0xhcmdlU2NyZWVuKCkgPyAnJyA6CiAgYGljb24tJHtpdGVtLmlzQ29sbGFwc2VkID8gJ2V4cGFuZGVyJyA6ICdjb2xsYXBzZXInfWAgfWA7)

![image](https://user-images.githubusercontent.com/15798755/106852672-673bf200-66f3-11eb-8fcf-96f2cc4d3ee0.png)

Hi, i found a problem about template string when using the javascript lexer。
This is correct in the typescript parser https://github.com/rouge-ruby/rouge/issues/1516

**Related Links**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#nesting_templates

**Comment by digitalmoksha** [comment]
This is definitely still a problem, hopefully we can re-open this issue.

We're seeing reports of it on GitLab, https://gitlab.com/gitlab-org/gitlab/-/issues/331150

**Comment by markrian** [comment]
I [closed](https://gitlab.com/gitlab-org/gitlab/-/issues/331150#note_1527412235) the GitLab issue, as it appears to be fixed there. Was this fixed in this project? Can this issue be closed now?

**Comment by tancnle** [comment]
@markrian @digitalmoksha I believe this bug has been addressed as part of https://github.com/rouge-ruby/rouge/pull/1846. We can close this now.
