### ISSUE TITLE
Diff requires two newlines between diff-blocks to highlight properly

### ISSUE THREAD

**Issue by johannesstricker** [rouge-ruby/rouge#1676]
**Name of the lexer**
diff

**Code sample**
```diff
// path/to/file.js

+ this is inserted
+ over multiple lines

- this is removed
- over multiple lines
```
This is how the output looks:
![image](https://user-images.githubusercontent.com/12081471/107475060-cffff000-6b73-11eb-89a8-3bdf271db582.png)
As you can see, it doesn't highlight the first line of a new diff block. It only works when I add an additional newline in between.
Also, why is the `//` at the beginning of the file wrapped in a `<span class="err">` 🤔

**Comment by connection-reset** [comment]
I have the same issue and did some investigation. The diff lexer is correct, if strict.
In the unified diff format, there is always at least the prefix character + (plus), - (minus), or ␣ (space).
So apparently empty lines in a diff are not empty, they contain `␣\n` (space)(newline).

The diff lexer does not understand empty lines, i.e. lines that only contain `\n` (newline). It prepends them to the next line and yields that as a text token, i.e. `\n+some insert\n`.

I am using AsciiDoctor to render AsciiDoc with embedded diffs to HTML.
AsciiDoctor strips whitespace of the whole document before passing code blocks to Rouge, resulting in this issue.
I believe this is a bug in AsciiDoctor.

**Comment by colinodell** [comment]
I encountered this exact same issue using Rouge within Jekyll.  It turns out my IDE was stripping trailing whitespace which caused the single space on those "empty" lines to be removed, thus triggering this issue.

**Comment by tancnle** [comment]
@johannesstricker As part of https://github.com/rouge-ruby/rouge/pull/1854, the rule around empty lines has been relaxed, it no longer requires spaces.
