### ISSUE TITLE
Line number issue when using redcarpet plugin

### ISSUE THREAD

**Issue by rishighan** [rouge-ruby/rouge#168]
Hi there, 

 Thanks for writing this amazing gem.
I am using the redcarpet plugin and initialize it as mentioned in the wiki.

Only thing, I don't know where to specify `line_numbers: true`
I know that I can use a parameter in the URL to do so, but I don't want to.
I took a look at the source and was wondering it putting it in the `redcarpet.rb` would be an option...

```
  formatter = rouge_formatter(
          :css_class => "highlight #{lexer.tag}"
          :line_numbers => true
   )

```

I realize that not everyone will like this, but is there any other way to do line numbers when using the plugin?

**Comment by sulmanhotmail** [comment]
Hello jneen. By entering above code the theme is lost.
<img width="1166" alt="screen shot 2015-10-21 at 13 05 15" src="https://cloud.githubusercontent.com/assets/11699039/10634825/6d6e8b0e-77f4-11e5-8bc5-1ee9b56eb813.png">

before putting line numbers them was like:
<img width="1104" alt="screen shot 2015-10-21 at 13 06 14" src="https://cloud.githubusercontent.com/assets/11699039/10634839/8b72c2c8-77f4-11e5-8260-b2699ea3edb4.png">

Please jneen help me to have same theme but line_number are shown

**Comment by BigChief45** [comment]
@sulmanweb Did you find a solution for this?

**Comment by zinefer** [comment]
If I'm not mistaken, do this to solve your problem:

```rb
class HTML < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
  def rouge_formatter(lexer)
    opts = { line_numbers: true, css_class: "highlight #{lexer.tag}" }
    Rouge::Formatters::HTMLLegacy.new(opts)
  end
end
```
