### ISSUE TITLE
How to use new lexer on GitHub Pages

### ISSUE THREAD

**Issue by reifjulian** [rouge-ruby/rouge#1684]
I submitted a [PR](https://github.com/rouge-ruby/rouge/pull/1658) for a new Stata lexer for Rouge. I would like to go ahead and start using this new lexer on my GitHub Pages website in the meantime. I added the following line to my gemfile:
```
gem "rouge", git: 'https://github.com/reifjulian/rouge'
```

When I type `bundle update`, Ruby confirms that it is using my version of Rouge:
`Using rouge 3.26.0 from https://github.com/reifjulian/rouge (at master@69b1b00)`

However, when I view my website (`bundle exec jekyll serve`), my Stata code is still not highlighted. I am using the "```stata" tag in my markdown code, and the Stata lexer I wrote specifies that the tag is "stata". Is there something else I need to do? Please feel free to point me a guide or reference that I missed.

**Comment by reifjulian** [comment]
Thanks, that makes sense. However, this issue arises locally too. That is, I checked out a local version of my [website](https://github.com/reifjulian/reifjulian.github.io), added the line mentioned above to my gemfile, updated my bundle, and viewed it locally (`bundle exec jekyll serve`). That should have worked, right?

**Comment by robin850** [comment]
Ah yes you're right. I didn't see it the first time around but you need to specify the branch on your Git repository:

~~~ruby
gem "rouge", git: 'https://github.com/reifjulian/rouge', branch: 'stata'
~~~

**Comment by reifjulian** [comment]
This fixed the issue for me, thank you very much!
