### ISSUE TITLE
Support JEP 378 Text Blocks in Java lexer highlighting

### ISSUE THREAD

**Issue by patrick-webs** [rouge-ruby/rouge#1687]
**Name of the lexer**
Java

**Code sample**
https://openjdk.java.net/jeps/378 adds `"""` delimited text blocks to Java 15, but these aren't supported

[Example from rouge.jneen.net](http://rouge.jneen.net/v3.26.0/java/cHVibGljIGNsYXNzIFRleHRCbG9ja3NEZW1vIHsKICBwcml2YXRlIHN0YXRpYyBmaW5hbCBTdHJpbmcgZXhhbXBsZSA9ICIiIgogICAgICAgICAgICAgIDxodG1sPgogICAgICAgICAgICAgICAgICA8Ym9keT4KICAgICAgICAgICAgICAgICAgICAgIDxwPkhlbGxvLCB3b3JsZC4gVGhpcyB0ZXh0IGJsb2NrIHNob3VsZCBhbGxvdyBlbmNsb3NlZCBxdW90YXRpb24gbWFya3MgbGlrZSAiIHdpdGhvdXQgYnJlYWtpbmcgc3Vic2VxdWVudCBzeW50YXggaGlnaGxpZ2h0aW5nLCBidXQgaXQgZG9lc24ndC48L3A-CiAgICAgICAgICAgICAgICAgIDwvYm9keT4KICAgICAgICAgICAgICA8L2h0bWw-CiAgICAgICAgICAgICAgIiIiOwogIHB1YmxpYyBUZXh0QmxvY2tzRGVtbygpIHsKICAgIFN5c3RlbS5vdXQucHJpbnRsbigiSGVsbG8sIHdvcmxkISIpOwogIH0KfQ)

```java
public class TextBlocksDemo {
  private static final String example = """
              <html>
                  <body>
                      <p>Hello, world. This text block should allow enclosed quotation marks like "
              without breaking subsequent syntax highlighting, but it doesn't.</p>
                  </body>
              </html>
              """;
  public TextBlocksDemo() {
    System.out.println("Hello, world!");
  }
}
```

This shows a syntax error on the ' character within the text block, and on a " character in the constructor.

**Additional context**

**Comment by fprochazka** [comment]
Can we reopen this please?
