### ISSUE TITLE
Support for MDX (Markdown + JSX) files

### ISSUE THREAD

**Issue by milgner** [rouge-ruby/rouge#1692]
**Is your enhancement request related to a problem? Please describe.**

We started using [MDX](https://mdxjs.com/) in one of our projects and realized that rouge-based syntax highlighting doesn't work with these files.

**Describe the solution you'd like**

It would be great to see this format supported by rouge. Ideally all Markdown-specific parts are highlighted via existing Markdown styling and JSX-specific parts handled by existing JSX functionality.

**Additional context**

The MDX specification can be found here: https://github.com/mdx-js/specification

**Comment by mhowes-veracode** [comment]
When previewing MDX files in GitLab, using **View file @** on the **Changes** tab in an MR, the preview shows the Markdown source instead of the rendered output.
