### ISSUE TITLE
Drop support for deprecated Ruby versions

### ISSUE THREAD

**Issue by tancnle** [rouge-ruby/rouge#1694]
## Description

With Ruby 2.4 EOL (https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/), we should drop support for old versions to reduce Rouge gem maintenance effort. It also helps to reduce build runtime and avoid overrunning our monthly CI build time allotment.

## Proposal

* Update README and gemspec to indicate this change
* Remove Ruby 2.4 and below from CI pipelines (i.e. `.travis.yml`)
* Update Rubocop to target Ruby 2.5 (i.e. `rubocop.yml`)
* Mark this change for a minor version bump

**Comment by dblessing** [comment]
Thanks @tancnle. I agree with only supporting 2.5+

**Comment by tancnle** [comment]
Superseded by https://github.com/rouge-ruby/rouge/pull/1862
