### ISSUE TITLE
HTML templates are not highlighted in Angular components (.ts files)

### ISSUE THREAD

**Issue by WouldYouKindly** [rouge-ruby/rouge#1707]
Hello!

This snippet is not highlighted on Gitlab, although it's a valid syntax in Angular:

```
// some-comp.component.ts
@Component({
  selector: 'selector',
  template: `<ng-container *ngIf="false"></ng-container>`
})
class SomeComp {}
```

**Comment by tancnle** [comment]
👋🏼  @WouldYouKindly Is it still an issue? I have checked with the latest release v3.30.0 and it seems to be ok.

![Screen Shot 2022-08-18 at 9 20 38 pm](https://user-images.githubusercontent.com/756722/185383114-e7a9386d-7f37-4ba5-951d-7d46b9ccf29c.png)

(see [link](http://rouge.jneen.net/v3.30.0/typescript/Ly8gc29tZS1jb21wLmNvbXBvbmVudC50cwpAQ29tcG9uZW50KHsKICBzZWxlY3RvcjogJ3NlbGVjdG9yJywKICB0ZW1wbGF0ZTogYDxuZy1jb250YWluZXIgKm5nSWY9ImZhbHNlIj48L25nLWNvbnRhaW5lcj5gCn0pCmNsYXNzIFNvbWVDb21wIHt9Cg))

**Comment by WouldYouKindly** [comment]
Hi @tancnle to my great sadness, I no longer enjoy the luxury of working with Gitlab, so I can't confirm.
