### ISSUE TITLE
the PHP lexer does not properly handle namespace separators in qualified names

### ISSUE THREAD

**Issue by stof** [rouge-ruby/rouge#1718]
**Name of the lexer**
PHP

**Code sample**

```php
<?php

use ScssPhp\ScssPhp\Compiler;

try {
    $compiler = new Compiler();

    echo $compiler->compileString($content)->getCss();
} catch (\Exception $e) {
    echo '';
    syslog(LOG_ERR, 'scssphp: Unable to compile content');
}
```

I could not provide this on http://rouge.jneen.net/ because I got 503 errors when trying to use it.

**Additional context**
the `\` in `catch(\Exception $e)` gets highlighted as an error, while it is not an error

**Comment by pyrmont** [comment]
@stof I'm not working on this project any more but in my quick tests, it looks like there's a problem with the lexing of the `(` after `compileString`. Not sure if fixing that will fix everything else.

**Comment by stof** [comment]
@pyrmont which kind of problem ?

**Comment by stof** [comment]
For reference, the live version of that code snippet is at https://scssphp.github.io/scssphp/docs/#security-considerations
This is rendered using github pages, which uses rouge.

**Comment by pyrmont** [comment]
@stof If you paste your example up to the `(` in the dingus, it updates the right hand side but as soon as you have the `(` then it stops updating. So I assume there something breaking there.

**Comment by Linettegalarza94** [comment]
hi
I do not know how this worck
