### ISSUE TITLE
SQL Windowing keywords

### ISSUE THREAD

**Issue by hawkfish** [rouge-ruby/rouge#1753]
**Is your enhancement request related to a problem? Please describe.**
`WINDOW`, `PARTITION` and `RANGE` are not recognised as keywords in the syntax highlighting right now.

**Describe the solution you'd like**
Add them to the list.

**Additional context**
Here is a fairly complete windowing query using common syntax:

```sql
SELECT "Plant", "Date",
    AVG("MWh") OVER seven AS "MWh 7-day Moving Average"
FROM "Generation History"
WINDOW seven AS (
    PARTITION BY "Plant"
    ORDER BY "Date" ASC
    RANGE BETWEEN INTERVAL 3 DAYS PRECEDING
              AND INTERVAL 3 DAYS FOLLOWING)
ORDER BY 1, 2
```

**Comment by tancnle** [comment]
Resolved by https://github.com/rouge-ruby/rouge/pull/1754
