### ISSUE TITLE
Next release ETA?

### ISSUE THREAD

**Issue by robin-aws** [rouge-ruby/rouge#1755]
Apologies for being impatient. :) I realized I mistakenly thought `3.26.1` included the new Dafny support, and only now realize that #1647 just missed the train.

**Comment by reifjulian** [comment]
See also #1674

**Comment by tancnle** [comment]
@robin-aws Sorry for the delay. We have released `3.27.0` with Dafny support (https://github.com/rouge-ruby/rouge/pull/1774).
