### ISSUE TITLE
PowerShell subexpressions nested within strings

### ISSUE THREAD

**Issue by thecityofguanyu** [rouge-ruby/rouge#1757]
**Name of the lexer**
PowerShell

**Code sample**
A sample of the code that produces the bug.

```
function Write-Log {
    Param(
        $Message,
        $Path = "L:\IISSiteAudit.txt"
    )

    function TS { return "[{0:MM/dd/yy} {0:HH:mm:ss}]" -f (Get-Date) }
    "$(TS) $Message" | Tee-Object -FilePath $Path -Append | Write-Verbose
}
```

Sample on [rouge.jneen.net](http://rouge.jneen.net/v3.26.1/powershell/ZnVuY3Rpb24gV3JpdGUtTG9nIHsKICAgIFBhcmFtKAogICAgICAgICRNZXNzYWdlLAogICAgICAgICRQYXRoID0gIkw6XElJU1NpdGVBdWRpdC50eHQiCiAgICApCgogICAgZnVuY3Rpb24gVFMgeyByZXR1cm4gIlt7MDpNTS9kZC95eX0gezA6SEg6bW06c3N9XSIgLWYgKEdldC1EYXRlKSB9CiAgICAiJChUUykgJE1lc3NhZ2UiIHwgVGVlLU9iamVjdCAtRmlsZVBhdGggJFBhdGggLUFwcGVuZCB8IFdyaXRlLVZlcmJvc2UKfQo).

**Additional context**
Specifically, characters after the `"$()` get mangled as if they're all part of the string -- even after the closing `"` character. 

Originally observed via GitLab 14.3.2. Re-produced locally with Rogue v3.26.1 via `rougify`,

[dingus]: http://rouge.jneen.net/

**Comment by retryW** [comment]
Has been an annoyance of mine in GitLab for some time and when I saw it still existed in 15.1 I started seeing if it was raised as an issue.

Would very much love to see some movement on this one :)
