### ISSUE TITLE
Support PHP8 attributes

### ISSUE THREAD

**Issue by bobvandevijver** [rouge-ruby/rouge#1759]
**Is your enhancement request related to a problem? Please describe.**
PHP8 added [attribute support](https://www.php.net/manual/en/language.attributes.overview.php), but they are currently rendered as simply a comment.

**Describe the solution you'd like**
I would like to see similar syntax highlighting as with normal classes.

**Additional context**
See this [example](http://rouge.jneen.net/v3.26.0/php/LyoqCiAqIFNvbWUgY29tbWVudAogKi8KI1tSb3V0ZSgiL2FwaSIsIG5hbWU6ICJhcGkiKV0KY2xhc3MgQ29udHJvbGxlcgp7CiAgLy8gQSBjb21tZW50CiAgcHVibGljIGZ1bmN0aW9uIHNlcnZlKCl7CiAgICBlY2hvICJ0ZXN0IjsKICB9Cn0).

**Comment by kissifrot** [comment]
Hello, do you have any news about this? 
PHP 8+ is now widely used, and doing MR reviews is getting quite difficult when all attributes are displayed as comments 😅
