### ISSUE TITLE
Valid Kotlin syntax highlighted as error

### ISSUE THREAD

**Issue by npryce** [rouge-ruby/rouge#1760]
**Name of the lexer**
kotlin

**Code sample**
A sample of the code that produces the bug.

```
// The ? is not an error
fun <T : Any> foo(a: Array<T?>): Int = a.size

// The < is not an error
val <T> T.exhaustive get() = this

// The . in Map.Entry is not an error
fun foo(props: Iterable<Map.Entry<String, JsonNode>>) = 
    TODO()
```

http://rouge.jneen.net/v3.26.1/kotlin/Ly8gVGhlID8gaXMgbm90IGFuIGVycm9yCmZ1biA8VCA6IEFueT4gZm9vKGE6IEFycmF5PFQ_Pik6IEludCA9IGEuc2l6ZQoKLy8gVGhlIDwgaXMgbm90IGFuIGVycm9yCnZhbCA8VD4gVC5leGhhdXN0aXZlIGdldCgpID0gdGhpcwoKLy8gVGhlIC4gaW4gTWFwLkVudHJ5IGlzIG5vdCBhbiBlcnJvcgpmdW4gZm9vKHByb3BzOiBJdGVyYWJsZTxNYXAuRW50cnk8U3RyaW5nLCBKc29uTm9kZT4-KSA9IAogICAgVE9ETygp

**Comment by vidarh** [comment]
@npryce If you're able to test this locally (bundle exec rackup if you check it out), let me know if this looks reasonable to you (I added new examples at the bottom of the visual test), as I don't use Kotlin myself. The Kotlin lexer looks like it's taking quite a few shortcuts so could probably use more love but this at least gets rid of the errors.
