### ISSUE TITLE
add Stan lexer

### ISSUE THREAD

**Issue by spinkney** [rouge-ruby/rouge#1768]
**Stan**
Language documentation: https://mc-stan.org/docs/2_28/reference-manual/index.html

**Implementation of Stan language syntax highlighting in other libraries**
[Pygments](https://github.com/pygments/pygments/blob/master/pygments/lexers/_stan_builtins.py)
[PrismJS](https://github.com/PrismJS/prism/blob/master/components/prism-stan.js)
[VS-code](https://github.com/ivan-bocharov/stan-vscode)
[Emacs](https://github.com/stan-dev/stan-mode)
[Vim](https://github.com/eigenfoo/stan-vim)
[highlight.js](https://github.com/highlightjs/highlight.js/blob/main/src/languages/stan.js)
[LaTeX listings](https://github.com/jrnold/lstbayes)
[Atom](https://github.com/jrnold/atom-language-stan)
[JupyterLab](https://github.com/WardBrian/jupyterlab-stan-highlight/blob/master/lib/stan.js)

**Comment by tancnle** [comment]
Closed by https://github.com/rouge-ruby/rouge/pull/1735
