### ISSUE TITLE
elisp support

### ISSUE THREAD

**Issue by spcbfr** [rouge-ruby/rouge#1771]
_Please note: New lexers are contributed to Rouge from the community. Your request will help the community in developing a lexer but it does not mean that anyone **will** develop the lexer._

**The name of the language**
Emacs-lisp (elisp) here is [the syntax](https://www.gnu.org/software/emacs/manual/html_mono/elisp.html)

**Implementation in other libraries**
prism supports elisp, not sure if that counts

**Additional context**
A lot of people use elisp for their emacs configuration (me being one of them), and I have my literate config in gitlab since gitlab uses rouge for it's syntax highlighting, I get no syntax highlighting

**Comment by i-koch** [comment]
rouge supports *.el files with the common_lisp lexer.
