### ISSUE TITLE
Next release ETA?

### ISSUE THREAD

**Issue by reifjulian** [rouge-ruby/rouge#1776]
I added a new Stata lexer in December 2020, but noticed that #1658 was not included in the 3.27.0 release. @tancnle, is it possible to include this in the next release? I know of several people eager to use the Stata lexer.

**Comment by tancnle** [comment]
@reifjulian The new release ([v3.28.0](https://rubygems.org/gems/rouge/versions/3.28.0)) which included Stata lexer has been pushed to `rubygems`. Closing the issue now.
