### ISSUE TITLE
Rust: keyword `in` missing from lexer

### ISSUE THREAD

**Issue by QWERTZenjoyer** [rouge-ruby/rouge#1778]
**Name of the lexer**
Rust

**Code sample**

```
for i in 0..10 {
    println!("{}", i);
}
```
Here, the keyword `in` is not recognized as such by the lexer.

**Comment by tancnle** [comment]
@QWERTZenjoyer This issue should be resolved by https://github.com/rouge-ruby/rouge/pull/1649.
