### ISSUE TITLE
block comments highlight for PHP does not work when there exists double asterisk

### ISSUE THREAD

**Issue by ZsgsDesign** [rouge-ruby/rouge#1782]
**Name of the lexer**
PHP

**Description**
Block comments highlight for PHP does not work when there exists double `*`, here I would use C++ as a comparison.

**Code sample**
Both works when one-liner:

C++:

```cpp
/* This works */
```

PHP:

```php
<?php
/* THis works too */
```

Both work when block with a single `*`:

C++:

```cpp
/*
 * This works
 */
```

PHP:

```php
<?php
/*
 * This works too
 */
```

BUT PHP highlighter would not work when involving double `*`, as php-doc style guided:

C++:

```cpp
/**
 * This works for sure
 */
```

PHP:

```php
<?php
/**
 * This should work but sadly no
 */
```

Both C++ and PHP comments are valid here but only C++ lexer parsed block comments the right way.

**Comment by BenSouchet** [comment]
@ZsgsDesign I just check and it's work as expected see:
http://rouge.jneen.net/v3.27.0/php/PD9waHAKLyoqCiAqIFRoaXMgd29yawogKi8KPz4K

**Comment by ZsgsDesign** [comment]
> @ZsgsDesign I just check and it's work as expected see: http://rouge.jneen.net/v3.27.0/php/PD9waHAKLyoqCiAqIFRoaXMgd29yawogKi8KPz4K

It does not, if you check the CSS it uses default parent color, which means black on most of the cases. And its class also does not use proper comment class. What you see as grey is the default color, Which is also grey if you type random text.

![image](https://user-images.githubusercontent.com/19504567/150711504-fb1705d4-36ea-4534-b59a-27519a93d3f0.png)

**Comment by ZsgsDesign** [comment]
I originally thought the same, so I am planning to post this issue on `gitlab-ee` because I spot this bug on the GitLab file view. Later I checked the semantic highlighter and styles, classes it generated, finding out the web demo uses grey as the default color and it actually parses it wrong, I then posted it here.

**Comment by ZsgsDesign** [comment]
@BenSouchet 

I figured out it's not rouge's fault, rouge parsed it into type `Comment.Doc` currently and designated it as class `cd`. But sadly both `dingus` and `rouge.jneen.net` did not provide style support for this new `cd` class, neither does `gitlab` and other rouge users.
