### ISSUE TITLE
Tab indentation width

### ISSUE THREAD

**Issue by konsolebox** [rouge-ruby/rouge#1823]
Hello, is there a way to customize the displayed width of tabs to 4 spaces? If not, where is the best place to add the custom behavior?

**Comment by tancnle** [comment]
@konsolebox Sorry I don't really get the context of your question 🙏🏼 Could you elaborate a bit more?

**Comment by konsolebox** [comment]
Thanks for the reply. I utilize Jekyll to generate pages with highlighting enabled. Tabs in highlighted code become displayed in browsers with a width of 8 spaces but I want to reduce it to 4, like having a `.editorconfig` with `indent_size = 4` in a github repository so code with tabs are rendered in 4-spaced indents.

I can write a Jekyll plugin which extends Rouge if Rouge doesn't have this feature yet but I'll need basic directions.

**Comment by konsolebox** [comment]
It turns out Github simply uses `tab-size`. It's pretty odd how I missed it. I'll just close this.
