### ISSUE TITLE
Gherkin: Support `Rule` keyword

### ISSUE THREAD

**Issue by shivjm** [rouge-ruby/rouge#1827]
**Is your enhancement request related to a problem? Please describe.**
[The `Rule` keyword](https://cucumber.io/docs/gherkin/reference/#rule) was added in v6, but Rouge doesn’t recognize it.

**Describe the solution you'd like**
Rouge should recognize the keyword. I don’t believe any additional processing is required, as it only affects the indentation of the contained `Example`s/`Scenario`s.

**Comment by jsa34** [comment]
I've just come across this when using Gitlab's markdown for gherkin and it would be extremely helpful.
