### ISSUE TITLE
C++ logical statements which only contain a one line expression are not indented.

### ISSUE THREAD

**Issue by MaxMansfield** [rouge-ruby/rouge#183]
While using [exercism.io](http://exercism.io which highlights) which uses rouge to highlight my C++ I've had the issue that logical statements such as `if` `else` and `for` which only contain a one line expression are displayed incorrectly **even with brackets**.
## Example 1

A single `if` statement no brackets 

``` c++
      if(!isWord(word_cpy))
    return ret;
```

_Example 1 should be_

``` c++
      if(!isWord(word_cpy))
         return ret;
```
## Example 2

A single `if`statement nested in a `for` loop **with brackets** 

``` c++
  for(auto s : word_list){
      boost::trim(s);
      if(!s.empty()){
    ++word_map[s];
      }
    }
```

_Example 2 should be_

``` c++
 for(auto s : word_list){
      boost::trim(s);
      if(!s.empty()){
        ++word_map[s];
      }
    }
```
## Example 3

A bracketless `for` loop which does not correctly indent a bracketless `if` statment

``` c++
      for(auto word : words)
    if(isValid(word))
      matches.push_back(word);
```

_Example 3 should be_

``` c++
      for(auto word : words)
        if(isValid(word))
          matches.push_back(word);
```
## Example 4

An `if` `else` statement **with brackets** nested inside a `for` loop. It is not indented properly with a nested bracketless `if` `else` statement whose contents are indented properly

``` c++
  for(auto c : words){
      if(isalpha(c) && c != '\0'){
    word += c;
      } else {
    if(wordlist.find(word) == wordlist.end())
      wordlist.insert(std::pair<std::string,int>(word,1));
    else
      ++wordlist[word];

    word = "";
      }
    }
```

_Example 4 should be_

``` c++
  for(auto c : words){
      if(isalpha(c) && c != '\0'){
        word += c;
      } else {
        if(wordlist.find(word) == wordlist.end())
          wordlist.insert(std::pair<std::string,int>(word,1));
        else
          ++wordlist[word];

        word = "";
      }
    }
```

**Comment by MaxMansfield** [comment]
Wow, I feel terrible that I completely forgot about this. I must have missed the initial email for your response. Not that it matters now but, yes, the issue is resolved.

**Comment by pyrmont** [comment]
@MaxMansfield Don't feel bad—that's great it's fixed :) Thanks for getting in touch!
