### ISSUE TITLE
Bug in JavaScript lexer

### ISSUE THREAD

**Issue by legacy3** [rouge-ruby/rouge#1834]
**Name of the lexer**
The JavaScript Lexer.

**Code sample**
A sample of the code that produces the bug.

```js
  // Format return
  let ret = "";

  ret += `// ${action.Name ?? "Unk"}: ${action.Comment ?? "Just do it"}`;
  ret += "\n";
  console.log("I am wrongly formatted");
```

It also helps if you can provide a link to a code sample on [rouge.jneen.net][dingus].

http://rouge.jneen.net/v3.29.0/javascript/ICAvLyBGb3JtYXQgcmV0dXJuCiAgbGV0IHJldCA9ICIiOwoKICByZXQgKz0gYC8vICR7YWN0aW9uLk5hbWUgPz8gIlVuayJ9OiAke2FjdGlvbi5Db21tZW50ID8_ICJKdXN0IGRvIGl0In1gOwogIHJldCArPSAiXG4iOwogIGNvbnNvbGUubG9nKCJJIGFtIHdyb25nbHkgZm9ybWF0dGVkIik7Cg

**Additional context**
I encountered this issue in Gitlab. They referred me here.

[dingus]: http://rouge.jneen.net/

**Comment by tancnle** [comment]
@legacy3 could you link the GitLab issue here as well? 🙏🏼

**Comment by legacy3** [comment]
Hey, first of all looks good thanks :)

Here is the link: https://gitlab.com/gitlab-org/gitlab/-/issues/364595
