### ISSUE TITLE
PHP syntax only works with opening tag

### ISSUE THREAD

**Issue by rcrowe** [rouge-ruby/rouge#187]
I'm using `middleman-syntax` with fenced code blocks in markdown. PHP syntax highlighting only works when including `<?php`. This is inconsistent with other languages & seems unnecessary.

Ruby is rendered fine:

```ruby
def my_cool_method(message)
  puts message
end
```

But with php, you have to include `<?php` in order for the syntax highlighting to work; even though I've said parse as php.

**Broken:**

```php
$foo = new Bar;
echo $foo->name();
```

**Works:**

```php
<?php

$foo = new Bar;
echo $foo->name();
```

**Comment by alainmeier** [comment]
I'm having a similar issue, but the proposed:

    ``` php?start_inline=1
    $foo = new Bar;
    echo $foo->name();
    ```

Doesn't appear to work when you're using kramdown. Is there a global setting we can use so all PHP snippets are handled this way?

**Comment by jneen** [comment]
I'd bring this issue up with @gettalong - so long as Kramdown calls `Lexer.find_fancy(lang)` the CGI-style options should work.

**Comment by gettalong** [comment]
Yes, it does, see https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter/rouge.rb#L26

However, the parser (see https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/kramdown/codeblock.rb#L35) probably doesn't accept the additional options.

**Comment by jneen** [comment]
Ah yeah, looks like it's just looking for `\w+`.  Is this as easy as switching to `\S+` (or maybe `\w\S*`)?

**Comment by gettalong** [comment]
In theory, yes, but in practice I have to consider backwards compatibility.

Is there a way to provide the rouge lexer with options? I.e. can the option `start_inline: 1` somehow be specified when using `Lexer.find_fancy` or a similar method?

**Comment by jneen** [comment]
`find_fancy` is just a wrapper over some lower-level features with a CGI.parse added in.  `Lexer.find` and `Lexer.guess` can get you a lexer class, and the options are arguments to the initializer.

**Comment by jneen** [comment]
(fwiw, redcarpet allows this style of options in its parser, so i'd be surprised if it was forbidden by markdown standards)

**Comment by gettalong** [comment]
Alas, there is *no* Markdown standard.

I will see what I can do without breaking compatibility.

**Comment by alainmeier** [comment]
Any movement on this?

**Comment by DanielSiepmann** [comment]
Can someone open and finish this task?

**Comment by jneen** [comment]
?

**Comment by DanielSiepmann** [comment]
It's still not possible to insert PHP Code without the opening tag. At the moment I'm using ruby as language for highlighting PHP Code.
