### ISSUE TITLE
What is the new website of Rouge?

### ISSUE THREAD

**Issue by UlyssesZh** [rouge-ruby/rouge#1902]
[The old website](http://rouge.jneen.net/) cannot be accessed now.

**Comment by tancnle** [comment]
Thank you for reporting @UlyssesZh. The old website `rouge.jneen.net` was deployed on the Heroku platform. Since the Free tier has been retired, our application is no longer available. I believe @jneen is looking at hosting the site somewhere else.

**Comment by zenspider** [comment]
If you're not going to fix it, you can remove the metadata.

**Comment by tancnle** [comment]
@UlyssesZh  The web site should be up and running now at https://rouge.jneen.net/. Apology for any convenience caused.
