### ISSUE TITLE
Updating rouge on Github Pages

### ISSUE THREAD

**Issue by reifjulian** [rouge-ruby/rouge#1910]
Github Pages is still using [Rouge version 3.2.6](https://rubygems.org/gems/github-pages). I posted a [Github issue](https://github.com/github/pages-gem/issues/816) in February asking if they can update to a more recent version, but the last several updates this year still use 3.2.6. Does anyone have suggestions for how to nudge them to incorporate the latest version?

**Comment by lee-lindley** [comment]
Agree. I've worked around the GitHub pages build to generate the site files locally and probably won't go back, but it would be nice if GitHub pages got on a regular upgrade schedule. OTOH, it's free. I'm grateful it was good enough to get me started.

**Comment by tancnle** [comment]
Thanks @reifjulian. I don't think we can control when the GitHub Pages gems are updated so the ⚽ is on their court. Closing.
