### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by seshrs** [rouge-ruby/rouge#1917]
Hi! I noticed that the website appears to be down: [rouge.jneen.net/](http://rouge.jneen.net/)
Just thought I'd flag. Would be great if either the website could be fixed of if this repo removed the link to that website :)

Thanks for continuing to maintain this project ❤️

**Comment by tancnle** [comment]
Thanks for raising this, @seshrs. We need to migrate away from Heroku. Would you have any thoughts on the progress @jneen? 

This issue relates to https://github.com/rouge-ruby/rouge/issues/1902

**Comment by dunkmann00** [comment]
@tancnle @jneen Just an FYI, this was just recently announced from Heroku: [Heroku Open Source Software Credit Program](https://www.heroku.com/open-source-credit-program). It might be interesting to consider as a new solution.

**Comment by tancnle** [comment]
Thank you for letting us know @dunkmann00. This is a great idea. I will see if we can apply for the credit.

**Comment by tancnle** [comment]
Closing as duplicates https://github.com/rouge-ruby/rouge/issues/1902
