### ISSUE TITLE
gem homepage metadata is broken

### ISSUE THREAD

**Issue by zenspider** [rouge-ruby/rouge#1959]
goes to http://rouge.jneen.net which prolly died when heroku went corrupt

**Comment by jneen** [comment]
Yep, I still need to put it up on my server. Unless maybe gitlab wants to host it?

**Comment by tancnle** [comment]
Closing as duplicate of https://github.com/rouge-ruby/rouge/issues/1902

**Comment by tancnle** [comment]
> Unless maybe gitlab wants to host it?

I will check with the folks at GitLab and get back to you on this.
