### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by fingolfin** [rouge-ruby/rouge#1988]
The rogue website at http://rouge.jneen.net reports this:

> Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
      heroku logs --tail

<img width="514" alt="Screen Shot 2023-08-24 at 10 07 07" src="https://github.com/rouge-ruby/rouge/assets/241512/b10a1c23-7a17-41fc-9a10-ee7df08a8b66">

**Comment by tancnle** [comment]
@fingolfin The web site should be up and running now at https://rouge.jneen.net. Apology for any convenience caused.
