### ISSUE TITLE
`guess` with source and `guess_by_source` frequently returning PlainText lexer

### ISSUE THREAD

**Issue by depthbomb** [rouge-ruby/rouge#2028]
**Describe the bug**
Given many code strings, using `guess({ source: ... })` or `guess_by_source(...)` returns `Rouge::Lexers::PlainText`.

**To Reproduce**
```rb
# frozen_string_literal: true

require 'rouge'

code = <<~CODE
  {
    "s": "t",
    "i": 123,
    "b": true
  }
CODE

formatter = Rouge::Formatters::HTMLInline.new(Rouge::Themes::Github.new)
lexer = Rouge::Lexer.guess({ source: code }) # or Rouge::Lexer.guess_by_source(code)
output = formatter.format(lexer.lex(code))

puts lexer.title
puts output
```

**Expected behavior**
Correctly guesses the lexer to use.

**Screenshots**
_None_

**System**
 - Windows 10 22H2 (19045.4046)
 - Ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x64-mingw-ucrt]
 - Rouge 4.2.0

**Additional context**
I'm not sure if this is entirely a library bug or I'm attempting to use the code incorrectly as there wasn't much info about the usage regarding guessing by code source.

**Comment by NebulaBC** [comment]
How did you resolve this? I have looked through this project's codebase and all resources I can find and I'm still unsure why it can't manage to make even very obvious guesses? Nothing works. Why even include this function if it's not a feature. I built around this library assuming that I could assume text language.

**Comment by depthbomb** [comment]
> How did you resolve this? I have looked through this project's codebase and all resources I can find and I'm still unsure why it can't manage to make even very obvious guesses? Nothing works. Why even include this function if it's not a feature. I built around this library assuming that I could use it to guess text language.

I don't have a solution since I figured it just requires more info than the code to be able to guess the language.
