### ISSUE TITLE
Windows Batch files support

### ISSUE THREAD

**Issue by XhmikosR** [rouge-ruby/rouge#252]
This along with [Powershell](https://github.com/jneen/rouge/issues/251) are the lexers I'm personally missing in Rouge :)

**Comment by tibel** [comment]
:+1:

**Comment by dmetzler1988** [comment]
👍

**Comment by CapitanShinChan** [comment]
Is there any advance on this? My batch files are not getting any highlight. 

I almost don't know any Ruby, but can try to help to define the lexer in pseudocode.

**Comment by mat-m** [comment]
Since Rouge is used in Gitlab, it would be very cool to have syntax highlighting for batches.

See gitlab: https://gitlab.com/jjb3/HotChocolatey/blob/master/build.bat
vs github: https://github.com/chocolatey/chocolatey/blob/master/build.bat

We can help for the definition if not on the code.

**Comment by pulcov** [comment]
👍

**Comment by nussetorten** [comment]
👍

**Comment by deadlydog** [comment]
You can see [pygments batch lexer definition here](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/shell.py) for reference. I would love to see this added.

**Comment by pyrmont** [comment]
@deadlydog Thanks for the link to the Pygments batcher; that should be helpful. At this stage, we're mostly doing our best to clear through the backlog of PRs that had built up over the past few months but I'd like to eventually start looking at some of the more popular lexer requests.

In the meantime, we have [a new lexer development guide](https://www.rubydoc.info/github/rouge-ruby/rouge/master/file/docs/LexerDevelopment.md) that might be helpful for users looking to add a lexer themselves. That's always most welcome!
