### ISSUE TITLE
Implement an Obj-C lexer

### ISSUE THREAD

**Issue by jneen** [rouge-ruby/rouge#27]

**Comment by saagarjha** [comment]
Hi, apologies for commenting on a long-closed issue but I was wondering if Rouge ever got Objective-C++ support. If it did, how can I turn it on? If not, is there I anything I can do to help get this added (should I file a lexer request?) I want to put some snippets in Objective-C++ on my blog and would like that to be highlighted too :)

**Comment by pyrmont** [comment]
@saagarjha Rouge has an Objective-C lexer, it was added in version 0.5.2 so will in all likelihood be in the version you're using.

With GitHub-style code blocks that look like ` ```<some_lang> `, you can tell Rouge to use the Objective-C lexer by replacing `<some_lang>` with `objc` (or `objective_c`, `obj-c` or any of the alternatives [here](https://github.com/rouge-ruby/rouge/blob/7e04388a1222bf26ddb660778744eab82a6ea847/lib/rouge/lexers/objective_c.rb#L12)).

Hope that helps!

**Comment by saagarjha** [comment]
Right, that's what I'm using now. But that one doesn't "get" C++ like an actual Objective-C++ lexer would, so it leaves large blocks of my code unhighlighted.

**Comment by pyrmont** [comment]
Oh sorry—I didn't catch that it was Objective-C++. I'm afraid no, we don't have a lexer for that. You can look at how the Objective-C lexer is implemented if you'd like to try making an Objective-C++ lexer.

**Comment by saagarjha** [comment]
So I took a look and it looks like there's some sort of ["`load_lexer`" functionality](https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/lexers/objective_c.rb#L6)? Could we implement this with an e.g. "_objective_c.rb" that contains all the Objective-C stuff, then an "objective_c.rb" that includes "c.rb" an "_objective_c.rb", while "objective_cpp.rb" includes "cpp.rb" and "_objective_c.rb"?

**Comment by jneen** [comment]
It's possible - it has a lot of room for bugs though. See sass/scss, which both extend from css, for an example.

**Comment by jneen** [comment]
I'm actually astounded that such a language exists, and that somebody took the time to write a parser for it to be honest.

**Comment by saagarjha** [comment]
Hey, once you have one C++ parser, you try to get as much milage out of it as you can ;) I'll take a look at factoring out the Objective-C parts and see how it works out.

**Comment by jneen** [comment]
Another example worth looking at is TSX, a combination of typescript and JSX, which are both extensions of javascript.

**Comment by saagarjha** [comment]
Hmm, so I'm having some difficulty with subclassing, and I unfortunately don't know Ruby well enough to figure it out. AFAIK Ruby doesn't do multiple inheritance, so what I'm trying to do is have `ObjectiveC` subclass `C`, and `ObjectiveCpp` subclass `Cpp`, but put all the common parsing stuff in `ObjectiveCCommon` (which inherits from `Lexer`. But unlike `TSX` the common parser has state-related stuff in it that it needs to get from `C`, so I can't just load it like `TSX` does. Any ideas on how to approach this? Is there a way to include code from a module without trying to execute it, or inside the correct scope so it can use the surrounding state information?

**Comment by jneen** [comment]
Yes, since there is no multiple inheritance, you will need to move existing code around in order to implement this. Look into how `TypescriptCommon` does it, as well as the `self.inherited` hook that Ruby provides to modules.

**Comment by pyrmont** [comment]
@saagarjha I suggest you move this into a new issue or (better yet) a PR; this isn't really related to the original issue.

**Comment by saagarjha** [comment]
Thanks for the help; I filed #1378 with a rough attempt at getting this to work.
