### ISSUE TITLE
Rust Lexer Problem

### ISSUE THREAD

**Issue by HarryLovesCode** [rouge-ruby/rouge#287]
Hello,
I was trying out Rust on the [Rouge website](http://rouge.jneen.net/pastes/X1b) and I noticed some peculiar highlighting of slashes. Here's what it looks like on my computer...

<img width="1054" alt="screen shot 2015-07-15 at 8 44 30 pm" src="https://cloud.githubusercontent.com/assets/12660259/8713079/5fd903e8-2b32-11e5-9a9a-9ae3e29b0d11.png">

Here's how the same snippet is highlighted on the Rust website...

<img width="539" alt="screen shot 2015-07-15 at 8 45 37 pm" src="https://cloud.githubusercontent.com/assets/12660259/8713088/89bb10de-2b32-11e5-89b8-8ec40b6ac737.png">

If you could point me in the right direction, I might be able to help, but Ruby isn't exactly my thing...

---

Current issues:
- [x] String escapes not working with double quotes
- [x] `/=` Operating not highlighting correctly
- [x] Attributes should be highlighted as a preprocessor and not highlighted as a function (similar to C)
- [x] Preprocessor commands on the first line should not be highlighted as an error
- [x] Underscores are **not** ignored in numbers like they should be (similar to Ruby).
- [ ] The `..` range syntax

**Comment by jneen** [comment]
Hi @HarryLovesCode! Thanks for the bug report. I might get around to it in the next few months but I'm very busy these days, so if you could take a look at it that'd be great.  Fortunately, rouge lexers are mostly regexes and rouge DSL and not a whole lot of ruby. You'll find the rust lexer in `lib/rouge/lexers/rust.rb`, and there's a guide on getting set up [in the wiki](https://github.com/jneen/rouge/wiki/Setting-up-Ruby)
