### ISSUE TITLE
Missing support for JavaScript's new interpolation syntax

### ISSUE THREAD

**Issue by marlonbernardes** [rouge-ruby/rouge#289]
Rouge does not yet support JavaScript string interpolation. In order to use string interpolation in JavaScript, we need to wrap our strings using backticks, like so:

``` js
var id = 'rouge';
var html = `<input id="${id}" type="text">`;
```

Currently rouge only supports strings created using single or double quotes.

**Comment by morkro** [comment]
Would also love to see this added :+1:

**Comment by lucasfcosta** [comment]
This would be great.

**Comment by miparnisari** [comment]
@pyrmont I this can be closed since the code for it is here: https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/lexers/javascript.rb#L269

![image](https://user-images.githubusercontent.com/5374887/58744614-fc082b80-83f9-11e9-9243-5faf015a6847.png)

**Comment by pyrmont** [comment]
Yep, agreed :)
