### ISSUE TITLE
Liquid support

### ISSUE THREAD

**Issue by robbyklein** [rouge-ruby/rouge#294]
Hey guys, love the gem. By far the best syntax highlighting gem (I tried them all). Would be awesome if you added support for [Liquid templating](http://liquidmarkup.org/).

**Comment by Arcovion** [comment]
It's already supported since `1.8.0`:
https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/liquid.rb#L7

**Comment by miparnisari** [comment]
@pyrmont can you close this?
