### ISSUE TITLE
Livescript support

### ISSUE THREAD

**Issue by wolfflow** [rouge-ruby/rouge#309]
[Livescript](http://livescript.net) is a language which compiles to JavaScript. It has a straightforward mapping to JavaScript and allows you to write expressive code devoid of repetitive boilerplate. While LiveScript adds many features to assist in functional style programming, it also has many improvements for object oriented and imperative programming.

**Comment by pyrmont** [comment]
This is being addressed by #650. I'm afraid we're behind in getting through the PRs but [we are making progress](https://github.com/rouge-ruby/rouge/commits/master).
