### ISSUE TITLE
Saltstack related file support

### ISSUE THREAD

**Issue by zyio** [rouge-ruby/rouge#318]
Support for the '.sls' and jinja-flavoured-yaml '.j2' files commonly used in saltstack would be appreciated.

Similar to the following pygments lexer: 
http://pygments.org/docs/lexers/#pygments.lexers.templates.YamlJinjaLexer

**Comment by Xiol** [comment]
+1

**Comment by aditaa** [comment]
+1

**Comment by vitalyisaev2** [comment]
+1

Lacking this on Gitlab

**Comment by blaketmiller** [comment]
+1

**Comment by jneen** [comment]
Unfortunately there's no mechanism to add file extension support for this yet, but have you considered trying `jinja?parent=yaml`?

In GitLab, you would use

``` bash
echo '*.sls gitlab-language=jinja?parent=yaml
```
