### ISSUE TITLE
Javascript Lexer does not recognize a literal object as first element

### ISSUE THREAD

**Issue by KuttKatrea** [rouge-ruby/rouge#322]
When you have a literal object at the beginning of a block/file its not recognized, but if you include first a comment it will be recognized just fine.

**Comment by jneen** [comment]
This is intended behavior. Curly braces in statement position are blocks, not objects.  `{a: 1}` is a syntax error in statement position in javascript.

**Comment by KuttKatrea** [comment]
I've been investigating and you are right, but there is still a bug, that if you do:

~~~js
// Comment
{a: 1}
~~~

Then ´{a:1}´ will be recognized as an object just fine, which then its an error because it's still in a statement position.

**Comment by jneen** [comment]
You're right, that is odd. Hrm :\
