### ISSUE TITLE
php hilight, strings with objects in

### ISSUE THREAD

**Issue by puggan** [rouge-ruby/rouge#338]
When using objects in string, the hilight gets bad afterwarrds.

exemple code, works fine in github:

``` php
<?php
if($deleted)
{
    // Tell the user how many products was deleted
    $repsons_html .= "Deleted products = {$deleted} {$user->lang['ITEMS']}<br />";
}
// This comment should be gray(.c1), not green(.s2)
```

not so fine in your hilight:
http://rouge.jneen.net/pastes/xvW

(image of exemple code, for reference after the bug is fixed)
https://gitlab.com/gitlab-org/gitlab-ce/uploads/96de50a29812972e78f10ea8b952283b/gitlab_hilight_error_php_issue_3375.png

**Comment by jneen** [comment]
Thanks for the report @puggan! I'll try and find some time to look at it.

**Comment by jfse** [comment]
Just want to point out that it does not need to be attached to an object to result in an error (though of course, it could be separate issues)
For example, the code below will result in the string being terminated at the last single quote
```
<?php
$string = "{$array['index']}"
```

**Comment by puggan** [comment]
Looks like it's solved already.
