### ISSUE TITLE
Extend Visual Basic filenames

### ISSUE THREAD

**Issue by robodude666** [rouge-ruby/rouge#340]
The Visual Basic Lexer currently included only recognizes VBScript (_.vbs) and VB.NET (_.vb) file extensions. 

It would be great if `*.bas` and `*.cls` extensions were also recognized in order to support Visual Basic 6 and Visual Basic for Application.

**Comment by klmr** [comment]
It may be a better idea to provide a completely different lexer for those (and potentially merge `*.vbs` into it) since VB6 and VB.NET are quite different languages (even on the syntax level).
