### ISSUE TITLE
Nix support

### ISSUE THREAD

**Issue by phunehehe** [rouge-ruby/rouge#345]
I may be able to open a PR later on, but want to open an issue before I forget.
It's like this in Pygments https://bitbucket.org/birkenfeld/pygments-main/pull-requests/267/add-nix-language-lexer/diff.

**Comment by sjmackenzie** [comment]
@phunehehe Oh I would love to see your merge request opened! It's quite nasty reading nix files on gitlab! :beers:

**Comment by pyrmont** [comment]
It looks like Nix support was subsequently added to Rouge. Please let us know if there are any problems with its implementation.
