### ISSUE TITLE
Matlab files without comments don't get highlighted

### ISSUE THREAD

**Issue by stanhu** [rouge-ruby/rouge#346]
In the [example here](https://gitlab.com/kelvinmutuma/matlab_test/blob/master/test.m), calling `Rouge::Lexer.guess('test.m')` resolves to the `PlainText` lexer. Here's what's happening:
1. *.m files can be interpreted either as Matlab or Objective C.
2. Rouge runs `analyze_text` on the file to resolve the ambiguity. For the Matlab case, it's scanning for comments. In the Objective C case, it's scanning for some keywords (e.g. `implementation`, `protocol`, etc.).
3. Since the example above contains neither, it chooses the `PlainText` lexer.

Is there a way to improve  `analyze_text` in the Matlab lexer so that it does a better job resolving this ambiguity? I suppose [Pygments doesn't do a much better job](https://bitbucket.org/birkenfeld/pygments-main/src/f114940f5aeb4775eef157e7089f462b49bdc127/pygments/lexers/matlab.py?at=default&fileviewer=file-view-default#matlab.py-136) either.

**Comment by jneen** [comment]
Yeah, this is a tricky one, and I'm not sure how to approach it. I would suggest some kind of `% language: matlab` comment be added in these cases, but then the file would already have a comment!

In a system like GitLab, I'd potentially suggest a user-facing selector that a) indicates the current highlighted language, and b) allows the user to specify a different one.

**Comment by robin850** [comment]
Just my two cents : maybe you could try to infer that the current file is a Matlab one like you'd with Objective-C, through keywords ; I think there are keywords/instructions that are specific enough to Matlab like `clear all`, `close all`, `clc`, `plot`, or `(x|y)label`.
