### ISSUE TITLE
Using "apache" syntax highlighting corrupts the output

### ISSUE THREAD

**Issue by m47z0r** [rouge-ruby/rouge#350]
What should look like this:

``` apache
<Location /srv/bla>
    #Enable Subversion
    DAV svn
    AuthType Basic
    AuthBasicProvider ldap
    Require valid-user
</Location>
```

..., is becoming this:

``` apache
<Location /srv/bla>
    #Enable Subversion
     svn
    AuthType Basic
     ldap
    Require valid-user
</Location>
```

As you can see, some words are just cut off instead of being highlighted.

See also:
- http://rouge.jneen.net/pastes/qO3
- https://github.com/gitlabhq/gitlabhq/issues/9896

**Comment by julp** [comment]
Hi,

this issue was already reported by #246 and #300

It should be fixed by #301 in next release.

**Comment by miparnisari** [comment]
Looks fine to me now.

![image](https://user-images.githubusercontent.com/5374887/58744654-73d65600-83fa-11e9-8dec-3653859cf435.png)

**Comment by pyrmont** [comment]
Thanks!
