### ISSUE TITLE
`http` lexer requires first line to be http request method and path

### ISSUE THREAD

**Issue by uberfuzzy** [rouge-ruby/rouge#373]
Hi, I was trying to use the `http` language to style up some blocks of HTTP headers in a tutorial, but I noticed too late that it only works when the first line matches a HTTP method verb and a path (aka, the opening http request). The after-header response body lines seems to be optional, but not that opening request line.

My ruby skills are far too newbie to even know where to start to fix this, and my project cant wait for an updated package to work its way through the gem tubes, but I thought I'd at least drop a line about it, and hope for the future.

this was using v1.10.1 with jekyll 3.0.1 if it matters
http://rouge.jneen.net/pastes/QGl

**Comment by jneen** [comment]
...the HTTP spec requires this too, iirc.  Is this a feature request?

**Comment by uberfuzzy** [comment]
I guess it is a feature request, to be able to syntax highlight just http headers, and not a full http request.
So the above link would be colored like such, http://rouge.jneen.net/pastes/ZMX (just sans line 1)
With the headers in `na`, and the values in `s`.
