### ISSUE TITLE
Tiny bug in scala lexer

### ISSUE THREAD

**Issue by htch** [rouge-ruby/rouge#374]
Stumbled upon a small wart in scala lexer: it treats closing parenthesis as a part of a preceding scala symbol, for example in this code sample:

```
StorageState.table(StorageState.NewUsers()).format(
  keyParams('app_id).asInstanceOf[String],
  keyParams('platform).asInstanceOf[String],
  keyParams('version).asInstanceOf[String],
  keyParams('scale).asInstanceOf[String],
  formattedToday
)
```

Relevant [screenshot of the same code](http://i.imgur.com/frldlRd.png) from gitlab that relies on rouge for its syntax highlighting and a [paste](http://rouge.jneen.net/pastes/opp) in the rouge pastebin.

**Comment by anthony-cros** [comment]
This is still an issue as of today (the closing brackets is colored improperly), at least as used from Jekyll

**Comment by pyrmont** [comment]
Pretty sure the `[^']` is the bug:

https://github.com/rouge-ruby/rouge/blob/20da6514cbeab9fd2a10c3ea6ee47f4686a934af/lib/rouge/lexers/scala.rb#L43

I'm guessing that it's there to avoid matching against single-quoted strings but should probably be a negative lookahead.
