### ISSUE TITLE
Support Hack (PHP-like)

### ISSUE THREAD

**Issue by fredemmott** [rouge-ruby/rouge#392]
_most_ files would work simply by pretending '<?hh' files are PHP - there is some extra syntax though, that would be good to also support:
# XHP (XML-like literals)

``` Hack
$foo = <div class={$bar}>{$baz}</div>;

class :myclass extends :x:element {
  attribute string myattr @required;
/* ... */
}

$herp = <myclass myattr="myvalue" />;
```

More info: https://docs.hhvm.com/hack/XHP/introduction
# Collection object literals

``` Hack
$foo = Vector { 'herp', 'derp' };
$bar = Map { 'herp' => 'derp' };
```

https://docs.hhvm.com/hack/collections/introduction
# Short lambdas

``` Hack
$square_func = $x ==> $x * $x;
var_dump($square_func(2)); // outputs 4

$two_args = ($x, $y) ==> $x + $y;
```
# nullable

``` Hack
function foo(?MyClass $my_class_or_null) {
}
```
# callable types

``` Hack
function do_stuff((function(int $x): string) $callback) {
 // callback() takes an int and returns a string
```
# Generics

https://docs.hhvm.com/hack/generics/introduction

``` Hack

class Foo<T> { ... }
```
# async/await

There's a lot of these: pretty much needs the whole section going through: https://docs.hhvm.com/hack/async/introduction

**Comment by pyrmont** [comment]
Support for Hack has subsequently been added to Rouge. If there are any issues with the implementation, please let us know!
