### ISSUE TITLE
Small improvement for YAML highlighting, big leap for readability [Feature Request]

### ISSUE THREAD

**Issue by do11** [rouge-ruby/rouge#393]
(Excuse me for not knowing thoroughly how Rouge works. If I know that good, I would probably create pull request instead of feature request.) :bow:

Currently, it seems, when Rouge highlight YAML text, it assumes that almost everything in YAML is strings (except comments and punctuation) so highlighting become _single color everywhere_ style. Because of this, in GitLab (in default white theme) almost a whole YAML text is bright red (and comments are gray). I think, highlighting YAML by string/code logic is not that useful, because almost everything in yaml isn't code, but strings.

I request change to be made in lexer, to make YAML highlighting more informative, and at least distinguish _hash keys_ from other strings. It could be similar to how GitHub do, example: https://github.com/geerlingguy/ansible-for-devops/blob/master/drupal/provisioning/playbook.yml - keys are green, strings are blue. For example it could be like currently Rouge highlights non-quoted hash keys in javascript or json keys. :pray:

Example of current _single color everywhere_ YAML highlighting: https://gitlab.com/thestage/bedrock-ansible/blob/faa6914c65cdfbe032852a5478fd7c74aacb499f/roles/wordpress-sites/tasks/main.yml

Much more readable JSON highlight: https://gitlab.com/tylert/packer-build/blob/35278680e3645f7050ab9ca2b9644ede35801303/template/trusty.json

---

Just for reference, this feature request is related to GitLab feature request [issue:13258](https://gitlab.com/gitlab-org/gitlab-ce/issues/13258).

**Comment by sanderson** [comment]
Looks like this is already on @jneen's todo list - issue #38. May want to bump there.

**Comment by jneen** [comment]
YAML is a notoriously complicated language to highlight correctly. I will bump this up on my list of things to take care of.

**Comment by sanderson** [comment]
Yeah, it is. GitHub does a pretty good job, but I don't know which lever they're using. The biggest thing for me would just be highlighting keys differently than their values/arrays.

**Comment by stanhu** [comment]
+1 for highlighting keys/values.

**Comment by mrzool** [comment]
See also: #341
