### ISSUE TITLE
C++ support has some bugs

### ISSUE THREAD

**Issue by tcbrindle** [rouge-ruby/rouge#394]
I've just switched to using Rouge (from Pygments) for my Jekyll blog as encouraged by Github, and I've noticed a couple of bugs in the highlighting of C++:
- Many [C++ keywords](http://en.cppreference.com/w/cpp/keyword) seem to be unrecognised. In particular, anything added in C++11 such as `constexpr` or `decltype` is absent, as is `bool` (which has existed for as long as C++).
- A couple of [C99 keywords](http://en.cppreference.com/w/c/keyword), such as `_Bool` and `_Complex` are erroneously highlighted as C++ keywords -- strictly speaking, these are not valid. (Not a particularly big deal but mentioned for completeness)
- The `class` and `struct` keywords in C++ have almost-identical meaning, but the snippet
  
  ``` cpp
  class example1 {};
  struct example2 {};
  ```
  
  when highlighted by Rouge has `example1` coloured, but`example2` not.
- Similarly, given the snippet
  
  ``` cpp
  template <typename Type, class Class>
  struct example {};
  ```
  
  the keywords `typename` and `class` have identical meaning in this context; however, Rouge highlights `Class` but not `Type` (and in fact Github's highlighter appears to have the same bug).

I'm afraid I've never written a line of Ruby in my life so I don't have a clue where to start when it comes to fixing these, but hopefully someone else reading this might do :-)

**Comment by tcbrindle** [comment]
Also, the rarely-used `compl` keyword is highlighted as a type (like `int` or `float`), whereas in fact it's an alternative to the `~` bitwise-complement operator.

**Comment by tcbrindle** [comment]
Current Rouge support for C++ keywords can be seen here:

http://rouge.jneen.net/pastes/OY4

**Comment by jneen** [comment]
Hi @tcbrindle, we've merged a couple of PRs adding more keywords and some other features - could you re-check which parts of this issue are still an issue?

Thanks!

**Comment by rongjiecomputer** [comment]
Variadic template does work too http://rouge.jneen.net/pastes/5xmP

**Comment by jneen** [comment]
Our support for C++11/14 is limited - we have had a few pull requests to add specific pieces of it, but nobody has sat down and attempted to support the entirety of the specs yet.

**Comment by jneen** [comment]
If you'd like to help, simply adding examples to the stress-test file (`spec/visual/samples/cpp`) would help immensely.

**Comment by rongjiecomputer** [comment]
I made a PR in #565!

**Comment by kaiywen** [comment]
Found some other bugs or unfriendly highlighting problems in c++ codes:

1. Function definitions with keyword "const" would not be highlighted with particular color. e.g. `int getArea() const { return area; }` has `getArea` colored while `int getArea() {return area; }` not;

2. Function names would not be highlighted if defined out of the class declaration. Such as, for function `int Rectangle::getArea() {return area;}`, the name `getArea` would not be colored. 

Hopefully they can be fixed.

**Comment by integricho** [comment]
The struct / class coloring issue is still relevant, specifically, struct names are not colored the same as class names.

**Comment by pyrmont** [comment]
It was a little difficult to track what has and hasn't been fixed in this issue so I've filed a separate report for the struct/class/typename issue.

If there are any others still outstanding, please feel free to file fresh issues for those as well.
