### ISSUE TITLE
Swift Keywords Highlighting Outside of “Particular Contexts”

### ISSUE THREAD

**Issue by SlaunchaMan** [rouge-ruby/rouge#403]
Some keywords in Swift, such as `left` and `right`, are only keywords inside of [certain contexts](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html):

> Keywords reserved in particular contexts: `associativity`, `convenience`, `dynamic`, `didSet`, `final`, `get`, `infix`, `indirect`, `lazy`, `left`, `mutating`, `none`, `nonmutating`, `optional`, `override`, `postfix`, `precedence`, `prefix`, `Protocol`, `required`, `right`, `set`, `Type`, `unowned`, `weak`, and `willSet`. Outside the context in which they appear in the grammar, they can be used as identifiers.

In particular, I have a Swift struct with a member called `left` and it’s highlighting as a keyword.

**Comment by reitzig** [comment]
Related: keywords are allowed as parameter labels. Currently, rouge highlights such labels as keywords.
