### ISSUE TITLE
Bug [javascript]: `\uXXXX` sequences not supported in strings and regular expressions

### ISSUE THREAD

**Issue by stepmuel** [rouge-ruby/rouge#408]
While Pygments highlights regular expressions in JavaScript with a single color, Rouge tries to do code highlighting inside regular expressions. 

``` javascript
str.replace(/([a-z])([A-Z])/g, "$1\u200B$2");
str.replace(/\u200B/g, "<wbr>");
```

The highlighter fails in some cases (e.g. unicode characters written in hex), and is more distracting than helpful in many cases due to the dense nature of regular expressions. Highlighting the entire expression in a single color, like Pygments does, would lead to more readable results.

**Comment by jneen** [comment]
Hi @stepmuel, I'm happy to fix the `\u....` syntax, but unfortunately we are going to continue highlighting within regular expressions.
