### ISSUE TITLE
Support for EEX (embedded Elixir templates)

### ISSUE THREAD

**Issue by sevenseacat** [rouge-ruby/rouge#412]
Like ERB embeds Ruby in HTML templates, EEX embeds Elixir in HTML templates. It should be pretty straightforward to copy and adapt the ERB lexer...?

(I may take a look at this myself)

**Comment by jneen** [comment]
Yes, this would be wonderful. There is a TemplateLexer class to make using a parent lexer more convenient.

**Comment by elvio** [comment]
Is there any update on it?

**Comment by pyrmont** [comment]
Sorry, this issue has an associated PR. It shouldn't have been marked as stale. That's been fixed.
