### ISSUE TITLE
Preview existing themes

### ISSUE THREAD

**Issue by alexconst** [rouge-ruby/rouge#418]
Is there any way to preview existing color schemes?
I guess this is more of a documentation/website issue. But it would be nice to have.

FWIW I'm using Rouge via Github Pages.

Thanks

BTW, does Rouge also set the background on its own or is this the responsibility of a third party (like Jekyll)?
This results in broken themes, where the text is either very hard to read or an annoying whitespace selection highlight type of effect manifest itself.

_just wondering if this is a bug with Jekyll or Rouge_ :p

**Comment by alexconst** [comment]
I'm guessing this is related to the "background selection highlight".
Is there any way to disable it?
![](https://i.imgur.com/5zTGacJ.png)

**Comment by jneen** [comment]
The specific coloring or visual properties of the highlighted text is the responsibility of whoever created your stylesheet. I don't believe any of the rouge themes have this behavior.
