### ISSUE TITLE
A notranslate HTML5 class should be added to highlighted segments

### ISSUE THREAD

**Issue by tomball** [rouge-ruby/rouge#429]
Our site uses GitHub Pages, and our docs have lots of code segments using both back-ticks (`foo`) and 4-space indention. However, we support using Google Translate with our docs, and those code blocks were also getting translated, with sometimes hilarious results. HTML5 supports translation disabling per element, by adding a "notranslate" class to the element. If Rouge adds this class to the segments it creates when highlighting, then HTML files generated using it can be translated more accurately.

As a workaround, on our site we now [add that class dynamically when a page loads](https://github.com/google/j2objc/commit/d67cc0924e65e2311ce1ee3c89912043658e07d5#diff-822e9cf54ee310f9a7ebd0d16c9ae066). If you go to our [Getting Started page](http://j2objc.org/docs/Getting-Started.html) and select a language like Chinese from the Select Language dropdown menu at the bottom, you'll see that the Rouge-formatted sections are no longer translated.

**Comment by jneen** [comment]
Hi @tomball, I can suggest two fixes:

a) wait for rouge 2.0 which will allow you much more fine-grained control over HTML formatting.
b) surround your code snippets with an additional div with your desired class.
