### ISSUE TITLE
JavaScript syntax highlighting

### ISSUE THREAD

**Issue by Nipher** [rouge-ruby/rouge#434]
When writing javascript, there are many `nx` classes,
what do you guys think about changing that to something like ruby highlighting?

Example:
With rouge, when writing this:

``` javascript
function test (param) {
  console.log(param);
}
```

I get this:

``` html
<pre class="highlight">
  <code>
    <span class="kd">function</span>
    <span class="nx">test</span>
    <span class="p">(</span>
    <span class="nx">param</span>
    <span class="p">)</span>
    <span class="p">{</span>
    <span class="nx">console</span>
    <span class="p">.</span>
    <span class="nx">log</span>
    <span class="p">(</span>
    <span class="nx">param</span>
    <span class="p">);</span>
    <span class="p">}</span>
  </code>
</pre>
```

(A lot of `classes="nx"`)

Couldn't we get something like this:

``` html
<pre class="highlight">
  <code>
    <span class="kd">function</span>
    <span class="nf">test</span>
    <span class="p">(</span>
    <span class="nb">param</span>
    <span class="p">)</span>
    <span class="p">{</span>
    <span class="n">console</span>
    <span class="p">.</span>
    <span class="nf">log</span>
    <span class="p">(</span>
    <span class="n">param</span>
    <span class="p">);</span>
    <span class="p">}</span>
  </code>
</pre>
```

The function name would become `nf` the param would become `nb`
Something like that

**Comment by jneen** [comment]
That would be alright with me, although potentially difficult. The original decision was made because JS doesn't have the same variable / method distinction that Ruby does, but I could be persuaded otherwise.

**Comment by nwalton3** [comment]
+1 for more nuanced JS highlighting. I'd love for it to look more like Sublime text or [Google's prettify](https://github.com/google/code-prettify) syntax highlighter.

I'd be happy to contribute.

**Comment by gauntface** [comment]
Just started to use Rouge and would be very much in favor of this. Comparing Rouge and Prism, Prism gives more granularity.

**Comment by jneen** [comment]
Please have a go at it, @nwalton3!
