### ISSUE TITLE
Support for postrgesql-console

### ISSUE THREAD

**Issue by ioguix** [rouge-ruby/rouge#437]
Hello,

Just wanted to report an incompatibility with Pygments as Github is dropping support for pygments with Rouge as a "drop-in" replacement (as they wrote in their public announce).

Currently, Rouge do not support syntaxe highlighting for people using `portgresql-console` (or its alias `psql`) with pygments.

Regards,

**Comment by jneen** [comment]
Hi @ioguix! Writing lexers takes a good amount of work, and Pygments has a *lot* of them. Rouge is a drop-in replacement in that it can output HTML that conforms to stylesheets already written for Pygments, but it certainly doesn't lex code in the same way or support all the same languages.

If you'd like to port the `postgresql-console` lexer, I'd be happy to take a look.

**Comment by ioguix** [comment]
Hi @jneen,

Oh, ok, I have a better understanding of the drop-in replacement signification :)

Well, I would be happy to contribute but:
  - I have no ruby experience
  - I have no time to dig in a new project :(

Thank you for your answer!

Cheers,
