### ISSUE TITLE
Support for Django Templating Language

### ISSUE THREAD

**Issue by pawamoy** [rouge-ruby/rouge#440]
Hi,

When I was using Jekyll 2.2.0, I was able to highlight Django with `html+django`. Upgrading to Jekyll 3.1.2 to better match Github's version, I noticed that Django code was not highlighted anymore :sob:. Looking at [the list of supported languages](https://github.com/jneen/rouge/wiki/list-of-supported-languages-and-lexers), I can't find Django nor Jinja :cry:.

Are you planning to add support for DTL or Jinja in the future?

**Comment by minddust** [comment]
+1

**Comment by jneen** [comment]
Hi @Pawamoy. Have you tried using the liquid lexer? I seem to remember it being rather similar.

**Comment by Pawamoy** [comment]
Yes @jneen, I am using the `liquid` lexer in the few cases for which I just have DTL/Jinja code and no HTML. DTL is almost always a mix of liquid-like and HTML code. Using `liquid` does not highlight HTML :disappointed:

**Comment by jneen** [comment]
Ah, well that's a bug then. The liquid lexer should support HTML on the outside. If liquid was properly a template lexer and you could get your HTML *and* liquid together, would that solve your use case?

**Comment by Pawamoy** [comment]
Well, I think that if liquid lexer also highlights HTML, then it's similar to what erb is doing. I think some DTL template tags would still not be recognized. In that case it would change nothing for my use case :hamster:

**Comment by jneen** [comment]
Can you give an example of what would not be recognized?

**Comment by Pawamoy** [comment]
Things like

- `{% block content %}`
- `"{{ tuple.country }}"`
- `"{% trans "Number of patients per country" %}"`

**Comment by jneen** [comment]
Ah, okay. Ideally the liquid lexer would recognize those as well. I've got it on my list of things to do to untangle liquid / jinja / twig / dtl.

**Comment by Pawamoy** [comment]
Any update on this 😃 ?

**Comment by pyrmont** [comment]
The Jinja lexer was subsequently added to Rouge. Please let us know if there are any problems with it!
