### ISSUE TITLE
Support for API Blueprint

### ISSUE THREAD

**Issue by EpocDotFr** [rouge-ruby/rouge#445]
Hello!

It would be great to add syntax highlighting for the [API Blueprint](https://apiblueprint.org/) syntax. Or maybe at least add the `.apib` files in the Markdown syntax group.

PS: this is a cross post from [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/15014)

**Comment by jneen** [comment]
I'm happy to simply specify that `.apib` is Markdown, if that's good enough for now.

**Comment by pyrmont** [comment]
This was subsequently added to Rouge. Please let us know if there are any issues with its implementation!
