### ISSUE TITLE
Support for Protocol Buffers

### ISSUE THREAD

**Issue by bestouff** [rouge-ruby/rouge#446]
Helloo Rouge guys !

Would it be possible to have support for [Protocol Buffer](https://developers.google.com/protocol-buffers/) ? It's a quite simple language for binary XML-like data exchange.

**Comment by jneen** [comment]
Yes, that would be awesome.

**Comment by pyrmont** [comment]
This was subsequently added to Rouge. Let us know if there's any issues with it's current implementation!
