### ISSUE TITLE
rust code highlighting error

### ISSUE THREAD

**Issue by kernelmachine** [rouge-ruby/rouge#456]
single quotes (ie apostrophes) and hash signs are incorrectly highlighted red, e.g. 

http://rouge.jneen.net/pastes/eAMb

**Comment by theindigamer** [comment]
The hash sign part has been discussed here: https://github.com/jneen/rouge/issues/287

> Preprocessor commands on the first line should not be highlighted as an error

There is a pull request fixing some issues: https://github.com/jneen/rouge/pull/452

**Comment by pyrmont** [comment]
Sorry, this shouldn't have been marked as stale given the existing PR. Will be getting to this one as we work our way through the backlog >_<

**Comment by hugopeixoto** [comment]
The linked paste seems to highlight properly, so I think this is already fixed. The issues in the linked PR have been merged.

**Comment by pyrmont** [comment]
@hugopeixoto Thanks for the report! Will close this now.
