### ISSUE TITLE
Improve `Makefile` syntax highlighting

### ISSUE THREAD

**Issue by dblessing** [rouge-ruby/rouge#464]
Makefile syntax highlighting seems to have trouble with some things. Take this `ifeq` example. Can this be improved?

![screen shot 2016-05-10 at 2 20 51 pm](https://cloud.githubusercontent.com/assets/2394772/15159473/8c0b64fa-16ba-11e6-8adc-ef5ce65b9f72.png)

**Comment by dblessing** [comment]
cc/ @bluegod

**Comment by bluegod** [comment]
Thanks for the ping @dblessing - I'll have a look soon
