### ISSUE TITLE
Support for Elm

### ISSUE THREAD

**Issue by jaapz** [rouge-ruby/rouge#472]
Would be great to have support for Elm, a functional programming language for the browser.
http://elm-lang.org

There already are highlighting plugins for Vim, Atom and other text editors.

**Comment by jneen** [comment]
Yes! I would love to support Elm.

**Comment by Anahkiasen** [comment]
Any news o,n this one?

**Comment by jneen** [comment]
Still working through the above PR, thanks for the bump though.

**Comment by Anahkiasen** [comment]
Oh! I didn't see the referenced PR, nice!

**Comment by phaazon** [comment]
Any news? Is there a way to help? I’m really looking forward that to happen!

**Comment by Janiczek** [comment]
I'd also like to bump this one. Thank you for your work!

**Comment by ashishsc** [comment]
I'd love this as well! Thank you for your work!

**Comment by antonpaisov** [comment]
looks like elm support is a part of 3.0 release, but I can't seem to make it work 🤔

**Comment by antonpaisov** [comment]
btw, works from master.

**Comment by pyrmont** [comment]
Elm was subsequently added to Rouge. If there are any bugs in its implementation, please let us know!
