### ISSUE TITLE
How to turn off backslash highlighting for INI-file?

### ISSUE THREAD

**Issue by aka-demik** [rouge-ruby/rouge#474]
Is there a way to turn off backslash highlighting for INI-file?
[my test case](http://rouge.jneen.net/pastes/4jaX)
Thanks!

PS
I use rouge in [asciidoctor](http://asciidoctor.org/).

**Comment by jneen** [comment]
Hi @aka-demik. This could be exposed via a lexer option - asciidoctor would have to expose that option to you, though.

**Comment by aka-demik** [comment]
Asciidoctor began to develop slowly. :(
[#1040](https://github.com/asciidoctor/asciidoctor/issues/1040) - It is already two years ago. Documentation still does not even mention rouge.
But I create [issue](https://github.com/asciidoctor/asciidoctor/issues/1785) for this.
