### ISSUE TITLE
Wrong filetype detection for IDL files with .pro extension

### ISSUE THREAD

**Issue by malteger** [rouge-ruby/rouge#506]
As a follow up for #395, IDL files with .pro extensions are currently highlighted as Prolog.

My knowledge of ruby is non existent, so is there a chance anyone else can improve the guessing with the new guessing infrastructure introduced lately? Or is there an example on how to do this guessing for another language in this repo? Then I would try to fix this myself.

**Comment by jneen** [comment]
Hi @malteger,

Is there some signifier in IDL (like a `#lang IDL` declaration or similar) that will allow us to differentiate the two?

**Comment by malteger** [comment]
No, that is the problem. I had a look at pygments at how they handled this, they used the extension multiple times and checked the mimetype. The problem is: I do not know how they determine these mimetypes, for me the source files just yield `text/plain` as a mimetype.

A difference I spotted between prolog and IDL: prolog programs may have a lot more parantheses, though I have no knowledge in Prolog and just some very basic in IDL.

**Comment by malteger** [comment]
At a closer look I figured out that `pygments` checks for `:-` in prolog files with weight `1.0`. This check is done also in rouge, but with a `0.1` weight. Maybe this helps.

**Comment by jneen** [comment]
1.0 is... not appropriate for that check. 1.0 is for things like shebangs or `#lang` declarations.

If it helps for the GitLab case, we've just merged [a feature](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4606) that will allow you to override the selection in your project.

**Comment by malteger** [comment]
While we can work around this issue with the mentioned merge request in gitlab, it would certainly nice if this would work out of the box without specifying the language. I will talk to some colleagues with more IDL knowledge tomorrow, maybe we can figure out a way to safely identify IDL source code.

In the context of GitLab: It recognises the language of the project correctly as IDL, so there also seems to be some filetype guessing.

**Comment by jneen** [comment]
That guessing uses Linguist, which has some other kinds of heuristics, and is also Very Slow.
