### ISSUE TITLE
Rails 5.0 breaks the way `rouge(text, language)` renders in ERB files

### ISSUE THREAD

**Issue by marcamillion** [rouge-ruby/rouge#511]
Everything was working with all versions of Rails 5 before the official 5.0 release.

I believe [this issue](https://github.com/rails/rails/issues/24949) is the cause of the problems.

Right now, when I want to call rouge within my `html.erb` file, I simply do:

```
<%= raw rouge(@question.test_suite, @question.language) %>
```

But now that doesn't work.

I am not quite sure how to get my code to be formatted properly now.

Thoughts?

**Edit 1**

For a complete explanation of what I am doing and what's happening, please see the explanation here: https://github.com/rails/rails/issues/24949#issuecomment-231497151

**Edit 2**

So I found what seems to be a solution, but the strange thing is that it worked before. 

Basically, I just had to wrap the `raw rouge` helper method call in my view with `pre` tags that have a class of `highlight`.

Now the formatting works. 

However, now it adds a weird space to the first line of the text that is being highlighted. For instance, look at it here: https://refactormeplz.com/questions/family-tree-relation-conversion . Scroll down to 'Test Suite'. You will notice the `context 'when the user is male'` is way in the middle of the page, when it should be flush left.

What could be causing this?

**Edit 3**

It turns out that when I updated Rails 5, it also updated this gem from `1.11.0` to `2.0.2` and that broke a bunch of stuff in my app.

But that still doesn't answer why it is adding a space to the beginning of the code that is formatted.

Could it be the theme I am using? `<%= Rouge::Themes::Github.render(scope: '.highlight') %>`

**Comment by jneen** [comment]
Ah. Rouge 1.x and 2.x formatters are not compatible. I'm not sure what's going on with Rails 5, but you will have to, as you did, manually wrap the output with `<pre>` tags. The indentation is likely caused by something in your template engine - spaces, including indentation, within `<pre>` tags are preserved in rendering.
