### ISSUE TITLE
liquid tag for rendering rouge css

### ISSUE THREAD

**Issue by stevecrozz** [rouge-ruby/rouge#513]
Not sure if you'd be interested in adding this to the project or not, but I put this together and found it useful for my Jekyll sites:
https://gist.github.com/stevecrozz/9b0a598223c03b4adacdd73acf2c3315

It's pretty basic, but maybe it'll save folks some time to have it or reference it from the docs.

**Comment by jneen** [comment]
Looks good :]. I'd suggest releasing it as its own gem (`rouge-liquid` or similar) which includes tags for css and highlighting.
