### ISSUE TITLE
Do we have a highlighter for SAS?

### ISSUE THREAD

**Issue by abrahamdu** [rouge-ruby/rouge#523]
I checked the Wiki and don't find we can use Rouge to highlight [SAS](http://www.sas.com/en_us/home.html). Is there anyone planning to work on that? Thanks!

**Comment by tomsutch** [comment]
I have written one and submitted a pull request: https://github.com/jneen/rouge/pull/1107

**Comment by pyrmont** [comment]
This was indeed fixed by #1107.
