### ISSUE TITLE
syntax highlighting support for CUDA C++ .cu / .cuh files

### ISSUE THREAD

**Issue by florianjacob** [rouge-ruby/rouge#535]
I'm a gitlab user (which, to my knowledge, uses rouge to highlight) and noticed it does not highlight `.cu` and `.cuh` files.

Essentially, those files are a superset of `.cpp` and `.hpp`, with some additions to execute code on the GPU.

As far as I know, that's only `__device__`, `__global__`, `__host__` and `__shared__` specifiers written before some functions or variables, and a special syntax to call those functions with `function_name<<<numBlocks,numThreads>>>()`.

An example of how those elements are used:

``` cuda
__global__ void mykernel() {
    // do something here…
}

int main() {
    mykernel<<<1,1>>>();
    printf("Hello World!\n");
    return 0;
}
```

Thanks for your time. :smile:

**Comment by pyrmont** [comment]
@florianjacob I realise it's been a very long time but we've just merged a lexer for CUDA into the master branch. Rouge is currently on a two-week release cadence as we clear the backlog of outstanding pull requests. I suspect you probably don't need this any more but just in case it's still something you'd like to use: a gem with the CUDA lexer will be available when 3.7.0 is released next Tuesday. Sorry it took so long!
