### ISSUE TITLE
handle better <script type=""> not javascript

### ISSUE THREAD

**Issue by glensc** [rouge-ruby/rouge#548]
it's perfectly valid to use `<script>` tag where `type` is not `type="text/javascript"`, in such case the content should not treated as javascript.

it's common to use this technique to insert html templates to page for javascript. for example:

``` html
<script type="text/x-tpl" class="share-for-free-dialog-tpl">
    <a href="#" class="dialog-close modal-close">&times;</a>
</script>
```

but it gets rendered ugly, here's screenshot from [demo site](http://rouge.jneen.net/):

![image](https://cloud.githubusercontent.com/assets/199095/18743492/ff0f0828-80c1-11e6-8336-be3da190b7ef.png)

**Comment by glensc** [comment]
If maintainers don't care for 4 years, I don't care either. No need to threaten with a bot. just close. In fact, I don't even remember why I needed this.

**Comment by pyrmont** [comment]
@glensc Sorry that message sounded threatening, that definitely wasn't the intention :( I've only recently joined the project as a maintainer and set up Probot as a way to rationalise a lot of the outstanding issues (we have over 200! O_O).

I just had a look and this error is still there. I'll replace the `stale-issue` label with a `bugfix-request` label. The priority at the moment is to clear the outstanding PRs (there are still about 100 of those) but [we're making progress](https://github.com/rouge-ruby/rouge/commits/master) and hopefully we can then turn to fixing outstanding bugs.

**Comment by glensc** [comment]
looks like there are already attempts to solve: #645, however that solution seems wrong and short-sighted, only blocks with `<script type="javascript">` should get rendered as javascript, everything else should be left unformatted. and in the future more types detected with appropriate hiliting, if they became common.

**Comment by pyrmont** [comment]
Thanks for checking out #645. Your comment's quite helpful!

**Comment by pyrmont** [comment]
I've still got a large number of PRs to get through before I reach #645 but I came across [this SO answer](https://stackoverflow.com/questions/14323376/do-html5-script-tag-need-type-javascript#14323399) coincidentally and wanted to put it down here so I don't forget it for later.
