### ISSUE TITLE
Add support Apache Pig.

### ISSUE THREAD

**Issue by jandresaedo** [rouge-ruby/rouge#557]
Apache Pig is a high-level platform for creating programs that run on Apache Hadoop

Reference: https://en.wikipedia.org/wiki/Pig_(programming_tool)

File extention: .pig

**Comment by jandresaedo** [comment]
I'm working on it. 
Guys do you have any document or rules for create a new branch and a new pull request?.

Thanks.

**Comment by jneen** [comment]
Hi! If you run `rake lex[pig]`, stubs for all the necessary files should be added for you. There's a page in the wiki of this project that gives suggestions for getting set up with ruby, if that's something you need as well.

**Comment by jandresaedo** [comment]
Got it, Thanks.
