### ISSUE TITLE
Standalone regex highlighting

### ISSUE THREAD

**Issue by LukeeeeBennett** [rouge-ruby/rouge#572]
I'd love to see standalone regex highlighting!

For example, the expression `/<{7}(?=[\s\S]*?)/g` on regexr.com is shown as...

<img width="214" alt="screen shot 2016-11-14 at 16 54 45" src="https://cloud.githubusercontent.com/assets/5678671/20273987/1f57e56c-aa8b-11e6-8e9e-745d38721991.png">

**Comment by DomGarguilo** [comment]
+1 for this feature
