### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by vning93** [rouge-ruby/rouge#586]
More companies than ever are starting to use GraphQL. It would be great to have support for the GraphQL language as well.

Thanks!

**Comment by langpavel** [comment]
This can be closed.
I just opened two new issues:
- #992: multiline string support
- #993: Markdown support for multiline strings often used as descriptions

**Comment by benneq** [comment]
It looks like the `extend` keyword is missing.

**Comment by pyrmont** [comment]
GraphQL support was added via #634. The `extend` keyword support was added via #1261.
