### ISSUE TITLE
Syntax highlighting for `new` keyword in Ruby

### ISSUE THREAD

**Issue by AlexWayfer** [rouge-ruby/rouge#596]
Hello!

Rouge is highlighting `new` in Ruby as keyword without any context now.

Example of problem: [Sequel has method `new?` for models](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Model/InstanceMethods.html#method-i-new-3F), it's not Ruby-keyword, but highlighting as it.

[Rouge paste with code](http://rouge.jneen.net/pastes/m9a1)
[Screenshot of highlighting](https://cloud.githubusercontent.com/assets/6510020/21405581/cf9c8a2c-c7d7-11e6-85b3-782396d0118c.png)

I think, that we need:
1. doesn't highlight methods with `new` __and__ others symbols (`new?`)
2. doesn't highlight `new` method in instance methods when receiver isn't `class` 

I'm not sure about the last one, but you can think about this.

Thanks!

**Comment by AlexWayfer** [comment]
Today I've discovered another one: [`new` as argument](http://rouge.jneen.net/pastes/laWx).

**Comment by jneen** [comment]
I'd be happy to look at a pull request that implemented this.

**Comment by AlexWayfer** [comment]
How can I distinguish an instance from a class? And argument or not, for example.

**Comment by jneen** [comment]
There's not really a way to make that distinction, unfortunately.

**Comment by jneen** [comment]
For an argument, you'd use the `:expr_start` case. If all you care about is capitalized words (and not whether it actually represents a class or an instance in the runtime), you can branch off when that particular thing is matched, I think it's line 214 of the ruby lexer.
