### ISSUE TITLE
c#: interface declaration should be highlighted like class declaration

### ISSUE THREAD

**Issue by haesemeyer** [rouge-ruby/rouge#605]
Currently the name of classes and structs in csharp is given a style indicating that they are user-defined types. However, this is not done for interface declarations even though as far as the language is concerned they are user-defined types as well.

I suggest expanding in csharp.rb
```ruby
rule /class|struct/, Keyword, :class
```
to
```ruby
rule /class|struct|interface/, Keyword, :class
```
in order to fix this.

Martin

**Comment by miparnisari** [comment]
This was implemented in https://github.com/rouge-ruby/rouge/blob/f8f229598c15ff88c29c19d263032f34f757ed75/lib/rouge/lexers/csharp.rb#L92

![image](https://user-images.githubusercontent.com/5374887/58744734-3b834780-83fb-11e9-9745-2fa025eb7e8e.png)

We can close this @pyrmont

**Comment by pyrmont** [comment]
Cheers!
