### ISSUE TITLE
Ruby Lexer fix

### ISSUE THREAD

**Issue by akemrir** [rouge-ruby/rouge#61]
hi there,

I have found some missuse, that exists in wrong highlighting of methods that are used on objects in ruby. It looks the same as definition name now.

I have digged in this lexer and changed this:

``` ruby
       rule /(\.|::)([a-z_]\w*[!?]?|[*%&^`~+-\/\[<>=])/,
         'Name.Function', :expr_start
```

to that

``` ruby
       rule /(\.|::)([a-z_]\w*[!?]?|[*%&^`~+-\/\[<>=])/,
         'Name', :expr_start
```

This regexp is quite complex.
What do you think, It will have other after-effects?

**Comment by monfresh** [comment]
I actually disagree with this behavior. Method names should not be highlighted in the same way as method calls in Ruby. I don't think I've come across any other highlighter that does this. Check out how GitHub does it, for example:

```ruby
def this_is_a_method_name
  puts 'hi'
end

user.this_is_a_method_name
```
The method name is in purple, but chained method calls are all in black.

In my particular case, I'm using middleman-syntax, which uses Rouge, and the CSS theme I'm using sets `name.function` to bold, so the result is that when I chain methods, such as `user.method`, `method` is in bold, but `user` is not, which doesn't look right.
