### ISSUE TITLE
Add support for Template Strings in TypeScript

### ISSUE THREAD

**Issue by elias-garcia** [rouge-ruby/rouge#635]
Hi, in TypeScript is very common to use backtick string literals, also known as template strings. I think that add this would be add one line of code to the typescript file, but I don't know Ruby or how this library is implemented at all...

This is an example of backtick string literal:

<img width="355" alt="captura de pantalla 2017-03-15 a las 23 03 44" src="https://cloud.githubusercontent.com/assets/6737805/23972833/b27d768e-09d3-11e7-82dd-04c351006b83.png">

**Comment by thiagoabreu** [comment]
Not only TypeScript, it's a ES6 syntax 👍
