### ISSUE TITLE
JavaScript template literals (using back-tick) rendered as `err`

### ISSUE THREAD

**Issue by ilg-ul** [rouge-ruby/rouge#641]
```
<span class="err">`</span>
```

The input code is:

<code>
```javascript
</code><br/>
<code>
const paramOk = `Back quotes string with ${parameter}`
</code><br/>
<code>
```
</code>

**Comment by revathskumar** [comment]
@ilg-ul I think this works fine in the latest version (2.0.7). The http://rouge.jneen.net will show error since it still uses 1.x. There is a PR open to update the web page jneen/rouge.jneen.net#24

**Comment by ilg-ul** [comment]
yes, good to know, but I currently use it via jekyll -> kramdown -> rouge, and I guess it'll take some time for the new version to propagate, right the latest kramdown requires `~>1.8` and my actual Gemfile.lock (a bit older) shows `~>1.7`

a `bundle update` did not change things, so I'll probably have to wait...

thank you,

Liviu

**Comment by stenmuchow** [comment]
+1

**Comment by miparnisari** [comment]
This works for me @ilg-ul @stenmuchow 

![image](https://user-images.githubusercontent.com/5374887/58744747-79806b80-83fb-11e9-9d4a-48464460f172.png)

@pyrmont should we close it?

**Comment by pyrmont** [comment]
Yeah, seems to be displaying fine on [the website](http://rouge.jneen.net/pastes/e0Lk) now. Thanks for the heads up, @miparnisari!
