### ISSUE TITLE
SML syntax highlighting eats up "if" keyword

### ISSUE THREAD

**Issue by munircontractor** [rouge-ruby/rouge#657]
### Summary

"if" keyword is not visible in SML code

### Steps to reproduce

1. Create a SML function with an if statement in it
2. Save file with .sml extension and push to Gitlab

Example:
```
infix ++
fun l ++ [] = l
  | l ++ (y::ys) = if y elt l then l ++ ys else (y::l) ++ ys
```
when typed in a .sml file or with `sml` tag in the code markdown appears as
```sml
infix ++
fun l ++ [] = l
  | l ++ (y::ys) = y elt l then l ++ ys else (y::l) ++ ys
```

### What is the current *bug* behavior?

"if" keyword is not visible while viewing the code, but it is present in the raw version.
Checked on Chrome and Firefox.

### What is the expected *correct* behavior?

"if" keyword should be visible.

### Relevant logs and/or screenshots

![image](https://cloud.githubusercontent.com/assets/11322718/25135703/13f35458-2421-11e7-8fe4-309644c41db5.png)

I spotted this on Gitlab.com and they asked me to raise this here. This is the original issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/30981

**Comment by jneen** [comment]
I believe I've fixed this in 3796474 - could you confirm?

**Comment by munircontractor** [comment]
Hi @jneen 
I ran the visual test from your README document and it looks fine. Hopefully, Gitlab will also update soon.
Thank you so much!

**Comment by miparnisari** [comment]
This was fixed and we can close it.

![image](https://user-images.githubusercontent.com/5374887/58768222-88c2fe80-854c-11e9-9db2-e99fc2b3d446.png)

**Comment by pyrmont** [comment]
Thanks @miparnisari!
