### ISSUE TITLE
SAS Lexer for rouge

### ISSUE THREAD

**Issue by allanbowe** [rouge-ruby/rouge#677]
We're currently building this lexer and planning to share in a PR.  Our hope was - should the PR be accepted - that the lexer could be leveraged in Kramdown via GitHub pages.

However, I understand that GitHub are actually [stuck with version 1.11.1](https://pages.github.com/versions/) of Rouge as they are blocked by this pull request:  https://github.com/jekyll/jekyll/pull/5919

Is there any update on how to move forward?

**Comment by jneen** [comment]
That is up to GitHub. Since I have very limited resources (and GitHub has... well, plenty), I do not consider it an appropriate use of my time to backport code for them, especially since 1.11.1 is about a year out of date.
