### ISSUE TITLE
How can I spilt code into lines, each contained in its own div

### ISSUE THREAD

**Issue by alexkie007** [rouge-ruby/rouge#708]
I have read the read me,  and I wanna implement this function in my rails app. How can I use this api to by construct the formatter.

Rouge::Formatters::HTMLLinewise.new(formatter, class_format: 'line-%i') This formatter will split your code into lines, each contained in its own div. The class_format option will be used to add a class name to the div, given the line number.

Thank you very much

**Comment by jneen** [comment]
If you're wondering how to use code as in the example, you might try:

``` ruby
Rouge::Formatters::HTMLLinewise.new(Rouge::Formatters::HTML.new)
```

**Comment by jneen** [comment]
Or! You can write your own formatter and use the `token_lines` method to receive chunks of tokens line-by-line and yield out whatever HTML you like.
