### ISSUE TITLE
Angular 2+ HTML bindings templates are highlighted as errors.

### ISSUE THREAD

**Issue by SoftwareTipi** [rouge-ruby/rouge#725]
`<app-my #my></app-my>` and `<div [class.test]="expression"></div>` and `<button (click)="fun()"></button>` and `<input [(value)]="data"></input>`.
All above binding are highlighted as errors on GitLab which uses rouge as far as I know.
Sorry, if it's my fault, and I only need some additional angularx configuration, but I couldn't find any syntax hightlight for angular2+ on README etc. 

EDIT:// And anyway seems like `[value]="exp"` and so are valid html tags :)

**Comment by nicktobolski** [comment]
I would loved to see this fixed. We're using Angular for a big project at my company and Gitlab's failing to diff angular templates is a nuisance and an impediment to progress. 

Maybe an Angular team engineer would be interesting in help out?

**Comment by pyrmont** [comment]
#907 has been merged into master and should address this. Sorry it took so long! >_<
