### ISSUE TITLE
@jneen is starting grad school

### ISSUE THREAD

**Issue by jneen** [rouge-ruby/rouge#726]
cc @gfx @dblessing 

Since I'll be starting as a graduate student in September, I won't be available to maintain Rouge for much longer. So! I want to give both of you merge permissions and access to the rouge gem on rubygems.org, as well as walk you through the release process.

**Comment by dblessing** [comment]
@jneen Congrats. Sorry we won't see you around much but that sounds like a good opportunity. Happy to talk through the Rouge process anytime.

**Comment by gfx** [comment]
Congrats! 🎉 

I'll do my best because Rouge is important to my business. My rubygem.org account is:

https://rubygems.org/profiles/gfx

You can add me to the owners by `gem owner ts_assets --add g.psy.va@gmail.com`.

**Comment by jneen** [comment]
Are the two of you able to merge pull requests, or is there a setting I have to enable for that?

**Comment by jneen** [comment]
As far as releases go, I trust that you will find a way to coordinate those. My process is:

* Update the CHANGELOG.md with attribution for pull requests
* Update `lib/rouge/version.rb` with the new version number
* `rake gem` to make a gem, (makes sure the tests pass), and push the gem up to rubygems
* commit the change to CHANGELOG.md and `version.rb` with the status message and tag vX.X.X
* push the release commit and tag to master

**Comment by jneen** [comment]
Errr... apparently I don't have a `rake gem` on this project, so... I'd say just make sure the tests pass.

**Comment by jneen** [comment]
And @dblessing if you could send me the email address you use for rubygems, I can add you as an owner.

**Comment by gfx** [comment]
With recent rake, `rake release` creates git tag, build a gem package, upload it to rubygems.org, do `git push [tag]`.

So, all we have to do are (1) update CHANGELOG.md, (2) bump version in `version.rb`, and do `rake release`. 

I think even CHANGELOG.md can be automatically maintained to gather pull-requests from git tags.

**Comment by parkr** [comment]
Congratulations, @jneen! I hope you enjoy grad school 😄
