### ISSUE TITLE
Docker lexer misses command endings if lines end with `/`

### ISSUE THREAD

**Issue by luise** [rouge-ruby/rouge#731]
E.g.:
```
# Highlighted as COMMENT
COPY myScript.sh /myDir/

# Highlighted as COMMAND
# Highlighted as COMMENT
```

This first comment line after the `COPY` command should be highlighted as a comment, not as a command.

If we change the `COPY` command to be  `COPY myScript.sh /myDir/myScript.sh`, all comments are highlighted correctly.

Thanks!

**Comment by miparnisari** [comment]
This works for me

![image](https://user-images.githubusercontent.com/5374887/58768205-43063600-854c-11e9-9c2c-2fa5ec0243cb.png)

**Comment by pyrmont** [comment]
[Same here](http://rouge.jneen.net/pastes/XkxM). Thanks @miparnisari :)
