### ISSUE TITLE
Add support for Jenkinsfile

### ISSUE THREAD

**Issue by marcelbrueckner** [rouge-ruby/rouge#753]
Add support for Jenkinsfile.

As Groovy syntax is already supported, it should be as easy as extending the [groovy_spec.rb](https://github.com/jneen/rouge/blob/c1c1f1d66f5798e09f8ab5bb90980c753408b1d0/spec/lexers/groovy_spec.rb) by 'guessing by filename' or (more generic) by searching for a shebang like #!groovy (like it is done in [shell_spec.rb](https://github.com/jneen/rouge/blob/47e79550178a8f0a9668ce813d956f9aba476a0a/spec/lexers/shell_spec.rb)).

A similiar issue was already raised at [GitLab's issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues/33229). As GitLab is using rouge, the issue should be raised here.

**Comment by jneen** [comment]
This should be as easy as adding `Jenkinsfile` to the `filenames` declaration in `lib/rouge/lexers/groovy.rb`

**Comment by pyrmont** [comment]
This was subsequently added.
