### ISSUE TITLE
Add support for nunjucks templating language

### ISSUE THREAD

**Issue by armpogart** [rouge-ruby/rouge#758]
Add syntax highlighting for [Nunjucks](https://mozilla.github.io/nunjucks/).

As nunjucks is heavily inspired by jinja2 (twig), for now it is only a matter to add the same highlighting to .njk extensions (.njk is community adapted extension, see [here](https://mozilla.github.io/nunjucks/templating.html)).

Nunjucks is jinja2 inspired templating language heavily used in frontend development nowadays as it is one of the most powerful ones.

**Comment by nervgh** [comment]
It would be great to support of syntax highlight for [Nunjucks](https://mozilla.github.io/nunjucks/).  
In particular it means highlighting [.njk](https://mozilla.github.io/nunjucks/templating.html#file-extensions) files using [Twig](https://twig.symfony.com/) preset.

+1 for this "feature"

**Comment by Hirbod** [comment]
not stale
