### ISSUE TITLE
add logfile / config file syntax highlighting like 'ccze'

### ISSUE THREAD

**Issue by rcampbel3** [rouge-ruby/rouge#769]
Hi,

I would like to take advantage of logfile and config file syntax highlighting in applications that use rouge. On the commandline, I like piping output to the utility 'ccze'. I would be very excited to have either a 'ccze' or 'logfile' syntax highliting filter as an option.

See: https://lintut.com/colorize-log-files-on-linux-using-ccze-tool/
and https://github.com/cornet/ccze

This tool has a wealth of syntax highilighting information for log file and config file use that make it very useful for sysadmins. Thanks for your consideration.

**Comment by juwens** [comment]
fyi: i was looking for something like this too. And for serilog formatted log, the "conf" highlighting does some highlighting (better than nothing).
