### ISSUE TITLE
YAML syntax highlighting for keys with periods and forward slashes

### ISSUE THREAD

**Issue by aplowman** [rouge-ruby/rouge#778]
If you place a period in YAML key, the highlighting looks wrong. Are periods in keys not valid YAML or is there a problem with the syntax highlighting? I've tested this using the [online previewer](http://rouge.jneen.net/) with this YAML:
```
a: 1
b.c: 2
d: 3
```

**Comment by AlexWayfer** [comment]
The same with `/`:

![image](https://user-images.githubusercontent.com/6510020/35434414-1b1a1bda-0298-11e8-9f4e-d8161f5509bb.png)

**Comment by pyrmont** [comment]
@aplowman I realise it's been a long time since this bug was originally filed but just wanted to confirm that this is a bug. Your example uses [valid plain style scalars](https://yaml.org/spec/1.2/spec.html#id2788859).
