### ISSUE TITLE
Broken coffeescript syntax highlighting

### ISSUE THREAD

**Issue by martinkadlec0** [rouge-ruby/rouge#801]
### Summary

Multiline comments starting with asterisk in coffeescript break syntax highlighting.

Note that the asterisk is important as some libraries (e.g. closure compiler) requires it for its annotations to work.

(Based on https://gitlab.com/gitlab-org/gitlab-ce/issues/38959)

### Steps to reproduce

- Create a commit containing multiline comment with asterisk, e.g.:

```
###*
  @param {number} x
  @param {number} y
###
add = (x, y)->
  x + y
```
- Look at the commit in application using rouge - e.g. gitlab

### Example Project

https://gitlab.com/martinkadlec0/broken-coffeescript-syntax-highlighting/commit/8e919bfac68222b93701e6236a5480b9b96640a3

### What is the current *bug* behavior?

- Syntax highlighter ignores the `###*` comment start and thinks the comments starts with the second `###`

### What is the expected *correct* behavior?

- Syntax highlighter recognises `###*` is a start of multiline comment

**Comment by jneen** [comment]
Is this supported syntax? My understanding was that a newline was required after `###`. Could you link to a place in Coffeescript's documentation where this syntax is described?

**Comment by martinkadlec0** [comment]
http://coffeescript.org/#comments

> or from ### to the next appearance of ###
no mention of required new line.

Writing the asterisk just after the `###` is - i think - the only way to get two asterisk just after each other in js.
```
###*
  xyz
###
...
/**
  xyz
*/
```

**Comment by pyrmont** [comment]
@martinkadlec0 The bug no longer looks like it's there when I check on [rouge.jneen.net](http://rouge.jneen.net) (sorry, we've exhausted the free space on Heroku so I'm not currently able to save pastes). Are you still seeing the bug?

**Comment by martinkadlec0** [comment]
On rouge.jneen.net it works fine for me as well. It is still broken on our gitlab but it uses rouge-3.3.0 so it might have been fixed since then.

**Comment by pyrmont** [comment]
B'oh—it was _my_ commit that fixed this and I somehow forgot I'd done it! See [here](https://github.com/rouge-ruby/rouge/pull/1123/). It was an oversight on my part not to close this issue at the time of the merge.

**Comment by martinkadlec0** [comment]
Great, thank you!
