### ISSUE TITLE
No way to escape single quote

### ISSUE THREAD

**Issue by doodlesbykumbi** [rouge-ruby/rouge#803]
- Current ![image](https://user-images.githubusercontent.com/8653164/31454775-7e3c31fa-aeae-11e7-8432-438a8bc4c09c.png)

vs

- Ideal 
![image](https://user-images.githubusercontent.com/8653164/31454903-ea8b787a-aeae-11e7-9d3a-8e33133d6e73.png)

If I could get some guidance as to what's responsible for this behaviour I could take a look and open a PR :)

**Comment by pyrmont** [comment]
@doodlesbykumbi [An escape lexer](https://github.com/rouge-ruby/rouge/pull/1152) has recently been added by @jneen. It looks to me like that's really what you want. The text you're talking about escaping is not shell input text but output text (which isn't really what a lexer is designed to tokenise).
