### ISSUE TITLE
Shell highlighting incorrect for combining $(...) with ((...))

### ISSUE THREAD

**Issue by kkopper** [rouge-ruby/rouge#812]
The following code snippet is not rendered correctly (see http://rouge.jneen.net/pastes/Jlw3):

````shell
# Not highlighted correctly
echo Highlighting fails: $( if (( a == b )) ; then "equal" ; fi )

# Not highlighted correctly
echo "Highlighting fails: $( if (( a == b )) ; then "equal" ; fi )"

# Highlighted correctly
echo "Highlighted $( echo "correctly" )"

# Highlighted correctly
if (( a == b )) ; then "equal" ; fi

# Highlighted correctly
echo "Highlighting `if (( a == b )) ; then "equal" ; fi` works"
````

The highlighting breaks if using arithmetic expansion `((..))` inside command substitution (only for `$(..)`). This appears both in regular and double quoted context.

**Comment by pyrmont** [comment]
@kkopper Is this still broken for you? I had only a quick look but it looked all right to me.

**Comment by kkopper** [comment]
Quickly checking, the following line is still not highlighted correctly:
```shell
echo "Highlighting fails: $( if (( a == b )) ; then "equal" ; fi )"
```
