### ISSUE TITLE
Ada language support

### ISSUE THREAD

**Issue by AdaDoom3** [rouge-ruby/rouge#824]
Your project is used by Gitlab which seems to be disinterested in adding Ada syntax highlighting.
See: https://gitlab.com/gitlab-org/gitlab-ce/issues/37709

Basic Ada language support would be nice.

**Comment by JethroT** [comment]
We also use GitLab for Ada development. Please add support for Ada 2012 & SPARK 2014 syntax to Rouge. On GitHub, which apparently uses a different highlight tool, Ada looks good enough in the sources in the https://github.com/AdaCore projects.

**Comment by pyrmont** [comment]
Sorry, this has an associated PR and should not have been marked as stale. The PR is currently under review and should hopefully be merged soon :)
