### ISSUE TITLE
javascript object with escaped backslash and immediate quote is broken

### ISSUE THREAD

**Issue by fireattack** [rouge-ruby/rouge#828]
Quote immediately after escaped backslash (`\\`) is incorrectly escaped:

![image](https://user-images.githubusercontent.com/4130991/32986751-f555c802-cc9d-11e7-9d6a-8b5b5f975682.png)

Compare to: 
![image](https://user-images.githubusercontent.com/4130991/32986756-12d567de-cc9e-11e7-9c81-b556e4493bad.png)

Also not sure why `\n` is not highlighted in a consistent way, either:

![image](https://user-images.githubusercontent.com/4130991/32986760-24200eb8-cc9e-11e7-9120-c8f14f16e12d.png)

This bug seems only affects the first occurrence. when there are two `"\\"`, they highlighted differently

![image](https://user-images.githubusercontent.com/4130991/32986846-676c814a-cca0-11e7-9c6f-e41ae5c745a6.png)

Because of that, when escaped backslash + immediate quote (such as `"\\"`) exists, the colors after it all got reversed.

NORMAL: 
![image](https://user-images.githubusercontent.com/4130991/32986800-51188b10-cc9f-11e7-8218-382684ca022d.png)

BUGGED:

![image](https://user-images.githubusercontent.com/4130991/32986803-63168448-cc9f-11e7-8ff1-aa763fd3efb6.png)

**Comment by fireattack** [comment]
I discovered this bug on GitLab (example below):

![image](https://user-images.githubusercontent.com/4130991/32986888-38488c32-cca1-11e7-962e-2b75bfe71618.png)

**Comment by lannonbr** [comment]
I can confirm this still is an issue that still exists and hasn't been resolved

**Comment by vemoo** [comment]
Also affects typescript example: https://gitlab.com/berublan/vscode-log-viewer/blob/6d71a8e46bbe03f4e0fb65e71f48c80d073017fa/test/vscodefree/pathPattern.test.ts

**Comment by cben** [comment]
gilab issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/59787#note_156933111

**Comment by miparnisari** [comment]
@fireattack @cben I wish I could comment on the GitLab issue.

> Do you guys think we should start to consider alternatives of Rouge for syntax highlighting (if any, of course)?

You guys own this project. Can you assign resources to it?

**Comment by dblessing** [comment]
@pyrmont Would you mind taking a look at this, please? When you get time.

**Comment by fireattack** [comment]
Thanks. Glad someone is taking care of this project again.
