### ISSUE TITLE
Swift: fix tuple destructuring

### ISSUE THREAD

**Issue by dan-zheng** [rouge-ruby/rouge#833]
Tuple destructing is not handled correctly: http://rouge.jneen.net/pastes/oGAE

In particular, the `let` in `let (a, b, ...)` is parsed as a function name instead of a keyword.

Perhaps [this rule](https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/swift.rb#L106) could be edited:
```ruby
rule /(let|var)\b(\s*)(#{id})/ do
  groups Keyword, Text, Name::Variable
end
```

**Comment by pyrmont** [comment]
This should have been closed when the PR was merged. Sorry for the message about the issue being marked stale! I've closed it now :)
