### ISSUE TITLE
SCSS and Sass give errors with `::` (pseudo-element) in selector

### ISSUE THREAD

**Issue by AlexWayfer** [rouge-ruby/rouge#841]
[SCSS](http://rouge.jneen.net/pastes/Vwz6)

![image](https://user-images.githubusercontent.com/6510020/34264076-ba5e1098-e682-11e7-80ba-cee1bc8faafd.png)

[Sass](http://rouge.jneen.net/pastes/xXq0)

![image](https://user-images.githubusercontent.com/6510020/34264085-bf8ff536-e682-11e7-96c1-4020977c458f.png)

**Comment by AlexWayfer** [comment]
Simplified examples:

[SCSS](http://rouge.jneen.net/pastes/2ZmZ)

![image](https://user-images.githubusercontent.com/6510020/34264179-0c25919e-e683-11e7-9bf3-8c806392ba7a.png)

[Sass](http://rouge.jneen.net/pastes/RM1x)

![image](https://user-images.githubusercontent.com/6510020/34264201-2a0c6c28-e683-11e7-85f4-4538d3cfd333.png)

**Comment by gfx** [comment]
@AlexWayfer What is your Rouge version? Is there a difference between v3.0.0 and v3.1.0?

**Comment by purecaptain** [comment]
I cloned the v3.1.0. And I have print the m[2] in the next function, the variable is ''.
```ruby
  state :lang_tag do
    rule /(lang\s*=)(\s*)("(?:\\.|[^\\])*?"|'(\\.|[^\\])*?'|[^\s>]+)/ do |m|
      groups Name::Attribute, Text, Str
      puts "m[2]: #{m[2]} 
      @lang = lookup_lang(m[2])
    end

    mixin :tag
  end
```
Also, I changed the variable to ```m[3]```，but the function ```lookup_lang``` always return ``` PlainText```

**Comment by gfx** [comment]
@purecaptain It's vue.rb, isn't it? Is it related to this SASS/SCSS issues?

**Comment by purecaptain** [comment]
It's vue.rb.  A vue issues. But it can write SCSS codes in Vue. So I think it's also can put the issue in this.

**Comment by gfx** [comment]
@purecaptain Please file a new issue for Vue + SCSS issues. It seems not related to this issue.

**Comment by purecaptain** [comment]
Ok

**Comment by AlexWayfer** [comment]
> @AlexWayfer What is your Rouge version? Is there a difference between v3.0.0 and v3.1.0?

I've attached links to the [official site](http://rouge.jneen.net/). I see in footer `3.1.0`.

Also I found it in GitLab 10.2.4 (don't know what version it's using).

**Comment by pyrmont** [comment]
I can confirm this bug is still there.

**Comment by pyrmont** [comment]
I'll try to get this fixed soon.
