### ISSUE TITLE
Creating a rouge syntax highlighting plugin for YARD

### ISSUE THREAD

**Issue by noraj** [rouge-ruby/rouge#855]
Is someone able to help me to build a rouge syntax highlighting plugin for YARD.

Existing syntax highlighting plugin for YARD may help:
+ [yard-coderay](https://github.com/sagmor/yard-coderay)
+ [yard-pygments](https://github.com/nex3/yard-pygments)
+ [yard-pygmentsrb](https://github.com/13k/yard-pygmentsrb)

And also yard [documentation](http://www.rubydoc.info/gems/yard/0.9.12).

Why? Because both yard-pygments plugin use pygments of course and so have python dependencies, that's not very nice for a pure ruby project and that coderay is very limited compared to rouge.

**Comment by noraj** [comment]
Sadly.

**Comment by ashmaroli** [comment]
@noraj Were you able to make any progress on this?
What's the current status of highlighting in YARD..?

**Comment by noraj** [comment]
@ashmaroli I'm not using Yard very often, so I never started the dev of this feature.
