### ISSUE TITLE
Handling sed format may hide some text

### ISSUE THREAD

**Issue by gdm** [rouge-ruby/rouge#860]
The following code 
`\#<url>https://google.com/?q=test</url>#{s|<url>.*?</url>|<url>test</url>|;n;s|||}`

shows as 

`\#>#{s|<url>.*?</url>|<url>test</url>|;n;s|||}`

This issue can be also reproduced in http://rouge.jneen.net when 'sed' format selected

This issue has been originally reported for GitLab https://gitlab.com/gitlab-org/gitlab-ce/issues/41868

**Comment by gdm** [comment]
Probably has the similar fix as for https://github.com/jneen/rouge/issues/654

**Comment by pyrmont** [comment]
Sorry, this has an associated PR (#893) and should not have been marked as stale. That's been fixed.
