### ISSUE TITLE
Why does the template code for the application angular highlight red each time in GitLab?

### ISSUE THREAD

**Issue by splincode** [rouge-ruby/rouge#865]
For example, this is the valid syntax of an angular template:
https://gitlab.com/splincode/beria/blob/master/app.component.html

What to do then? in terms of angular everything is right and github normally displays the code:
http://rouge.jneen.net/pastes/6ZRO

but for some reason attributes are highlighted
https://gitlab.com/gitlab-org/gitlab-ce/issues/42390

**Comment by pyrmont** [comment]
@splincode I don't think that syntax is valid HTML. That's why it's being highlighted as an error by Rouge.

**Comment by afeinman** [comment]
The issue here is that Rouge thinks the file is stock HTML, but it's actually (valid) Angular HTML. Is there a lexer for Angular's HTML variant?

**Comment by pyrmont** [comment]
@afeinman Apologies—I should have updated this issue back in July. We merged in #907 and that's fixed the issue (you can see that [the snippet](http://rouge.jneen.net/pastes/6ZRO) in the OP no longer shows errors).

**Comment by afeinman** [comment]
Thanks! Now it's up to GitLab to integrate the change...
