### ISSUE TITLE
Support SSH config highlighting

### ISSUE THREAD

**Issue by stv0g** [rouge-ruby/rouge#870]
As documented here: http://man7.org/linux/man-pages/man5/ssh_config.5.html

**Comment by stv0g** [comment]
Bump

**Comment by pyrmont** [comment]
Thanks for letting us know this is still desired!

Unfortunately, while I wish I had a more satisfying response, I'm sorry to say that this might remain outstanding for some time :( Rouge depends for its feature development on contributions from its community. If you'd like to see a syntax supported, the best thing to do is submit a PR with your new lexer.

When I became a maintainer, I wrote [a guide on lexer development](https://www.rubydoc.info/github/rouge-ruby/rouge/master/file/docs/LexerDevelopment.md) that might be of help. We have quite a backlog of existing PRs but we give newer ones priority so anything you submit will go to the top of the pile.

**Comment by IanLee1521** [comment]
I would be interested in this feature too.

**Comment by cmbuckley** [comment]
Added a basic lexer for SSH config in #1543.
