### ISSUE TITLE
cshtml

### ISSUE THREAD

**Issue by devel0** [rouge-ruby/rouge#873]
- **problem**: syntax highlight for cshtml (razor pages) not recognized
- **possible fix**: treat is as if it were an html could help coloring major syntax

**Comment by Cerbrus** [comment]
This still appears to be an issue.
`cshtml` files are rendered as plain text.

**Comment by pyrmont** [comment]
I can add the extension to the file glob recognised by the HTML lexer. Is that still the best solution?

**Comment by Cerbrus** [comment]
It's at least better than plaintext :-)
