### ISSUE TITLE
Ambiguous guess: can't decide between ["xml", "html"] occurs for specific xml code

### ISSUE THREAD

**Issue by chenhengjie123** [rouge-ruby/rouge#878]
I'm using rouge to render markdown. But I met error `Ambiguous guess: can't decide between ["xml", "html"]` while the markdown content is as below in a markdown code block (` ``` `):

```
<?xml version="1.0" ?>
     <jacoco:report>
      ...
          <html destdir="${reportfolderPath}" encoding="utf-8" />         
          <xml destfile="${reportfolderPath}/jacoco_report.xml" encoding="utf-8" />
    </jacoco:report>
```

Codes above are part of xml for an ant build.xml file for jacoco (<https://github.com/jacoco/jacoco/blob/master/org.jacoco.examples/build/build.xml>). It's pure xml code and should be detected as xml language.

**Comment by miparnisari** [comment]
@chenhengjie123 submitted a PR for this :)
