### ISSUE TITLE
Twig syntax highlighting broken

### ISSUE THREAD

**Issue by ericmorand** [rouge-ruby/rouge#881]
Hi,

First, sorry, I don't know anything about Ruby so I cant' give an example that is not a Jekyll template. Jekyll team confirmed that this is a Rouge issue (https://github.com/jekyll/jekyll/issues/6844).

So here it is, hoping that you'll be able to understand and reproduce the bug.

Rouge syntax highlighting is broken with Twig. Consider the following Jekyll code blocks containing a perfectly valid Twig syntax:

```
{% highlight twig %}
{% raw %}
{% set a = 'b' %}
{% endraw %}
{% endhighlight %}
```

```
    ```twig
    {% raw %}
    {% set a = 'b' %}
    {% endraw %}
    ```
```

Both outputs the following HTML:

```
<code class="language-twig" data-lang="twig">
    <span class="cp">{%</span> 
    <span class="k">set</span> 
    <span class="nv">a</span> 
    <span class="err">=</span>
    <span class="s1">'b'</span> 
    <span class="cp">%}</span>
</code>
```

Notice the **err** class attributed to the equal sign.

## Steps to reproduce

* Follow the official quick-start guide: https://jekyllrb.com/docs/quickstart/
* Replace the content of the post created by the installation with this:

```
---
layout: post
title:  "Welcome to Jekyll!"
categories: jekyll update
---

{% highlight twig %}
{% raw %}
{% set a = 'b' %}
{% endraw %}
{% endhighlight %}

```

**Comment by pathawks** [comment]
It looks like the [Twig lexer](https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/twig.rb) is a subclass of the [Jinja lexer](https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/jinja.rb), which does not include an assignment operator:

https://github.com/jneen/rouge/blob/966efcb7a1cfa1d1851f8f44d292426de2b5d006/lib/rouge/lexers/jinja.rb#L82-L87

For reference, the statement seems to render correctly on GitHub:

```twig
{% set a = 'b' %}
```

GitHub uses [the Twig TextMate bundle](https://github.com/Anomareh/PHP-Twig.tmbundle/blob/master/Syntaxes/HTML%20(Twig).tmLanguage) for highlighting Twig snippets.

**Comment by XaBerr** [comment]
Same problem here

**Comment by pyrmont** [comment]
Support for `raw` has been added via #1003. Please let us know if there are any problems with it!
