### ISSUE TITLE
Assembly Support

### ISSUE THREAD

**Issue by miladkahsarialhadi** [rouge-ruby/rouge#882]
Hello, Does it support Assembly syntax for as o nasm ??

**Comment by vidarh** [comment]
Hi, it supports nasm. Currently there is no guesser support for nasm, so either you need to specify nasm (how depends on where you're trying to use it), or the filename needs to end in ".asm".

**Comment by jonhoo** [comment]
Duplicate of #483?

**Comment by vidarh** [comment]
@jonhoo yes, you're right. And that changeset was merged, so it is in the current version
