### ISSUE TITLE
Python: syntax highlight breaks on representation of obj

### ISSUE THREAD

**Issue by Draio** [rouge-ruby/rouge#887]
I'm writing a python guide on github pages, every time I write an example that shows a representation of an object, the syntax highlighting breaks.

Here is an example:
http://rouge.jneen.net/pastes/5DK5

I know that <class 'int'> is not a python syntax, but only a representation of an object, but there is a way to not interrupt the syntax highlighting?

Thank you
Dario

**Comment by pyrmont** [comment]
@Draio An [escape lexer](https://github.com/rouge-ruby/rouge/pull/1152) has recently been added that can allow you to interrupt the syntax highlighting. There are two problems:

1. while this has been added to Rouge as of 3.4.0, GitHub Pages is still on [version 2.2.1](https://pages.github.com/versions/) (as of the time of writing); and
2. syntax escape like this represents a security risk and may not be enabled by platform providers like GitHub.

You may, in other words, have to run Rouge (eg. via Jekyll) on your own server to achieve the effect you're looking for. Sorry not to have better news :(

**Comment by Draio** [comment]
No problem.

Thank you for your work
Dario
