### ISSUE TITLE
Lexer R: underscores highlighted as error if they contain numbers

### ISSUE THREAD

**Issue by fmichonneau** [rouge-ruby/rouge#895]
I found that variables that contain 1 letter followed by 1 number would lead to highlight as "error" the following underscore in R

![screenshot from 2018-04-18 17-37-10](https://user-images.githubusercontent.com/5502922/38959611-47c09a24-432f-11e8-9c1f-9f0ca78855ff.png)

**Comment by pyrmont** [comment]
Sorry, this has an associated PR and should not have been marked as stale. Fixed now.

**Comment by pyrmont** [comment]
Fixed in #896.
