### ISSUE TITLE
RFE: Add support for EPP - Embedded Puppet

### ISSUE THREAD

**Issue by ananace** [rouge-ruby/rouge#901]
https://puppet.com/docs/puppet/5.4/lang_template_epp.html

The syntax is much like ERB, only embedding Puppet instead of Ruby, and with a few small differences in the templating itself - like the parameters block.

**Comment by ananace** [comment]
This is still something that I'd like to have - and the PR to implement it has been open for quite a while

**Comment by ananace** [comment]
( PR is #903 for reference )

**Comment by pyrmont** [comment]
I'm sorry, this shouldn't have been marked as stale given the associated PR. Fixed it now (and we're slowly [getting through the backlog of PRs](https://github.com/rouge-ruby/rouge/commits/master) so this should be reviewed soon!).
