### ISSUE TITLE
Makefile: highlighting error for `include` and functions

### ISSUE THREAD

**Issue by gcapes** [rouge-ruby/rouge#913]
I maintain the Software Carpentry lesson on Make, and I have noticed that the syntax highlighting doesn't work correctly for `include` and when using functions e.g. `wildcard` and `patsubst`.

See https://github.com/swcarpentry/make-novice/issues/134#issuecomment-390194079 and screenshot below:
 ![image](https://user-images.githubusercontent.com/12446270/40235040-d3eda1b2-5aa0-11e8-95df-19cdbf936999.png)

**Comment by gcapes** [comment]
@rouge-ruby
Any thoughts on this?

**Comment by pyrmont** [comment]
@gcapes Hmmm... seems that although the keywords are defined (see below) they're never used in any of the rules:

https://github.com/rouge-ruby/rouge/blob/a03a3b302875bd70256fce1564944b960e3bd982/lib/rouge/lexers/make.rb#L14-L16

This is clearly a bug in the Make lexer. I don't mean to be the bearer of bad news but I'm afraid that it's unlikely this will get fixed soon without someone submitting a PR. We're doing our best to clear up the backlog after Rouge's hiatus but there's quite a lot to get through before we start looking at addressing individual issues :(

I will say that we are reviewing the newest PRs first, so if you wanted to take a stab at this yourself, your PR would be go to the top of the pile (or stack, as it were)! I became a maintainer recently and wrote [a guide to lexer development](https://www.rubydoc.info/github/rouge-ruby/rouge/master/file/docs/LexerDevelopment.md) that might be of some assistance.

**Comment by pyrmont** [comment]
Oh, and for future testing, here's the code I used to test:

```make
include config.mk

TXT_FILES=$(wildcard books/*.txt)
```

**Comment by gcapes** [comment]
Looks like this issue is now fixed. Thanks!
