### ISSUE TITLE
Kotlin Script Support

### ISSUE THREAD

**Issue by napperley** [rouge-ruby/rouge#927]
Syntax highlighting is missing for **kts** (Kotlin Script) files. Without highlighting it is difficult to read a kts file. One major use for kts files is with [Gradle build scripts](https://github.com/gradle/kotlin-dsl). More and more Kotlin projects use Gradle via the official Kotlin DSL, especially in server-side projects. Another major use for kts files is for [scripting JVM based tools](https://www.youtube.com/watch?v=cOJPKhlRa8c).

Most of the work required to do the highlighting is already done (about 95%), since the highlighting for **kt** (Kotlin source) files would cover just about everything.

## Other Links

- [Gradle Goes Kotlin](https://www.youtube.com/watch?v=4gmanjWNZ8E)
- [KotlinConf 2017 - Building Kotlin Applications at Scale with Gradle](https://www.youtube.com/watch?v=lg5hPBEIQ2E)
- [Writing Gradle Build Scripts in Kotlin - Gradle Summit 2016](https://www.youtube.com/watch?v=vv4zh_oPBTw)
- [The Kotlin DSL experience in Gradle](https://www.youtube.com/watch?v=m7tNOHUcDPU)

**Comment by lordcodes** [comment]
The Kotlin Lexer matches files with `.kts` extension, so is this issue resolved? Or is there something else about Gradle scripts not working?

**Comment by napperley** [comment]
Kotlin Script files are now recognised, however highlighting doesn't work properly with words surrounded by back ticks. Can see a example of this here: https://gitlab.com/webscene/webscene-core/blob/master/js/build.gradle.kts#L8

**Comment by lordcodes** [comment]
Kotlin Script files are supported to same extend as regular Kotlin files. The issue mentioned in the previous comment is a separate issue and is about the fact back-ticked identifiers aren't recognised when they are standalone. E.g.

```kotlin
`maven-published-plugin`
```

Back-ticked identifiers are supported in function names, but not standalone as above. This can be very noticeable when highlighting kts script files or build.gradle.kts files.

We should either rename this issue to that or mark this issue as closed and open a new issue for that.

**Comment by pyrmont** [comment]
I agree with @lordcodes. Basic Kotlin script was provided by #906. I've filed a new issue in #1325 to address hyphen support.
