### ISSUE TITLE
Should tests check for error tokens?

### ISSUE THREAD

**Issue by dblessing** [rouge-ruby/rouge#929]
When reviewing a PR I noticed there was an error token in the sample for the Nix lexer. I originally thought the change caused it so I tested on master, but the problem still existed. I thought automated testing was ensuring there were no error tokens. 

When I look at specs it looks like we assert no errors for the demo, but not the sample. Samples we only check to see if it throws an exception. 

Are tests supposed to catch error tokens in samples? @gfx @jneen

**Comment by miparnisari** [comment]
This is exactly why I submitted https://github.com/jneen/rouge/pull/852 :)

**Comment by pyrmont** [comment]
@dblessing I don't think it should be a problem if samples include an error. Not sure if @jneen or @gfx feel differently.

**Comment by pyrmont** [comment]
I think the answer to this should be no. There are samples that intentionally include errors to check the way error tokens work.
