### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by dblessing** [rouge-ruby/rouge#930]
Other maintainers have released this gem a number of times. I haven't so I have no clue what steps they like to go through in order to do so. 

@gfx Will you please walk me through your workflow sometime soon? Then I will document it for myself and future maintainers so we have a clear and repeatable process.

**Comment by miparnisari** [comment]
I think it should be simple:

1. Get access to https://rubygems.org/gems/rouge
1. Update version here: https://github.com/jneen/rouge/blob/master/lib/rouge/version.rb#L5
1. Publish! https://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

**Comment by jneen** [comment]
There's an "update the changelog" in there as well.

**Comment by dblessing** [comment]
Rubygems is the easy part. I was curious about any ancillary steps like
changelog, etc. Sounds like there isn’t anything else, though. I’ll do
manual changelog updates and publish. Thanks.

**Comment by jneen** [comment]
The changelog work could likely be mostly automated but I never got around to it.

**Comment by jneen** [comment]
(or we could take the GitLab approach and ask PR authors to write changelog entries)
