### ISSUE TITLE
Regex for python shebang is incorrect

### ISSUE THREAD

**Issue by FalkF** [rouge-ruby/rouge#945]
Using a shebang with a specific python subversion:
```
#!/usr/bin/env python3.6
```
breaks the syntax highlighting for the file.
It has probably to do with this [regex](https://github.com/jneen/rouge/blob/314f2d7756978b46c9dbe922aabbb39cd3d3a341/lib/rouge/lexers/python.rb#L14) ([example](http://rubular.com/r/dCAqIEVW2T)) as pointed out by [Mark Fletcher](https://gitlab.com/markglenfletcher) in the [Gitlab Issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/44194).

**Comment by julp** [comment]
Hi,

which version of rouge do you have? I can't reproduce the issue with my actual 3.1.1 version.

But, I think you're right, the regex should be more something like: `/pythonw?([32](\.\d)?)?/` because the minor version only apply to versions 2.X, not 3

**Comment by FalkF** [comment]
Thanks for looking into this. Your new regex seems to do the job. Sadly I have no way to verify it fast, since I encountered the issue in gitlabs snippets and am not familar with the workflow involved. I can verify it next weekend tho.

**Comment by dblessing** [comment]
I think we could even simplify things further. Rouge needs to highlight well, but it doesn't have to be always 100% syntactically correct for a language. So, for instance, we could do something like:

- `/pythonw?(\d(\.\d)?)?/` - Would match any `python<digit>.<digit>`. 
- `/pythonw?.*/` - Even more simplistic. If it starts with `python` or `pythonw` it's probably a safe bet.

**Comment by pyrmont** [comment]
@FalkF @julp I think PR #1172 fixes the problem but please let me know if you spot a mistake.
