### ISSUE TITLE
Add a wiki page with Docker instructions for development

### ISSUE THREAD

**Issue by nguillaumin** [rouge-ruby/rouge#947]
Similar to #733 I've been using Docker for development to avoid having to install Ruby and all the dependencies. Accepting #733 would make sense IMHO and help getting new people on board, but as an alternative I wrote instructions on how to use Docker with ad-hoc commands: https://gist.github.com/nguillaumin/a3f41095e735eb10112afa9c0e970893

If that's of interest it could be added as a wiki page next to the other guides. If not, then feel free to close this :)

**Comment by nguillaumin** [comment]
I think it would still bring value to have this page in the wiki.

**Comment by pyrmont** [comment]
@nguillaumin Thanks for replying and letting us know this is still active :)

I'm actually looking to move things from the wiki to documents in the `/docs` directory. Would you be interested in forking the repo, creating a branch, putting your instructions inside the `/docs` directory and then submitting a PR back? That would be helpful for me and would ensure your work has the appropriate credit in the Git history :)

**Comment by nguillaumin** [comment]
Done.

**Comment by pyrmont** [comment]
I just noticed this hadn't been closed automatically when #1214 was merged. This has now been addressed.
