### ISSUE TITLE
" in Multiline String Literals in Swift breaks highlighting

### ISSUE THREAD

**Issue by olivereisenhut** [rouge-ruby/rouge#955]
First of all thank you for this awesome project!

When putting a single quote into a multiline string literal the highlighting afterwards is broken. Testing code:
```swift
print("""
 Everything afterwards is handled as string because of this "
"""
let hans = "hello world"
```
Everything afterwards is handled as string.

Thank you!

Tested on http://rouge.jneen.net/ and also on gitlab.

**Comment by pyrmont** [comment]
I think the way to fix this might be to have a rule like [this one](https://github.com/rouge-ruby/rouge/pull/1253#discussion_r301955555) from the HOCON lexer.
