### ISSUE TITLE
jsx highlights closing > sign in red

### ISSUE THREAD

**Issue by pinkynrg** [rouge-ruby/rouge#956]
```
'''jsx
<QuickTable a={"a"}/>
'''
```

resulting in:

<img width="199" alt="screen shot 2018-07-11 at 1 03 47 am" src="https://user-images.githubusercontent.com/1474127/42542262-671de15c-84a6-11e8-8d4d-1425d157dfb5.png">

NOTE: using ' instead of ticks since i don't know how to escape ticks in markdown...

**Comment by dorian-marchal** [comment]
Same issue, here.

@pinkynrg Regarding the backtick escaping, you can indent your code with four spaces (try quoting me):

    ```jsx
    <QuickTable a={"a"}/>
    ```

**Comment by vidarh** [comment]
@pinkynrg @dorian-marchal 

The JSX lexer handles the example you give with a tiny adjustment - it does not accept JSX as a standalone expression, but e.g. `return <QuickTable a={"a"/>` works fine.

I'm of two minds about whether or not this is actually a bug or not - arguably it is not a bug, as just inlining JSX like that without passing it to a function, keyword or operator that'll actually do anything with it doesn't seem to make much sense.

**Comment by detj** [comment]
Facing this issue. Since, JSX is supported it should correctly syntax highlight. Anyone writing JavaScript with React code will encounter this issue.

Any idea how involved is the fix?

**Comment by pyrmont** [comment]
@detj I'm not seeing the issue in the latest version of Rouge. What version are you running and what is the text you're trying to lex?

**Comment by pyrmont** [comment]
Unfortunately, the shared linking is broken in the online dingus but if you copy and paste, you can see the text lexing correctly [here](http://rouge.jneen.net/).

**Comment by detj** [comment]
@pyrmont You're right. Apologies. This is a non-issue in the latest version. I was testing GitLab CE edition & the version they are using has this issue. So, it's on them.
