### ISSUE TITLE
Rust: Tuple indexing causes red highlight

### ISSUE THREAD

**Issue by stachetheoverlord** [rouge-ruby/rouge#958]
```
lorem.0
```
will cause the `.` to be highlighted...

**Comment by nixpulvis** [comment]
I too am seeing this on my site (seen at https://nixpulvis.com/ramblings/2019-05-10-fibonacci#iterative-in-rust).

![screenshot](https://user-images.githubusercontent.com/715947/57577488-16c43180-7446-11e9-9039-c95c53d0517a.png)
