### ISSUE TITLE
Support Haxe language?

### ISSUE THREAD

**Issue by jdonaldson** [rouge-ruby/rouge#96]
Pygments has support for version 3.0 of Haxe.  Would it be possible to port it to Rouge?  Here's the relevant lexer (in python):
https://bitbucket.org/birkenfeld/pygments-main/src/7304e4759ae65343d89a51359ca538912519cc31/pygments/lexers/web.py?at=default#cl-1131

It should be fairly similar to c#.

**Comment by byFd** [comment]
Sorry for digging out this old issue, but that would be really nice to have!

**Comment by frabbit** [comment]
Indeed, would be really nice to have.

**Comment by cmandlbaur** [comment]
Any update on this?

**Comment by uvtc** [comment]
Hi. Any update on this? Haxe 4 appears to be on the way --- the 4.0.0-preview.4 release was in June. Thanks!

**Comment by uvtc** [comment]
Oh! It appears there's a PR #815 for this, but it's a bit stuck at the moment. What's needed to help it along?

**Comment by pyrmont** [comment]
Woohoo! It's been checked in as https://github.com/rouge-ruby/rouge/commit/669dc1e21070bf742550f755e2bd6d8171ac632d :D
