### ISSUE TITLE
Rails 5.2 Support?

### ISSUE THREAD

**Issue by DanielKrolopp** [rouge-ruby/rouge#962]
I've been meaning to use this gem in my project, however it looks like it's not compatible with Rails 5.2 after a `gem install rogue`:
```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.2.0)

  In Gemfile:
    rails (= 5.2.0)

    rogue was resolved to 0.1.1, which depends on
      rails (>= 5.0.0.1, ~> 5.0.0)
```

Is there any time frame to know when it'll be updated? Thanks.

**Comment by dblessing** [comment]
`rogue` is not `rouge`. Did you make a typo on install or do you mean a
different gem? Rouge does not pin to any Rails version.
