### ISSUE TITLE
PowerShell lexer is missing ForEach-Object built-in cmdlet

### ISSUE THREAD

**Issue by markroloff** [rouge-ruby/rouge#966]
The lexer for PowerShell appears to be missing ForEach-Object. This is a built-in cmdlet, so would be nice consistent highlighting when using it.

![image](https://user-images.githubusercontent.com/8136829/43498609-f173b30e-9504-11e8-9e2b-5ed4cd7f297b.png)

**Comment by pyrmont** [comment]
@markroloff I'm sorry this took so long to address but we've updated Rouge with a new PowerShell lexer. The example you gave above lexes correctly now but if you see any problems, please let us know!
