### ISSUE TITLE
Add support for jsx syntax highlighting in .js files

### ISSUE THREAD

**Issue by BernardoFBBraga** [rouge-ruby/rouge#968]
As noted [here](https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904), using .jsx file extensions is not recommended.

Can we have JSX syntax highlighting in regular .js files?

I use gitlab at work and the syntax highlighting is terrible because of this.

**Comment by dblessing** [comment]
We might be able to switch things around slightly and instead of subclassing Javascript we could detect JSX inside the Javascript lexer itself and delegate to JSX. It may take a bit of reworking the current JSX lexer. I'm not familar with JS or JSX. If someone wants to take a crack at implementation that would be awesome. Otherwise, I'll investigate in the future.

**Comment by jneen** [comment]
In GitLab you can override the lexer choice based on `.gitattributes` as well.

https://docs.gitlab.com/ee/user/project/highlighting.html

**Comment by dblessing** [comment]
I suppose we could also disambiguate fairly if we allowed this to have .js
extension, as well? Would that be ill-advised @jneen? I suppose it depends
on how easily/definitively we can disambiguate

**Comment by jneen** [comment]
JSX isn't supported in vanilla javascript unfortunately :\

**Comment by jneen** [comment]
(I'm also not convinced of the reasoning behind not using .jsx as an extension, given the other highlighting issues it seems to be causing...)

**Comment by BernardoFBBraga** [comment]
@jneen there are plenty of arguments for and against using .jsx in this thread if you're interested: https://github.com/airbnb/javascript/pull/985

**Comment by BernardoFBBraga** [comment]
@dblessing it must be possible to disambiguate since vscode and github both disambiguate, parse and sintax highlight jsx correctly, refering to them as javascript

**Comment by jneen** [comment]
Is there a marking or some special comment that indicates that it is jsx, or do these tools just use a jsx lexer for all javascript? The reason I'm hesitant to do the latter is that the jsx lexer is a bit complicated and likely slow.

**Comment by BernardoFBBraga** [comment]
I'm not sure. I think vscode checks for imports of React on the javascript lexer to switch as it hints jsx as syntax error indicating that react should be imported
