### ISSUE TITLE
HTTP lexer : allow empty Reason Phrase in HTTP Response 

### ISSUE THREAD

**Issue by birou007** [rouge-ruby/rouge#977]
The HTTP lexer expect to have non-empty Reason Phrase (also called status message) in the status line of HTTP Response.
But the RFC 7230 says that the Reason Phrase is optional : https://tools.ietf.org/html/rfc7230#section-3.1.2

I think this part : 
https://github.com/jneen/rouge/blame/master/lib/rouge/lexers/http.rb
```
# response
rule %r(
  (HTTPS?)(/)(1[.][01])([ ]+) # http version
  (\d{3})([ ]+)               # status
  ([^\r\n]+)(\r?\n|$)       # status message
)x do
```

should be changed to something like : 
```
# response
rule %r(
  (HTTPS?)(/)(1[.][01])([ ]+) # http version
  (\d{3})([ ]+)               # status
  ([^\r\n]*)(\r?\n|$)       # status message
)x do
```

I discovered that because Tomcat 8.5 no longer send Reason Phrase : see https://bz.apache.org/bugzilla/show_bug.cgi?id=60183

**Comment by pyrmont** [comment]
I was just updating the HTTP lexer. This doesn't look like something that should be very difficult.
