### ISSUE TITLE
I think rogue could use some better usage examples, especially for Ruby on Rails

### ISSUE THREAD

**Issue by ndbroadbent** [rouge-ruby/rouge#985]
Thanks for building this! I got it working, but just wanted to leave some feedback because it wasn't the best developer experience.

It's quite difficult to figure out how to use rouge, and I think the Readme could use some better examples. For example, it's not immediately obvious how to render multiple lines of code with line breaks, and I couldn't find any API documentation. I didn't know if `Rouge::Formatters::HTML.new` could do that, or if I should use `Rouge::Formatters::HTMLLinewise` or `Rouge::Formatters::HTMLTable`. I think there was a few too many options, and it would be nice if there was just one default option that handled most things properly.

I also just found the `rouge-rails` gem at the bottom of the "Other integrations" section, but I think that could be more prominent, maybe with it's own section near the top of the Readme. I think most developers who find the rouge gem will probably be using Rails, and just want to render some code in their Rails views. So it might make sense to highlight this more prominently, or even merge this Rails integration into Rogue and have some better documentation in the Readme. The `rouge-rails` documentation could also use some better examples - I had to search through the source code to figure out how to include a single stylesheet, instead of all of them: `@import "rouge/github";`

Just thought it might be useful to mention this, since I ended up spending about 30 minutes figuring out how everything worked, and some better examples might have saved me about 25 minutes. But it's a great library and thanks for all your work!

**Comment by dblessing** [comment]
Thanks for the feedback, @ndbroadbent. We could add some more examples.

**Comment by jschulenklopper** [comment]
TFW someone has the same developer experience as yourself :-D In the end, I got it working (with `rouge-rails` as well) but only after some trial and error.
